'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.join(__dirname,'..'),gen=fs.readFileSync(path.join(root,'games/sudoku-generator.js'),'utf8'),bank=fs.readFileSync(path.join(root,'games/sudoku-bank.js'),'utf8'),lib=fs.readFileSync(path.join(root,'games/sudoku-library.js'),'utf8');
function context(){const c={console,globalThis:null,window:null,Map,Set,WeakMap};c.globalThis=c;c.window=c;vm.createContext(c);vm.runInContext(bank,c);vm.runInContext(gen,c);return c;}
function variant(c){const v=c.SudokuBank.find(x=>x.id==='arrow');assert.ok(v);return v;}
function median(xs){const a=xs.slice().sort((x,y)=>x-y),m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2;}
test('Arrow canonical solution satisfies every arrow',()=>{const c=context(),v=variant(c);for(const a of v.data.arrows){const cv=v.solution[a.circle[0]][a.circle[1]],sum=a.path.reduce((s,p)=>s+v.solution[p[0]][p[1]],0);assert.equal(sum,cv);}});
test('Arrow renderer enforces arrow sum conflicts',()=>{assert.match(lib,/v\.kind==='arrow'/);assert.match(lib,/d\.arrows/);});
test('Arrow generation is deterministic, solver-certified and variant-essential',()=>{const c=context(),v=variant(c);for(const d of ['gentle','focused','expert'])for(const seed of [1,17,101,2026]){const a=c.SudokuGenerator.make(v,seed,d),b=c.SudokuGenerator.make(v,seed,d);assert.deepEqual(a.puzzle,b.puzzle);assert.equal(a.generation.unique,true);assert.equal(a.generation.verification,'solver-verified');assert.equal(a.generation.mode,'seeded-variant-essential');assert.equal(a.generation.variantEssential,true);assert.equal(c.SudokuGenerator.countVariantSolutions(a.puzzle,a,2),1);assert.ok(c.SudokuGenerator.countSolutions(a.puzzle,2)>1);}});
test('Arrow exposes measured Gentle < Focused < Expert difficulty',()=>{const c=context(),v=variant(c),scores={gentle:[],focused:[],expert:[]};for(const d of Object.keys(scores))for(const seed of [1,17,101,2026,20260828])scores[d].push(c.SudokuGenerator.make(v,seed,d).generation.difficultyScore);assert.ok(median(scores.gentle)<median(scores.focused));assert.ok(median(scores.focused)<median(scores.expert));});
test('Arrow retains shared notes, Check cleanup, completion and language refresh',()=>{assert.match(lib,/note-mode-button/);assert.match(lib,/classList\.remove\('checked-wrong'\)/);assert.match(lib,/api\.solved\(\)/);assert.match(lib,/refreshLanguage:function\(\)/);});
