'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.join(__dirname,'..'),gen=fs.readFileSync(path.join(root,'games/sudoku-generator.js'),'utf8'),bank=fs.readFileSync(path.join(root,'games/sudoku-bank.js'),'utf8'),core=fs.readFileSync(path.join(root,'games/extra-house-generator-core.js'),'utf8'),hardening=fs.readFileSync(path.join(root,'games/extra-house-generator-hardening.js'),'utf8'),lib=fs.readFileSync(path.join(root,'games/sudoku-library.js'),'utf8');
function context(){const c={console,globalThis:null,window:null,Map,Set,WeakMap};c.globalThis=c;c.window=c;vm.createContext(c);vm.runInContext(bank,c);vm.runInContext(gen,c);vm.runInContext(core,c);vm.runInContext(hardening,c);return c;}
function variant(c,id){const v=c.SudokuBank.find(x=>x.id===id);assert.ok(v,'missing variant '+id);return v;}
function median(xs){const a=xs.slice().sort((x,y)=>x-y),m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2;}
const specs=[{id:'xv',title:'XV Sudoku',valid(v){for(const e of v.data.edges){const a=v.solution[e.a[0]][e.a[1]],b=v.solution[e.b[0]][e.b[1]];assert.equal(a+b,e.sum);}}},{id:'consecutive',title:'Consecutive Sudoku',valid(v){for(const e of v.data.edges){const a=v.solution[e.a[0]][e.a[1]],b=v.solution[e.b[0]][e.b[1]];assert.equal(Math.abs(a-b),1);}}},{id:'greater',title:'Greater Than Sudoku',valid(v){for(const e of v.data.edges){const a=v.solution[e.a[0]][e.a[1]],b=v.solution[e.b[0]][e.b[1]];assert.ok(e.op==='>'?a>b:a<b);}}},{id:'odd-even',title:'Odd / Even Sudoku',valid(v){for(const [key,parity] of Object.entries(v.data)){const [r,c]=key.split(',').map(Number),value=v.solution[r][c];assert.equal(value%2===0,parity==='even');}}}];
for(const spec of specs){test(spec.title+' canonical solution satisfies its variant rules',()=>{const c=context();spec.valid(variant(c,spec.id));});test(spec.title+' generation is deterministic, solver-certified and variant-essential',()=>{const c=context(),v=variant(c,spec.id);for(const d of ['gentle','focused','expert'])for(const seed of [1,17,101,2026]){const a=c.SudokuGenerator.make(v,seed,d),b=c.SudokuGenerator.make(v,seed,d);assert.deepEqual(a,b);assert.equal(a.generation.unique,true);assert.equal(a.generation.verification,'solver-verified');assert.equal(a.generation.mode,'seeded-variant-essential');assert.equal(a.generation.variantEssential,true);assert.equal(c.SudokuGenerator.countVariantSolutions(a.puzzle,a,2),1);assert.ok(c.SudokuGenerator.countSolutions(a.puzzle,2)>1);if(['xv','consecutive','greater'].includes(spec.id))assert.equal(a.generation.generatorFamily,'adjacency-fresh-fill-mrv');if(spec.id==='odd-even')assert.equal(a.generation.generatorFamily,'parity-fresh-fill-mrv');}});test(spec.title+' exposes measured Gentle < Focused < Expert difficulty',()=>{const c=context(),v=variant(c,spec.id),scores={gentle:[],focused:[],expert:[]};for(const d of Object.keys(scores))for(const seed of [1,17,101,2026,20260828])scores[d].push(c.SudokuGenerator.make(v,seed,d).generation.difficultyScore);assert.ok(median(scores.gentle)<median(scores.focused));assert.ok(median(scores.focused)<median(scores.expert));});}
test('fresh cell-relation variants vary both solution and constraint topology',()=>{const c=context();for(const id of ['xv','consecutive','greater','odd-even']){const v=variant(c,id),solutions=new Set(),topologies=new Set();for(const seed of [1,17,101,2026]){const g=c.SudokuGenerator.make(v,seed,'focused');specFor(id).valid(g);solutions.add(JSON.stringify(g.solution));topologies.add(id==='odd-even'?Object.keys(g.data).sort().join('|'):JSON.stringify(g.data.edges));}assert.ok(solutions.size>1,id+' solution diversity');assert.ok(topologies.size>1,id+' topology diversity');}});
function specFor(id){return specs.find(s=>s.id===id);}
test('cell-relation renderers enforce their production constraints',()=>{assert.match(lib,/v\.kind==='xv'&&x\+y!==a\.sum/);assert.match(lib,/v\.kind==='consecutive'&&Math\.abs\(x-y\)!==1/);assert.match(lib,/v\.kind==='greater'&&!/);assert.match(lib,/v\.kind==='parity'/);});
test('cell-relation variants retain shared Sudoku lifecycle',()=>{assert.match(lib,/note-mode-button/);assert.match(lib,/classList\.remove\('checked-wrong'\)/);assert.match(lib,/api\.solved\(\)/);assert.match(lib,/refreshLanguage:function\(\)/);});
