'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const C=require('../games/classic-human/contracts.js');const S=require('../games/classic-human/solver.js');const M=require('../games/classic-human/msls.js');
const INKALA='800000000003600000070090200050007000000045700000100030001000068008500010090000400';
const PRIMARY=[2,3,4,8],DIGITS=[1,3,6,8];
function desired(ds,orientation='rows'){return ds.find(d=>d.explanationData.orientation===orientation&&JSON.stringify(d.explanationData.primarySectors)===JSON.stringify(PRIMARY)&&JSON.stringify(d.explanationData.digits)===JSON.stringify(DIGITS));}
function transposeState(s){const t=new S.ClassicHumanState(s.grid.map((_,r)=>s.grid.map(row=>row[r])));for(let r=0;r<9;r++)for(let c=0;c<9;c++)t.masks[C.cellIndex(c,r)]=s.masks[C.cellIndex(r,c)];return t;}
function relabelState(s,map){const t=new S.ClassicHumanState('.'.repeat(81));for(let i=0;i<81;i++){const rc=C.rowCol(i),v=s.grid[rc[0]][rc[1]];if(v)t.grid[rc[0]][rc[1]]=map[v];t.masks[i]=C.digitsFromMask(s.masks[i]).reduce((m,d)=>m|C.bitForDigit(map[d]),0);}return t;}
function baseState(){return new S.ClassicHumanState(INKALA);}
function elimKeys(d){return d.eliminations.map(x=>x.cell+':'+x.digit);}
function assertRankZeroCover(d){const base=d.explanationData.baseCandidates,covers=d.explanationData.covers;assert.equal(covers.length,d.explanationData.truthCount);const covered=new Map();for(const cv of covers){for(const n of base){const rc=C.rowCol(n.cell);const hit=cv.type==='cell'?n.cell===cv.cell:cv.type==='column-digit'?rc[1]+1===Number(cv.house.slice(1))&&n.digit===cv.digit:rc[0]+1===Number(cv.house.slice(1))&&n.digit===cv.digit;if(hit)covered.set(n.cell+':'+n.digit,(covered.get(n.cell+':'+n.digit)||0)+1);}}assert.equal(covered.size,base.length);assert.ok([...covered.values()].every(v=>v===1));}
function oracleNodes(s){const nodes=[];for(let si=0;si<PRIMARY.length;si++)for(let di=0;di<DIGITS.length;di++){const digit=DIGITS[di],bit=C.bitForDigit(digit);let count=0;for(let c=0;c<9;c++){const cell=C.cellIndex(PRIMARY[si],c);if(!s.grid[PRIMARY[si]][c]&&(s.masks[cell]&bit)){nodes.push({cell,digit,truth:si*DIGITS.length+di});count++;}}if(!count)return null;}return nodes;}
function oracleHasExactRankZeroCover(s){const nodes=oracleNodes(s);if(!nodes)return false;const truthCount=PRIMARY.length*DIGITS.length,links=[];const byCell=new Map(),byColDigit=new Map();for(let i=0;i<nodes.length;i++){const n=nodes[i],col=C.rowCol(n.cell)[1],ck=n.cell,dk=col+':'+n.digit;if(!byCell.has(ck))byCell.set(ck,[]);byCell.get(ck).push(i);if(!byColDigit.has(dk))byColDigit.set(dk,[]);byColDigit.get(dk).push(i);}for(const [cell,ns] of [...byCell.entries()].sort((a,b)=>a[0]-b[0]))if(ns.length>=2)links.push(ns);for(const [key,ns] of [...byColDigit.entries()].sort((a,b)=>a[0].localeCompare(b[0])))if(ns.length>=2)links.push(ns);const byNode=Array.from({length:nodes.length},()=>[]);for(let li=0;li<links.length;li++)for(const n of links[li])byNode[n].push(li);const covered=new Uint8Array(nodes.length);function rec(chosen,coveredCount){if(coveredCount===nodes.length)return chosen===truthCount;if(chosen>=truthCount)return false;let opts=null;for(let n=0;n<nodes.length;n++){if(covered[n])continue;const local=byNode[n].filter(li=>links[li].every(x=>!covered[x]));if(!local.length)return false;if(opts===null||local.length<opts.length){opts=local;if(opts.length===1)break;}}for(const li of opts){for(const n of links[li])covered[n]=1;if(rec(chosen+1,coveredCount+links[li].length))return true;for(const n of links[li])covered[n]=0;}return false;}return rec(0,0);}
function combinations(items,size,visit){const chosen=[];function rec(start){if(chosen.length===size)return visit(chosen.slice());for(let i=start;i<=items.length-(size-chosen.length);i++){chosen.push(items[i]);if(rec(i+1))return true;chosen.pop();}return false;}return rec(0);}

test('MSLS finds the documented four-row Inkala rank-zero structure with exact cover proof',()=>{const s=baseState(),before=Array.from(s.masks),d=desired(M.findMultiSectorLockedSet(s));assert.ok(d);assert.equal(d.explanationData.rank,0);assert.equal(d.explanationData.truthCount,16);assert.ok(d.eliminations.length>1);assertRankZeroCover(d);assert.equal(oracleHasExactRankZeroCover(s),true);assert.deepEqual(Array.from(s.masks),before);});

test('MSLS column transpose preserves the rank-zero structure and eliminations',()=>{const a=baseState(),da=desired(M.findMultiSectorLockedSet(a));assert.ok(da);const b=transposeState(a),db=desired(M.findMultiSectorLockedSet(b),'columns');assert.ok(db);const expected=da.eliminations.map(x=>{const [r,c]=C.rowCol(x.cell);return C.cellIndex(c,r)+':'+x.digit;}).sort();assert.deepEqual(elimKeys(db).sort(),expected);assertRankZeroCover(db);});

test('MSLS rejects an oracle-proven broken-cover near miss while all truths remain',()=>{const original=baseState(),d=desired(M.findMultiSectorLockedSet(original));assert.ok(d);const cells=[...new Set(d.explanationData.covers.filter(x=>x.type==='cell').map(x=>x.cell))].sort((a,b)=>a-b),baseMask=DIGITS.reduce((m,x)=>m|C.bitForDigit(x),0);let witness=null;for(let size=1;size<=Math.min(4,cells.length)&&!witness;size++)combinations(cells,size,subset=>{const s=baseState();for(const cell of subset){const next=s.masks[cell]&~baseMask;if(!next)return false;s.restrictMask(cell,next);}if(!oracleNodes(s)||oracleHasExactRankZeroCover(s))return false;witness=s;return true;});assert.ok(witness,'fixture must yield a bounded multi-cell mutation with all truths present and no exact rank-zero cover');assert.equal(oracleHasExactRankZeroCover(witness),false);assert.equal(!!desired(M.findMultiSectorLockedSet(witness)),false);});

test('MSLS rejects a sector escape / missing truth occurrence near miss',()=>{const s=baseState(),d=desired(M.findMultiSectorLockedSet(s));assert.ok(d);const n=d.explanationData.baseCandidates[0],sameTruth=d.explanationData.baseCandidates.filter(x=>x.truth===n.truth);assert.ok(sameTruth.length>=2);for(const x of sameTruth){const next=s.masks[x.cell]&~C.bitForDigit(x.digit);if(next)s.restrictMask(x.cell,next);}assert.equal(!!desired(M.findMultiSectorLockedSet(s)),false);});

test('MSLS never self-eliminates a base candidate and applies safely',()=>{const s=baseState(),d=desired(M.findMultiSectorLockedSet(s));assert.ok(d);const protectedSet=new Set(d.explanationData.baseCandidates.map(x=>x.cell+':'+x.digit));assert.ok(d.eliminations.every(x=>!protectedSet.has(x.cell+':'+x.digit)));assert.equal(s.apply(d),true);assert.equal(s.valid,true);});

test('MSLS digit relabeling preserves geometry and proof cardinality',()=>{const s=baseState(),map={1:4,2:5,3:6,4:7,5:8,6:9,7:1,8:2,9:3},t=relabelState(s,map),target=DIGITS.map(x=>map[x]).sort((a,b)=>a-b),d=M.findMultiSectorLockedSet(t).find(x=>x.explanationData.orientation==='rows'&&JSON.stringify(x.explanationData.primarySectors)===JSON.stringify(PRIMARY)&&JSON.stringify(x.explanationData.digits)===JSON.stringify(target));assert.ok(d);assert.equal(d.explanationData.truthCount,16);assertRankZeroCover(d);});

test('MSLS enumeration is deterministic and repeated-call stable',()=>{const s=baseState();assert.deepEqual(M.findMultiSectorLockedSet(s),M.findMultiSectorLockedSet(s));});

test('MSLS enforces explicit hard budgets and bounded output',()=>{const s=baseState();assert.throws(()=>M.findMultiSectorLockedSet(s,{maxPrimarySectors:5}),/maxPrimarySectors/);assert.throws(()=>M.findMultiSectorLockedSet(s,{maxDigits:7}),/maxDigits/);assert.throws(()=>M.findMultiSectorLockedSet(s,{maxPatterns:65}),/maxPatterns/);assert.throws(()=>M.findMultiSectorLockedSet(s,{maxCombinations:20001}),/maxCombinations/);assert.ok(M.findMultiSectorLockedSet(s,{maxPatterns:1}).length<=1);assert.doesNotThrow(()=>M.findMultiSectorLockedSet(s,{maxCombinations:1}));});

test('MSLS is verified production-trusted and remains server-preferred after dedicated PASS',()=>{const meta=C.TECHNIQUES['multi-sector-locked-set'];assert.equal(meta.serverPreferred,true);assert.equal(meta.implementationStatus,'WIRED');assert.equal(meta.auditStatus,'VERIFIED');assert.equal(meta.productionTrusted,true);const index=require('../games/classic-human/index.js');const finder=index.FINDERS.find(x=>x.id==='multi-sector-locked-set');assert.ok(finder);assert.equal(finder.serverPreferred,true);assert.equal(typeof index.findMultiSectorLockedSet,'function');});
