'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.join(__dirname,'..');
const gen=fs.readFileSync(path.join(root,'games/sudoku-generator.js'),'utf8');
const core=fs.readFileSync(path.join(root,'games/extra-house-generator-core.js'),'utf8');
const hardening=fs.readFileSync(path.join(root,'games/diagonal-generator-hardening.js'),'utf8');
const bank=fs.readFileSync(path.join(root,'games/sudoku-bank.js'),'utf8');
const lib=fs.readFileSync(path.join(root,'games/sudoku-library.js'),'utf8');
const mobile=fs.readFileSync(path.join(root,'assets/sudoku-mobile.css'),'utf8');
function context(){const ctx={console,globalThis:null,Map,Set,WeakMap};ctx.globalThis=ctx;vm.createContext(ctx);vm.runInContext(bank,ctx,{filename:'sudoku-bank.js'});vm.runInContext(gen,ctx,{filename:'sudoku-generator.js'});vm.runInContext(core,ctx,{filename:'extra-house-generator-core.js'});vm.runInContext(hardening,ctx,{filename:'diagonal-generator-hardening.js'});return ctx;}
function diagonal(ctx){const v=ctx.SudokuBank.find(x=>x.id==='diagonal');assert.ok(v,'canonical diagonal variant must exist');return v;}
function diagonalsValid(grid){const n=grid.length,want=Array.from({length:n},(_,i)=>i+1).join(',');return [grid.map((row,i)=>row[i]),grid.map((row,i)=>row[n-1-i])].every(line=>line.slice().sort((a,b)=>a-b).join(',')===want);}
function median(xs){const a=xs.slice().sort((x,y)=>x-y),m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2;}
function normalizeSymbols(grid){const map=new Map();let next=1;return grid.map(row=>row.map(v=>{if(!map.has(v))map.set(v,next++);return map.get(v);}));}
function rotate(grid){const n=grid.length;return Array.from({length:n},(_,r)=>Array.from({length:n},(_,c)=>grid[n-1-c][r]));}
function reflect(grid){return grid.map(row=>row.slice().reverse());}
function structuralFingerprint(grid){const forms=[];let g=grid.map(row=>row.slice());for(let i=0;i<4;i++){for(const x of [g,reflect(g)])forms.push(normalizeSymbols(x).flat().join(''));g=rotate(g);}forms.sort();return forms[0];}

test('Diagonal canonical solution satisfies both X diagonals',()=>{const ctx=context(),v=diagonal(ctx);assert.equal(v.kind,'diagonal');assert.equal(v.solution.length,9);assert.ok(diagonalsValid(v.solution),'both long diagonals must contain 1-9 exactly once');});

test('Diagonal generation is variant-essential and solver-certified unique',()=>{const ctx=context(),G=ctx.SudokuGenerator,v=diagonal(ctx);for(const d of ['gentle','focused','expert'])for(const seed of [1,17,101,2026]){const g=G.make(v,seed,d);assert.equal(g.generation.mode,'seeded-variant-essential',d+' '+seed+' must use variant-essential generation');assert.equal(g.generation.unique,true,d+' '+seed+' unique under diagonal rules');assert.equal(g.generation.verification,'solver-verified');assert.equal(g.generation.variantEssential,true);assert.equal(G.countSolutions(g.puzzle,2)>1,true,d+' '+seed+' must not be Classic-unique');assert.ok(diagonalsValid(g.solution),d+' '+seed+' solution must retain both diagonal constraints');}});

test('Diagonal fresh generation is deterministic and structurally diverse',()=>{const ctx=context(),G=ctx.SudokuGenerator,v=diagonal(ctx),seeds=Array.from({length:16},(_,i)=>1000+i),solutions=new Set(),structures=new Set();for(const seed of seeds){const a=G.make(v,seed,'focused'),b=G.make(v,seed,'focused');assert.deepEqual(a.solution,b.solution,'same seed must replay exact solution');assert.deepEqual(a.puzzle,b.puzzle,'same seed must replay exact puzzle');assert.equal(a.generation.generatorFamily,'diagonal-fresh-fill-mrv');assert.ok(Number.isInteger(a.generation.solutionGenerationNodes)&&a.generation.solutionGenerationNodes>0);solutions.add(JSON.stringify(a.solution));structures.add(structuralFingerprint(a.solution));}assert.ok(solutions.size>=15,'expected broad completed-solution diversity, got '+solutions.size+'/16');assert.ok(structures.size>=12,'expected broad structural diversity after symbol/D4 normalization, got '+structures.size+'/16');});

test('Diagonal runtime no longer carves from the canonical solution',()=>{const ctx=context(),G=ctx.SudokuGenerator,v=diagonal(ctx),canonical=JSON.stringify(v.solution);for(const seed of [31,32,33,34])assert.notEqual(JSON.stringify(G.make(v,seed,'focused').solution),canonical,'seed '+seed+' must use a fresh completed grid');});

test('Diagonal difficulty keeps ordered clue targets and measured search medians',()=>{const ctx=context(),G=ctx.SudokuGenerator,v=diagonal(ctx),seeds=[1,17,101,2026,20260827],scores={gentle:[],focused:[],expert:[]},clues={gentle:new Set(),focused:new Set(),expert:new Set()};for(const d of Object.keys(scores))for(const seed of seeds){const g=G.make(v,seed,d);scores[d].push(g.generation.difficultyScore);clues[d].add(g.generation.clues);assert.ok(Number.isFinite(g.generation.difficultyScore)&&g.generation.difficultyScore>0,d+' '+seed+' measured difficulty');}assert.ok([...clues.gentle].every(x=>x<=40),'Gentle may remove extra clues only to force variant-essentiality');assert.ok([...clues.focused].every(x=>x<=32),'Focused may remove extra clues only to force variant-essentiality');assert.ok([...clues.expert].every(x=>x<=27),'Expert may remove extra clues only to force variant-essentiality');const med={gentle:median(scores.gentle),focused:median(scores.focused),expert:median(scores.expert)};assert.ok(med.gentle<med.focused,'Focused median must exceed Gentle: '+JSON.stringify(med));assert.ok(med.focused<med.expert,'Expert median must exceed Focused: '+JSON.stringify(med));});

test('Diagonal renderer visibly marks the X and retains shared interaction/language lifecycle',()=>{assert.match(lib,/kindIs\(v,'diagonal'\)\) board\.classList\.add\('show-diagonals'\)/,'renderer must mark diagonal boards');assert.match(lib,/v\.kind==='diagonal'/,'renderer validator must enforce diagonal duplicates');assert.match(lib,/refreshLanguage\s*:\s*function\(\)/,'shared board must refresh language in place');assert.match(lib,/note-mode-button/);assert.match(lib,/Backspace|Delete/);assert.match(lib,/clear-button/);assert.match(lib,/check-button/);});

test('Diagonal 9x9 inherits the shared 44px mobile board contract',()=>{assert.match(mobile,/\.sudoku-board-host:has\(\.sudoku-board\[style\*="--sudoku-size: 9"\]\)\s*\{[^}]*overflow-x:\s*auto/,'9x9 host must scroll horizontally');assert.match(mobile,/\.sudoku-board-shell:has\(\.sudoku-board\[style\*="--sudoku-size: 9"\]\)\s*\{[^}]*min-width:\s*410px/,'9x9 shell must preserve 410px minimum geometry');});
