'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.join(__dirname,'..');
function load(name){return fs.readFileSync(path.join(root,name),'utf8');}
function context(){const c={console,globalThis:null,window:null,Map,Set,WeakMap};c.globalThis=c;c.window=c;vm.createContext(c);for(const f of ['games/sudoku-bank.js','games/sudoku-generator.js','games/extra-house-generator-core.js','games/diagonal-generator-hardening.js','games/extra-house-generator-hardening.js'])vm.runInContext(load(f),c,{filename:f});return c;}
function variant(c){const v=c.SudokuBank.find(x=>x.id==='greater');assert.ok(v);return v;}
function median(xs){const a=xs.slice().sort((x,y)=>x-y),m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2;}
function edgesValid(g){return (g.data.edges||[]).length>0&&(g.data.edges||[]).every(e=>{const a=g.solution[e.a[0]][e.a[1]],b=g.solution[e.b[0]][e.b[1]];return e.op==='>'?a>b:e.op==='<'?a<b:false;});}
test('Greater Than fresh generation is deterministic, exact-unique and variant-essential',()=>{const c=context(),v=variant(c);for(const d of ['gentle','focused','expert'])for(const seed of [1,17,101,2026]){const a=c.SudokuGenerator.make(v,seed,d),b=c.SudokuGenerator.make(v,seed,d);assert.deepEqual(a,b);assert.equal(a.generation.unique,true);assert.equal(a.generation.variantEssential,true);assert.equal(c.SudokuGenerator.countVariantSolutions(a.puzzle,a,2),1);assert.ok(c.SudokuGenerator.countSolutions(a.puzzle,2)>1);assert.equal(edgesValid(a),true);assert.ok(a.data.edges.length>=24&&a.data.edges.length<=32);}});
test('Greater Than regenerates solution and inequality topology across seeds',()=>{const c=context(),v=variant(c),solutions=new Set(),topologies=new Set();for(let seed=7000;seed<7016;seed++){const g=c.SudokuGenerator.make(v,seed,'focused');solutions.add(JSON.stringify(g.solution));topologies.add(JSON.stringify(g.data.edges));}assert.ok(solutions.size>=15,'expected fresh solutions');assert.ok(topologies.size>=15,'expected fresh inequality topologies');});
test('Greater Than keeps ordered measured difficulty',()=>{const c=context(),v=variant(c),scores={gentle:[],focused:[],expert:[]};for(const d of Object.keys(scores))for(const seed of [1,17,101,2026,20260828])scores[d].push(c.SudokuGenerator.make(v,seed,d).generation.difficultyScore);assert.ok(median(scores.gentle)<median(scores.focused));assert.ok(median(scores.focused)<median(scores.expert));});
