'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');global.window=global;
for(const f of ['sudoku-bank.js','sudoku-bank-iteration2.js','sudoku-bank-iteration3.js','sudoku-bank-iteration4.js','sudoku-bank-iteration5.js','sudoku-bank-iteration6.js','sudoku-bank-iteration7.js','sudoku-bank-iteration8.js','sudoku-bank-iteration9.js','sudoku-bank-iteration10.js','sudoku-bank-iteration11.js','sudoku-bank-iteration12.js','sudoku-bank-iteration13.js','sudoku-bank-iteration14.js','sudoku-bank-iteration15.js','sudoku-bank-iteration16.js','sudoku-bank-iteration17.js','sudoku-bank-iteration18.js','sudoku-generator.js','extra-house-generator-core.js','diagonal-generator-hardening.js','iteration4-generator-hardening.js','iteration5-generator-hardening.js','iteration6-generator-hardening.js','iteration7-generator-hardening.js','iteration8-generator-hardening.js','iteration9-generator-hardening.js','iteration10-generator-hardening.js','iteration11-generator-hardening.js','iteration12-generator-hardening.js','iteration13-generator-hardening.js','iteration14-generator-hardening.js','iteration15-generator-hardening.js','iteration16-generator-hardening.js','iteration17-generator-hardening.js','iteration18-generator-hardening.js'])vm.runInThisContext(fs.readFileSync(path.join(root,'games',f),'utf8'));
const difficulties=['gentle','focused','expert'];
function variant(){return SudokuBank.find(v=>v.id==='domino-skyscrapers');}
function line(v,cl){let a=cl.axis==='row'?v.solution[cl.index].slice():v.solution.map(r=>r[cl.index]);if(cl.side==='right'||cl.side==='bottom')a.reverse();return a;}
function visibleCount(a){let m=0,n=0;for(const x of a)if(x>m){m=x;n++;}return n;}
function givens(p){return p.flat().filter(Boolean).length;}

test('Iteration 18 static solution satisfies Latin, visibility and equal-domino-sum rules',()=>{const v=variant();for(const row of v.solution)assert.deepEqual([...row].sort((a,b)=>a-b),[1,2,3,4,5,6,7]);for(let c=0;c<7;c++)assert.deepEqual(v.solution.map(r=>r[c]).sort((a,b)=>a-b),[1,2,3,4,5,6,7]);for(const cl of v.data.clues)assert.equal(visibleCount(line(v,cl)),cl.count,JSON.stringify(cl));const sums=v.data.dominoes.map(dm=>dm.reduce((s,p)=>s+v.solution[p[0]][p[1]],0));assert.equal(new Set(sums).size,1);});

test('Iteration 18 generation is deterministic, seed-diverse, unique and variant-essential',()=>{const v=variant();for(const difficulty of difficulties){const a=SudokuGenerator.make(v,1818,difficulty),b=SudokuGenerator.make(v,1818,difficulty),c=SudokuGenerator.make(v,2026,difficulty);assert.deepEqual(a.puzzle,b.puzzle,'deterministic '+difficulty);assert.notDeepEqual(a.puzzle,c.puzzle,'seed-diverse '+difficulty);assert.equal(a.generation.unique,true,'unique '+difficulty);assert.equal(a.generation.variantEssential,true,'essential '+difficulty);assert.equal(SudokuGenerator.countDominoSkyscraperSolutions(a.puzzle,a,2,false),1,'solver unique '+difficulty);assert.ok(SudokuGenerator.countDominoSkyscraperSolutions(a.puzzle,a,2,true)>1,'Latin baseline ambiguous '+difficulty);}});

test('Iteration 18 difficulty is clue-ordered and carries measured variant search evidence',()=>{const v=variant(),made=difficulties.map(d=>SudokuGenerator.make(v,1822,d));assert.ok(givens(made[0].puzzle)>=givens(made[1].puzzle),'gentle/focused clues');assert.ok(givens(made[1].puzzle)>=givens(made[2].puzzle),'focused/expert clues');for(const x of made){assert.ok(x.generation.searchStats,'search stats');for(const k of ['nodes','branches','deadEnds','solutions'])assert.equal(typeof x.generation.searchStats[k],'number',k);assert.equal(typeof x.generation.difficultyScore,'number','difficulty score');assert.ok(x.generation.difficultyScore>=0,'nonnegative score');}});

test('Iteration 18 runtime enforcement and visual hooks are present',()=>{const gen=fs.readFileSync(path.join(root,'games/sudoku-generator.js'),'utf8'),lib=fs.readFileSync(path.join(root,'games/sudoku-library.js'),'utf8');for(const t of ['countDominoSkyscraperSolutions','makeDominoSkyscraperPuzzle',"variant.kind==='dominoskyscrapers'"])assert.ok(gen.includes(t),t);for(const t of ["kindIs(vdef,'dominoskyscrapers')",'dominoSkyscraperConflict',"kindIs(v,'dominoskyscrapers')",'domino-cell'])assert.ok(lib.includes(t),t);});
