const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.join(__dirname,'..'),ctx={console,Map,Set,Math,JSON,Array,Object,Number,String,Boolean,Date,Uint8Array};ctx.globalThis=ctx;vm.createContext(ctx);
for(const f of fs.readdirSync(path.join(root,'games')).filter(x=>/^sudoku-bank(?:-iteration\d+)?\.js$/.test(x)).sort((a,b)=>{const n=x=>+(x.match(/iteration(\d+)/)||[,0])[1];return n(a)-n(b)}).concat(['sudoku-generator.js']))vm.runInContext(fs.readFileSync(path.join(root,'games',f),'utf8'),ctx,{filename:f});
const by=id=>ctx.SudokuBank.find(x=>x.id===id),Y=by('yajilin'),count=(p,l=2,s={})=>ctx.SudokuGenerator.countYajilinSolutions(p,l,s);
function independentSolutionCheck(g){const n=g.puzzle.size,clues=new Map(g.puzzle.clues.map(x=>[x.r+','+x.c,x])),black=g.solution.black,dirs={right:[0,1],left:[0,-1],up:[-1,0],down:[1,0]};for(const cl of g.puzzle.clues){let k=0,d=dirs[cl.dir];for(let r=cl.r+d[0],c=cl.c+d[1];r>=0&&c>=0&&r<n&&c<n;r+=d[0],c+=d[1])if(black[r][c])k++;assert.equal(k,cl.clue,'arrow count');}for(let r=0;r<n;r++)for(let c=0;c<n;c++)if(black[r][c])for(const [dr,dc] of [[1,0],[0,1]])if(r+dr<n&&c+dc<n)assert.equal(black[r+dr][c+dc],false,'black adjacency');const deg=new Map(),adj=new Map();for(const e of g.solution.edges){const a=e[0]+','+e[1],b=e[2]+','+e[3];deg.set(a,(deg.get(a)||0)+1);deg.set(b,(deg.get(b)||0)+1);if(!adj.has(a))adj.set(a,[]);if(!adj.has(b))adj.set(b,[]);adj.get(a).push(b);adj.get(b).push(a);}for(let r=0;r<n;r++)for(let c=0;c<n;c++){const k=r+','+c;if(clues.has(k)||black[r][c]){assert.equal(deg.get(k)||0,0,'excluded cell has edge');}else assert.equal(deg.get(k),2,'loop degree');}const start=adj.keys().next().value,seen=new Set([start]),stack=[start];while(stack.length){for(const w of adj.get(stack.pop())||[])if(!seen.has(w)){seen.add(w);stack.push(w);}}assert.equal(seen.size,adj.size,'single loop');}
test('catalog stays at 106 and Yajilin is solver-certified',()=>{assert.equal(ctx.SudokuBank.length,106);for(const seed of [3,17,41]){const g=ctx.SudokuGenerator.make(Y,seed,'focused');assert.equal(g.generation.unique,true);assert.equal(g.generation.verification,'solver-verified');assert.equal(count(g.puzzle,2),1);independentSolutionCheck(g);}});
test('Yajilin counter distinguishes zero, one and multiple solutions',()=>{assert.equal(count({size:1,clues:[]}),0);assert.equal(count({size:2,clues:[]}),1);assert.equal(count({size:3,clues:[]}),2);assert.equal(count({size:2,clues:[{r:0,c:0,dir:'right',clue:2}]}),0);});
test('10 focused seeds are unique and structurally diverse',()=>{const sig=new Set(),dirs=new Set();for(let seed=1;seed<=10;seed++){const g=ctx.SudokuGenerator.make(Y,seed,'focused');assert.equal(g.generation.unique,true,'seed '+seed);assert.equal(count(g.puzzle,2),1,'seed '+seed);sig.add(JSON.stringify(g.puzzle));g.puzzle.clues.forEach(x=>dirs.add(x.dir));}assert.equal(sig.size,10);assert.deepEqual([...dirs].sort(),['down','left','right','up']);});
test('difficulty uses measured solver search rather than clue count alone',()=>{const avg={};for(const d of ['gentle','focused','expert']){const scores=[];for(let seed=1;seed<=10;seed++){const g=ctx.SudokuGenerator.make(Y,seed,d);assert.equal(g.generation.unique,true,d+' '+seed);scores.push(g.generation.difficultyScore);}avg[d]=scores.reduce((a,b)=>a+b,0)/scores.length;}assert.ok(avg.focused>avg.gentle*3,{avg});assert.ok(avg.expert>avg.focused*1.5,{avg});});
test('Yajilin runtime is edge-based with explicit touch modes',()=>{const lib=fs.readFileSync(path.join(root,'games/sudoku-library.js'),'utf8'),css=fs.readFileSync(path.join(root,'assets/styles.css'),'utf8');assert.match(lib,/function mountYajilin/);assert.match(lib,/yajilin-edge/);assert.match(lib,/mode='loop'/);assert.match(lib,/mode='black'/);assert.match(lib,/current\.kind==='galaxies'\|\|current\.kind==='yajilin'/);assert.doesNotMatch(lib,/Jelöld a hurok celláit és a fekete mezőket/);assert.match(css,/\.yajilin-edge\.horizontal\{height:44px\}/);assert.match(css,/\.yajilin-edge\.vertical\{width:44px\}/);assert.match(css,/\.yajilin-cell\{min-width:44px;min-height:44px\}/);});
test('Yajilin independent rule audit covers every difficulty band',()=>{for(const d of ['gentle','focused','expert'])for(const seed of [1,3,7,17,41]){const g=ctx.SudokuGenerator.make(Y,seed,d);assert.equal(g.generation.unique,true,d+' '+seed);assert.equal(g.generation.verification,'solver-verified',d+' '+seed);assert.equal(g.generation.variantEssential,true,d+' '+seed);assert.equal(count(g.puzzle,2),1,d+' '+seed);independentSolutionCheck(g);}});
