'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
for(const f of ['sudoku-bank.js','sudoku-bank-iteration2.js','sudoku-bank-iteration3.js','sudoku-bank-iteration4.js','sudoku-bank-iteration5.js','sudoku-bank-iteration6.js','sudoku-bank-iteration7.js','sudoku-bank-iteration8.js','sudoku-bank-iteration9.js','sudoku-bank-iteration10.js','sudoku-generator.js','extra-house-generator-core.js','diagonal-generator-hardening.js','iteration4-generator-hardening.js','iteration5-generator-hardening.js','iteration6-generator-hardening.js','iteration7-generator-hardening.js','iteration8-generator-hardening.js','iteration9-generator-hardening.js','iteration10-generator-hardening.js'])require('../games/'+f);
const bank=global.SudokuBank,gen=global.SudokuGenerator,variant=id=>bank.find(v=>v.id===id);
function lineAt(g,axis,index){return axis==='row'?g[index]:g.map(row=>row[index]);}
function runningCount(line){const used=Array(line.length).fill(false);for(let i=0;i<line.length-1;i++)if(Math.abs(line[i]-line[i+1])===1)used[i]=used[i+1]=true;return used.filter(Boolean).length;}
function ascendingCount(line){let count=0,inRun=false;for(let i=0;i<line.length-1;i++){if(line[i]<line[i+1]){if(!inRun)count++;inRun=true;}else inRun=false;}return count;}

test('Running Cells and Ascending Sequences static solutions satisfy every outside clue',()=>{for(const id of ['running-cells','ascending-sequences']){const v=variant(id),measure=id==='running-cells'?runningCount:ascendingCount;assert.equal(v.data.clues.length,18);for(const cl of v.data.clues)assert.equal(measure(lineAt(v.solution,cl.axis,cl.index)),cl.count,id+' '+JSON.stringify(cl));}});

test('Running Cells and Ascending Sequences generation is deterministic, seed-diverse, unique and variant-essential',()=>{for(const id of ['running-cells','ascending-sequences']){const v=variant(id),seen=new Set();for(const seed of [1001,1002,1003,1004]){const a=gen.make(v,seed,'focused'),b=gen.make(v,seed,'focused');assert.deepEqual(a.puzzle,b.puzzle,id+' deterministic '+seed);assert.equal(a.generation.unique,true,id+' unique');assert.equal(a.generation.variantEssential,true,id+' essential');assert.equal(gen.countVariantSolutions(a.puzzle,v,2),1,id+' variant unique');assert.ok(gen.countSolutions(a.puzzle,2)>1,id+' classic ambiguous');seen.add(a.puzzle.flat().join(''));}assert.ok(seen.size>=3,id+' seed diversity');}});

test('Running Cells and Ascending Sequences difficulty is clue-ordered and carries measured variant search evidence',()=>{for(const id of ['running-cells','ascending-sequences']){const v=variant(id),outs=['gentle','focused','expert'].map(d=>gen.make(v,1010,d));assert.ok(outs[0].generation.clues>=outs[1].generation.clues,id+' gentle/focused clues');assert.ok(outs[1].generation.clues>=outs[2].generation.clues,id+' focused/expert clues');for(const out of outs){assert.ok(Number.isFinite(out.generation.difficultyScore)&&out.generation.difficultyScore>0,id+' measured difficulty');assert.ok(out.generation.searchStats&&Number.isFinite(out.generation.searchStats.nodes),id+' search stats');}}});

test('Running Cells and Ascending Sequences runtime enforcement, rotation and visuals are present',()=>{const source=fs.readFileSync(path.join(__dirname,'../games/sudoku-library.js'),'utf8'),css=fs.readFileSync(path.join(__dirname,'../assets/styles.css'),'utf8');for(const token of ["kindIs(v,'runningcells')","kindIs(v,'ascendingsequences')",'outsideCountConflict','runningCellCount','ascendingSequenceCount','rotateAxisIndex','count-clues'])assert.ok(source.includes(token),token);assert.match(css,/count-clues|sudoku-count-clue/,'outside clue styling');});
