'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');global.window=global;
for(const f of ['sudoku-bank.js','sudoku-bank-iteration2.js','sudoku-bank-iteration3.js','sudoku-bank-iteration4.js','sudoku-bank-iteration5.js','sudoku-bank-iteration6.js','sudoku-bank-iteration7.js','sudoku-bank-iteration8.js','sudoku-bank-iteration9.js','sudoku-bank-iteration10.js','sudoku-bank-iteration11.js','sudoku-bank-iteration12.js','sudoku-bank-iteration13.js','sudoku-bank-iteration14.js','sudoku-bank-iteration15.js','sudoku-bank-iteration16.js','sudoku-bank-iteration17.js','sudoku-bank-iteration18.js','sudoku-bank-iteration19.js','sudoku-bank-iteration20.js','sudoku-bank-iteration21.js','sudoku-bank-iteration22.js','sudoku-generator.js','extra-house-generator-core.js','diagonal-generator-hardening.js','iteration4-generator-hardening.js','iteration5-generator-hardening.js','iteration6-generator-hardening.js','iteration7-generator-hardening.js','iteration8-generator-hardening.js','iteration9-generator-hardening.js','iteration10-generator-hardening.js','iteration11-generator-hardening.js','iteration12-generator-hardening.js','iteration13-generator-hardening.js','iteration14-generator-hardening.js','iteration15-generator-hardening.js','iteration16-generator-hardening.js','iteration17-generator-hardening.js','iteration18-generator-hardening.js','iteration19-generator-hardening.js','iteration20-generator-hardening.js','iteration21-generator-hardening.js','iteration22-generator-hardening.js'])vm.runInThisContext(fs.readFileSync(path.join(root,'games',f),'utf8'));
const difficulties=['gentle','focused','expert'];
function variant(){return SudokuBank.find(v=>v.id==='toroidal-skyscrapers');}
function visible(a){let m=0,n=0;for(const x of a)if(x>m){m=x;n++;}return n;}
function givens(p){return p.flat().filter(Boolean).length;}

test('Iteration 22 static toroidal solution satisfies viewpoint, Latin and wrapped visibility rules',()=>{const v=variant(),d=v.data;assert.ok(v);assert.equal(v.solution.length,6);assert.equal(d.clueValue,6);assert.equal(d.maxDigit,5);assert.equal(d.toroidalClues.length,6);const clueSet=new Set(d.toroidalClues.map(cl=>cl.cell.join(',')));for(let i=0;i<6;i++){for(const seq of [v.solution[i],v.solution.map(r=>r[i])]){assert.equal(seq.filter(x=>x===6).length,1);for(let x=1;x<=5;x++)assert.equal(seq.filter(y=>y===x).length,1);}}for(const cl of d.toroidalClues){assert.equal(v.solution[cl.cell[0]][cl.cell[1]],6,'viewpoint value');assert.equal(cl.cells.length,5,'wrapped sightline length');assert.equal(new Set(cl.cells.map(p=>p.join(','))).size,5,'distinct wrapped cells');assert.ok(!cl.cells.some(p=>p[0]===cl.cell[0]&&p[1]===cl.cell[1]),'viewpoint excluded');assert.equal(visible(cl.cells.map(p=>v.solution[p[0]][p[1]])),cl.count,'wrapped visibility '+JSON.stringify(cl));}assert.equal(clueSet.size,6);});

test('Iteration 22 generation is deterministic, seed-diverse, unique and toroidal-clue-essential',()=>{const v=variant();for(const difficulty of difficulties){const a=SudokuGenerator.make(v,2222,difficulty),b=SudokuGenerator.make(v,2222,difficulty),c=SudokuGenerator.make(v,2026,difficulty);assert.deepEqual(a.puzzle,b.puzzle,'deterministic '+difficulty);assert.notDeepEqual(a.puzzle,c.puzzle,'seed-diverse '+difficulty);assert.equal(a.generation.unique,true,'unique '+difficulty);assert.equal(a.generation.variantEssential,true,'essential '+difficulty);assert.equal(SudokuGenerator.countToroidalSkyscraperSolutions(a.puzzle,a,2,false),1,'toroidal unique '+difficulty);assert.ok(SudokuGenerator.countToroidalSkyscraperSolutions(a.puzzle,a,2,true)>1,'Latin baseline ambiguous '+difficulty);for(const cl of a.data.toroidalClues)assert.equal(a.puzzle[cl.cell[0]][cl.cell[1]],a.data.clueValue,'viewpoint remains fixed');}});

test('Iteration 22 difficulty is clue-ordered and carries measured toroidal search evidence',()=>{const v=variant(),made=difficulties.map(d=>SudokuGenerator.make(v,2226,d));assert.ok(givens(made[0].puzzle)>=givens(made[1].puzzle),'gentle/focused clues');assert.ok(givens(made[1].puzzle)>=givens(made[2].puzzle),'focused/expert clues');for(const x of made){assert.ok(x.generation.searchStats,'search stats');for(const k of ['nodes','branches','deadEnds','solutions'])assert.equal(typeof x.generation.searchStats[k],'number',k);assert.equal(typeof x.generation.difficultyScore,'number','difficulty score');assert.ok(x.generation.difficultyScore>=0,'nonnegative score');}});

test('Iteration 22 runtime enforces wrapped sightlines and viewpoint rendering',()=>{const gen=fs.readFileSync(path.join(root,'games/sudoku-generator.js'),'utf8'),lib=fs.readFileSync(path.join(root,'games/sudoku-library.js'),'utf8'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');for(const t of ['countToroidalSkyscraperSolutions','makeToroidalSkyscraperPuzzle',"variant.kind==='toroidalskyscrapers'"])assert.ok(gen.includes(t),t);for(const t of ['function toroidalSkyscraperConflict',"v.kind==='toroidalskyscrapers'&&toroidalSkyscraperConflict",'toroidal-clue-cell','String(tc.count)+tc.arrow'])assert.ok(lib.includes(t),t);assert.ok(html.includes('sudoku-bank-iteration22.js'));});
