'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
for(const f of ['sudoku-bank.js','sudoku-bank-iteration2.js','sudoku-bank-iteration3.js','sudoku-bank-iteration4.js','sudoku-bank-iteration5.js','sudoku-bank-iteration6.js','sudoku-bank-iteration7.js','sudoku-bank-iteration8.js','sudoku-bank-iteration9.js','sudoku-bank-iteration10.js','sudoku-bank-iteration11.js','sudoku-bank-iteration12.js','sudoku-bank-iteration13.js','sudoku-generator.js','extra-house-generator-core.js','diagonal-generator-hardening.js','iteration4-generator-hardening.js','iteration5-generator-hardening.js','iteration6-generator-hardening.js','iteration7-generator-hardening.js','iteration8-generator-hardening.js','iteration9-generator-hardening.js','iteration10-generator-hardening.js','iteration11-generator-hardening.js','iteration12-generator-hardening.js','iteration13-generator-hardening.js'])require('../games/'+f);
const bank=global.SudokuBank,gen=global.SudokuGenerator,variant=id=>bank.find(v=>v.id===id);
function line(v,cl,g=v.solution){return cl.axis==='row'?g[cl.index].slice():g.map(r=>r[cl.index]);}
function evenSandwichDigits(a){const out=[];for(let i=1;i<a.length-1;i++)if(a[i-1]%2===0&&a[i+1]%2===0)out.push(a[i]);return out.sort((x,y)=>x-y);}

test('Even Sandwich and Top-Heavy Parity static solutions satisfy their full variant rules',()=>{const es=variant('even-sandwich');for(const cl of es.data.clues)assert.deepEqual(cl.digits,evenSandwichDigits(line(es,cl)),JSON.stringify(cl));const th=variant('top-heavy-parity');for(let r=0;r<8;r++)for(let c=0;c<9;c++){const a=th.solution[r][c],b=th.solution[r+1][c];if(a%2===b%2)assert.ok(a>b,'R'+(r+1)+'C'+(c+1));}});

test('Even Sandwich and Top-Heavy Parity generation is deterministic, seed-diverse, unique and variant-essential',()=>{for(const id of ['even-sandwich','top-heavy-parity']){const v=variant(id),seen=new Set();for(const seed of [1301,1302,1303,1304]){const a=gen.make(v,seed,'focused'),b=gen.make(v,seed,'focused');assert.deepEqual(a.puzzle,b.puzzle,id+' deterministic '+seed);assert.equal(a.generation.unique,true,id+' unique');assert.equal(a.generation.variantEssential,true,id+' essential');assert.equal(gen.countVariantSolutions(a.puzzle,a,2),1,id+' variant unique');assert.ok(gen.countSolutions(a.puzzle,2)>1,id+' classic ambiguous');seen.add(a.puzzle.flat().join(''));}assert.ok(seen.size>=3,id+' seed diversity');}});

test('Even Sandwich and Top-Heavy Parity difficulty is clue-ordered and carries measured variant search evidence',()=>{for(const id of ['even-sandwich','top-heavy-parity']){const v=variant(id),outs=['gentle','focused','expert'].map(d=>gen.make(v,1313,d));assert.ok(outs[0].generation.clues>=outs[1].generation.clues,id+' gentle/focused clues');assert.ok(outs[1].generation.clues>=outs[2].generation.clues,id+' focused/expert clues');for(const out of outs){assert.ok(Number.isFinite(out.generation.difficultyScore)&&out.generation.difficultyScore>0,id+' measured difficulty');assert.ok(out.generation.searchStats&&Number.isFinite(out.generation.searchStats.nodes),id+' search stats');}}});

test('Even Sandwich and Top-Heavy Parity runtime enforcement and visual hooks are present',()=>{const genSource=fs.readFileSync(path.join(__dirname,'../games/sudoku-generator.js'),'utf8'),lib=fs.readFileSync(path.join(__dirname,'../games/sudoku-library.js'),'utf8');for(const token of ['evenSandwichValid',"variant.kind==='topheavyparity'",'evensandwich:true','topheavyparity:true'])assert.ok(genSource.includes(token),token);for(const token of ["kindIs(v,'evensandwich')","kindIs(v,'topheavyparity')",'notes[r-1][c].delete','cl.digits.length'])assert.ok(lib.includes(token),token);});