'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');global.window=global;
for(const f of ['sudoku-bank.js','sudoku-bank-iteration2.js','sudoku-bank-iteration3.js','sudoku-bank-iteration4.js','sudoku-bank-iteration5.js','sudoku-bank-iteration6.js','sudoku-bank-iteration7.js','sudoku-bank-iteration8.js','sudoku-bank-iteration9.js','sudoku-bank-iteration10.js','sudoku-bank-iteration11.js','sudoku-bank-iteration12.js','sudoku-bank-iteration13.js','sudoku-bank-iteration14.js','sudoku-bank-iteration15.js','sudoku-generator.js','iteration15-generator-hardening.js'])vm.runInThisContext(fs.readFileSync(path.join(root,'games',f),'utf8'));
const ids=['skyscraper-parks','sum-skyscraper-parks'];
const difficulties=['gentle','focused','expert'];
function variant(id){return SudokuBank.find(v=>v.id===id);}
function line(v,cl){let a=v.solution? (cl.axis==='row'?v.solution[cl.index].slice():v.solution.map(r=>r[cl.index])):[];if(cl.side==='right'||cl.side==='bottom')a.reverse();return a;}
function visible(line,park,sum){let max=0,out=sum?0:0;for(const x of line){if(x===park)continue;if(x>max){max=x;out+=sum?x:1;}}return out;}
function givens(p){return p.flat().filter(Boolean).length;}

test('Iteration 15 static park solutions satisfy row-column and outside-clue contracts',()=>{for(const id of ids){const v=variant(id),park=v.data.parkValue;assert.equal(park,9,id+' park value');for(let i=0;i<9;i++){assert.deepEqual([...v.solution[i]].sort((a,b)=>a-b),[1,2,3,4,5,6,7,8,9],id+' row '+i);assert.deepEqual(v.solution.map(r=>r[i]).sort((a,b)=>a-b),[1,2,3,4,5,6,7,8,9],id+' col '+i);}for(const cl of v.data.clues){const actual=visible(line(v,cl),park,id==='sum-skyscraper-parks');assert.equal(actual,id==='sum-skyscraper-parks'?cl.sum:cl.count,id+' '+JSON.stringify(cl));}}});

test('Iteration 15 generation is deterministic, seed-diverse, unique and variant-essential',()=>{for(const id of ids){const v=variant(id);for(const difficulty of difficulties){const a=SudokuGenerator.make(v,1915,difficulty),b=SudokuGenerator.make(v,1915,difficulty),c=SudokuGenerator.make(v,2026,difficulty);assert.deepEqual(a.puzzle,b.puzzle,id+' deterministic '+difficulty);assert.notDeepEqual(a.puzzle,c.puzzle,id+' seed-diverse '+difficulty);assert.equal(a.generation.unique,true,id+' unique '+difficulty);assert.equal(a.generation.variantEssential,true,id+' essential '+difficulty);assert.equal(SudokuGenerator.countParkSolutions(a.puzzle,a,2,false),1,id+' solver unique '+difficulty);assert.ok(SudokuGenerator.countParkSolutions(a.puzzle,a,2,true)>1,id+' clues essential '+difficulty);}}});

test('Iteration 15 difficulty is clue-ordered and carries measured variant search evidence',()=>{for(const id of ids){const v=variant(id),made=difficulties.map(d=>SudokuGenerator.make(v,1519,d));assert.ok(givens(made[0].puzzle)>=givens(made[1].puzzle),id+' gentle/focused clues');assert.ok(givens(made[1].puzzle)>=givens(made[2].puzzle),id+' focused/expert clues');for(const x of made){assert.ok(x.generation.searchStats,id+' search stats');for(const k of ['nodes','branches','deadEnds','solutions'])assert.equal(typeof x.generation.searchStats[k],'number',id+' '+k);assert.equal(typeof x.generation.difficultyScore,'number',id+' difficulty score');assert.ok(x.generation.difficultyScore>=0,id+' nonnegative score');}}});

test('Iteration 15 runtime enforcement and park visual/input hooks are present',()=>{const lib=fs.readFileSync(path.join(root,'games/sudoku-library.js'),'utf8');for(const token of ['function parkConflict','parkVisibleCount(line,park)','parkVisibleSum(line,park)',"kindIs(v,'skyscraperparks')","kindIs(v,'sumskyscraperparks')","return '🌿'","e.key==='p'||e.key==='P'"])assert.ok(lib.includes(token),token);});
