const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.join(__dirname,'..'),ctx={console,Map,Set,Math,JSON,Array,Object,Number,String,Boolean,Date,Uint8Array};ctx.globalThis=ctx;vm.createContext(ctx);
for(const f of fs.readdirSync(path.join(root,'games')).filter(x=>/^sudoku-bank(?:-iteration\d+)?\.js$/.test(x)).sort((a,b)=>{const n=x=>+(x.match(/iteration(\d+)/)||[,0])[1];return n(a)-n(b)}).concat(['sudoku-generator.js']))vm.runInContext(fs.readFileSync(path.join(root,'games',f),'utf8'),ctx,{filename:f});
const S=ctx.SudokuBank.find(x=>x.id==='shakashaka'),count=(p,l=2,s={})=>ctx.SudokuGenerator.countShakashakaSolutions(p,l,s);
function independentCheck(g){const n=g.puzzle.size,block=new Map(g.puzzle.blocks.map(x=>[x.r+','+x.c,x]));for(const b of g.puzzle.blocks)if(b.clue!=null){let k=0;for(const [dr,dc] of [[1,0],[-1,0],[0,1],[0,-1]]){const r=b.r+dr,c=b.c+dc;if(r>=0&&c>=0&&r<n&&c<n&&!block.has(r+','+c)&&g.solution[r][c]>0)k++;}assert.equal(k,b.clue,'clue '+b.r+','+b.c);}for(let r=0;r<n;r++)for(let c=0;c<n;c++){const st=g.solution[r][c];if(block.has(r+','+c))continue;assert.ok(st>=0&&st<=4);}}
test('counter distinguishes known zero, one and multiple mini-puzzles',()=>{assert.equal(count({size:1,blocks:[]}),1);assert.equal(count({size:2,blocks:[]}),2);assert.equal(count({size:2,blocks:[{r:0,c:0,clue:4}]}),0);});
test('10 focused seeds are solver-certified and clue-valid',()=>{const puzzles=new Set(),solutions=new Set();for(let seed=1;seed<=10;seed++){const g=ctx.SudokuGenerator.make(S,seed,'focused');assert.equal(g.generation.unique,true,'seed '+seed);assert.equal(g.generation.verification,'solver-verified');assert.equal(count(g.puzzle,2),1,'seed '+seed);independentCheck(g);puzzles.add(JSON.stringify(g.puzzle));solutions.add(JSON.stringify(g.solution));}assert.equal(puzzles.size,10);assert.ok(solutions.size>=7,solutions.size);});
test('difficulty uses measured search complexity',()=>{const avg={};for(const d of ['gentle','focused','expert']){const xs=[];for(let seed=1;seed<=10;seed++)xs.push(ctx.SudokuGenerator.make(S,seed,d).generation.difficultyScore);avg[d]=xs.reduce((a,b)=>a+b,0)/xs.length;}assert.ok(avg.focused>avg.gentle,{avg});assert.ok(avg.expert>avg.focused*1.1,{avg});});
test('runtime draws real triangle overlays without clipping the cell touch target',()=>{const lib=fs.readFileSync(path.join(root,'games/sudoku-library.js'),'utf8'),css=fs.readFileSync(path.join(root,'assets/styles.css'),'utf8');assert.match(lib,/function mountShakashaka/);assert.match(lib,/shaka-tri-/);assert.match(lib,/téglalapnak vagy négyzetnek/);assert.match(css,/\.shakashaka-cell\{position:relative;min-width:44px;min-height:44px/);assert.match(css,/\.shakashaka-cell\.shaka-tri-1::after/);assert.doesNotMatch(css,/iteration51-cell\.tri-1\{clip-path/);});
test('catalog remains 106',()=>assert.equal(ctx.SudokuBank.length,106));
