'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
for(const f of ['sudoku-bank.js','sudoku-bank-iteration2.js','sudoku-bank-iteration3.js','sudoku-bank-iteration4.js','sudoku-bank-iteration5.js','sudoku-bank-iteration6.js','sudoku-bank-iteration7.js','sudoku-bank-iteration8.js','sudoku-bank-iteration9.js','sudoku-bank-iteration10.js','sudoku-bank-iteration11.js','sudoku-generator.js','extra-house-generator-core.js','diagonal-generator-hardening.js','iteration4-generator-hardening.js','iteration5-generator-hardening.js','iteration6-generator-hardening.js','iteration7-generator-hardening.js','iteration8-generator-hardening.js','iteration9-generator-hardening.js','iteration10-generator-hardening.js','iteration11-generator-hardening.js'])require('../games/'+f);
const bank=global.SudokuBank,gen=global.SudokuGenerator,variant=id=>bank.find(v=>v.id===id);
function bishopValid(v,g){const p=v.data.parity;for(let r=0;r<9;r++)for(let c=0;c<9;c++)if(((r+c)&1)===p){const d=g[r][c];for(const [dr,dc] of [[1,1],[1,-1]])for(let k=1;;k++){const rr=r+dr*k,cc=c+dc*k;if(rr<0||rr>=9||cc<0||cc>=9)break;assert.notEqual(g[rr][cc],d,'bishop '+r+','+c);}}}
function minmaxValid(v,g){for(const ex of v.data.extrema){const [r,c]=ex.cell,n=[];for(const [dr,dc] of [[1,0],[-1,0],[0,1],[0,-1]]){const rr=r+dr,cc=c+dc;if(rr>=0&&rr<9&&cc>=0&&cc<9)n.push(g[rr][cc]);}assert.ok(n.every(x=>ex.type==='min'?g[r][c]<x:g[r][c]>x),JSON.stringify(ex));}}

test('Bishopsgate and Min/Max static solutions satisfy their full variant rules',()=>{bishopValid(variant('bishopsgate'),variant('bishopsgate').solution);minmaxValid(variant('minmax'),variant('minmax').solution);});

test('Bishopsgate and Min/Max generation is deterministic, seed-diverse, unique and variant-essential',()=>{for(const id of ['bishopsgate','minmax']){const v=variant(id),seen=new Set();for(const seed of [1101,1102,1103,1104]){const a=gen.make(v,seed,'focused'),b=gen.make(v,seed,'focused');assert.deepEqual(a.puzzle,b.puzzle,id+' deterministic '+seed);assert.equal(a.generation.unique,true,id+' unique');assert.equal(a.generation.variantEssential,true,id+' essential');assert.equal(gen.countVariantSolutions(a.puzzle,a,2),1,id+' variant unique');assert.ok(gen.countSolutions(a.puzzle,2)>1,id+' classic ambiguous');seen.add(a.puzzle.flat().join(''));}assert.ok(seen.size>=3,id+' seed diversity');}});

test('Bishopsgate and Min/Max difficulty is clue-ordered and carries measured variant search evidence',()=>{for(const id of ['bishopsgate','minmax']){const v=variant(id),outs=['gentle','focused','expert'].map(d=>gen.make(v,1111,d));assert.ok(outs[0].generation.clues>=outs[1].generation.clues,id+' gentle/focused clues');assert.ok(outs[1].generation.clues>=outs[2].generation.clues,id+' focused/expert clues');for(const out of outs){assert.ok(Number.isFinite(out.generation.difficultyScore)&&out.generation.difficultyScore>0,id+' measured difficulty');assert.ok(out.generation.searchStats&&Number.isFinite(out.generation.searchStats.nodes),id+' search stats');}}});

test('Bishopsgate and Min/Max runtime enforcement and visual hooks are present',()=>{const source=fs.readFileSync(path.join(__dirname,'../games/sudoku-library.js'),'utf8'),css=fs.readFileSync(path.join(__dirname,'../assets/styles.css'),'utf8');for(const token of ["kindIs(v,'bishopsgate')","kindIs(v,'minmax')",'bishopsgate-cell','sudoku-minmax-marker','d.extrema'])assert.ok(source.includes(token),token);assert.match(css,/bishopsgate-cell|sudoku-minmax-marker/,'variant styling');});