'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
for(const f of ['sudoku-bank.js','sudoku-bank-iteration2.js','sudoku-bank-iteration3.js','sudoku-bank-iteration4.js','sudoku-bank-iteration5.js','sudoku-bank-iteration6.js','sudoku-bank-iteration7.js','sudoku-bank-iteration8.js','sudoku-bank-iteration9.js','sudoku-bank-iteration10.js','sudoku-bank-iteration11.js','sudoku-bank-iteration12.js','sudoku-bank-iteration13.js','sudoku-bank-iteration14.js','sudoku-generator.js','extra-house-generator-core.js','diagonal-generator-hardening.js','iteration4-generator-hardening.js','iteration5-generator-hardening.js','iteration6-generator-hardening.js','iteration7-generator-hardening.js','iteration8-generator-hardening.js','iteration9-generator-hardening.js','iteration10-generator-hardening.js','iteration11-generator-hardening.js','iteration12-generator-hardening.js','iteration13-generator-hardening.js','iteration14-generator-hardening.js'])require('../games/'+f);
const bank=global.SudokuBank,gen=global.SudokuGenerator,variant=id=>bank.find(v=>v.id===id);
function line(v,cl,g=v.solution){let a=cl.axis==='row'?g[cl.index].slice():g.map(r=>r[cl.index]);if(cl.side==='right'||cl.side==='bottom')a.reverse();return a;}
function visibleCount(a){let m=0,n=0;for(const x of a)if(x>m){m=x;n++;}return n;}
function visibleSum(a){let m=0,n=0;for(const x of a)if(x>m){m=x;n+=x;}return n;}

test('Iteration 14 static solutions satisfy their full skyscraper variant rules',()=>{const ss=variant('skyscraper-sums');for(const cl of ss.data.clues)assert.equal(cl.sum,visibleSum(line(ss,cl)),JSON.stringify(cl));const sm=variant('skyscraper-mixed');for(const cl of sm.data.clues){const a=line(sm,cl);assert.ok(cl.value===visibleCount(a)||cl.value===a[0],JSON.stringify(cl));}const sn=variant('skyscraper-nontouching');for(const cl of sn.data.clues)assert.equal(cl.count,visibleCount(line(sn,cl)),JSON.stringify(cl));for(let r=0;r<8;r++)for(let c=0;c<8;c++){assert.notEqual(sn.solution[r][c],sn.solution[r+1][c+1]);assert.notEqual(sn.solution[r+1][c],sn.solution[r][c+1]);}});

test('Iteration 14 generation is deterministic, seed-diverse, unique and variant-essential',()=>{for(const id of ['skyscraper-sums','skyscraper-mixed','skyscraper-nontouching']){const v=variant(id),seen=new Set();for(const seed of [1401,1402,1403,1404]){const a=gen.make(v,seed,'focused'),b=gen.make(v,seed,'focused');assert.deepEqual(a.puzzle,b.puzzle,id+' deterministic '+seed);assert.equal(a.generation.unique,true,id+' unique');assert.equal(a.generation.variantEssential,true,id+' essential');assert.equal(gen.countVariantSolutions(a.puzzle,a,2),1,id+' variant unique');assert.ok(gen.countSolutions(a.puzzle,2)>1,id+' classic ambiguous');seen.add(a.puzzle.flat().join(''));}assert.ok(seen.size>=3,id+' seed diversity');}});

test('Iteration 14 difficulty is clue-ordered and carries measured variant search evidence',()=>{for(const id of ['skyscraper-sums','skyscraper-mixed','skyscraper-nontouching']){const v=variant(id),outs=['gentle','focused','expert'].map(d=>gen.make(v,1414,d));assert.ok(outs[0].generation.clues>=outs[1].generation.clues,id+' gentle/focused clues');assert.ok(outs[1].generation.clues>=outs[2].generation.clues,id+' focused/expert clues');for(const out of outs){assert.ok(Number.isFinite(out.generation.difficultyScore)&&out.generation.difficultyScore>0,id+' measured difficulty');assert.ok(out.generation.searchStats&&Number.isFinite(out.generation.searchStats.nodes),id+' search stats');}}});

test('Iteration 14 runtime enforcement and visual hooks are present',()=>{const genSource=fs.readFileSync(path.join(__dirname,'../games/sudoku-generator.js'),'utf8'),lib=fs.readFileSync(path.join(__dirname,'../games/sudoku-library.js'),'utf8');for(const token of ['skyscraperVisibleSum','skyscraperFamilyValid','skyscrapersums:true','skyscrapermixed:true','skyscrapernontouching:true'])assert.ok(genSource.includes(token),token);for(const token of ["kindIs(v,'skyscrapersums')","kindIs(v,'skyscrapermixed')","kindIs(v,'skyscrapernontouching')",'notes[nr][nc].delete'])assert.ok(lib.includes(token),token);});
