const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.join(__dirname,'..'),ctx={console,Map,Set,Math,JSON,Array,Object,Number,String,Boolean,Date,Uint8Array};ctx.globalThis=ctx;vm.createContext(ctx);
for(const f of fs.readdirSync(path.join(root,'games')).filter(x=>/^sudoku-bank(?:-iteration\d+)?\.js$/.test(x)).sort((a,b)=>{const n=x=>+(x.match(/iteration(\d+)/)||[,0])[1];return n(a)-n(b)}).concat(['sudoku-generator.js']))vm.runInContext(fs.readFileSync(path.join(root,'games',f),'utf8'),ctx,{filename:f});
const R=ctx.SudokuBank.find(x=>x.id==='ripple-effect'),count=(p,l=2,s={})=>ctx.SudokuGenerator.countRippleEffectSolutions(p,l,s);
function validate(g){const n=g.puzzle.size,rooms=g.puzzle.rooms,sol=g.solution,by={};for(let r=0;r<n;r++)for(let c=0;c<n;c++){const id=rooms[r][c];(by[id]||(by[id]=[])).push(sol[r][c]);}for(const vals of Object.values(by)){const want=Array.from({length:vals.length},(_,i)=>i+1).sort((a,b)=>a-b);assert.deepEqual(vals.slice().sort((a,b)=>a-b),want);}for(let r=0;r<n;r++)for(let c=0;c<n;c++){const k=sol[r][c];for(let d=1;d<=k;d++){if(r+d<n)assert.notEqual(sol[r+d][c],k);if(c+d<n)assert.notEqual(sol[r][c+d],k);}}}
test('Ripple counter handles zero, one and multiple solutions from visible constraints',()=>{const rooms=[[0,0],[1,1]],empty=[[0,0],[0,0]];assert.equal(count({size:2,rooms,givens:empty}),2);assert.equal(count({size:2,rooms,givens:[[1,0],[0,0]]}),1);assert.equal(count({size:2,rooms,givens:[[1,1],[0,0]]}),0);assert.equal(count({size:1,rooms:[[0]],givens:[[0]]}),1);});
test('10 focused seeds are solver-certified, valid and room-diverse',()=>{const sig=new Set(),sizes=new Set();for(let seed=1;seed<=10;seed++){const g=ctx.SudokuGenerator.make(R,seed,'focused');assert.equal(g.generation.unique,true);assert.equal(g.generation.verification,'solver-verified');assert.equal(count(g.puzzle,2),1);validate(g);sig.add(JSON.stringify(g.puzzle.rooms));const d={};g.puzzle.rooms.flat().forEach(x=>d[x]=(d[x]||0)+1);Object.values(d).forEach(x=>sizes.add(x));}assert.equal(sig.size,10);assert.ok(sizes.has(2)&&sizes.has(3)&&sizes.has(4),[...sizes]);});
test('difficulty follows measured search complexity',()=>{const avg={};for(const d of ['gentle','focused','expert']){const xs=[];for(let seed=1;seed<=10;seed++){const g=ctx.SudokuGenerator.make(R,seed,d);assert.equal(g.generation.unique,true);xs.push(g.generation.difficultyScore);}avg[d]=xs.reduce((a,b)=>a+b,0)/xs.length;}assert.ok(avg.focused>avg.gentle*1.5,{avg});assert.ok(avg.expert>avg.focused*2,{avg});});
test('runtime renders true room borders and room-sized input with mobile targets',()=>{const lib=fs.readFileSync(path.join(root,'games/sudoku-library.js'),'utf8'),css=fs.readFileSync(path.join(root,'assets/styles.css'),'utf8');assert.match(lib,/function roomBorder/);assert.match(lib,/roomSizes\[rooms\[rr\]\[cc\]\]/);assert.match(lib,/borderTopWidth='3px'/);assert.match(lib,/A vastag vonalak a szobákat jelölik/);assert.match(css,/\.rippleeffect-board \.iteration51-cell\{min-width:44px;min-height:44px/);});
