'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');global.window=global;
for(const f of ['sudoku-bank.js','sudoku-bank-iteration2.js','sudoku-bank-iteration3.js','sudoku-bank-iteration4.js','sudoku-bank-iteration5.js','sudoku-bank-iteration6.js','sudoku-bank-iteration7.js','sudoku-bank-iteration8.js','sudoku-bank-iteration9.js','sudoku-bank-iteration10.js','sudoku-bank-iteration11.js','sudoku-bank-iteration12.js','sudoku-bank-iteration13.js','sudoku-bank-iteration14.js','sudoku-bank-iteration15.js','sudoku-bank-iteration16.js','sudoku-bank-iteration17.js','sudoku-bank-iteration18.js','sudoku-bank-iteration19.js','sudoku-generator.js','extra-house-generator-core.js','diagonal-generator-hardening.js','iteration4-generator-hardening.js','iteration5-generator-hardening.js','iteration6-generator-hardening.js','iteration7-generator-hardening.js','iteration8-generator-hardening.js','iteration9-generator-hardening.js','iteration10-generator-hardening.js','iteration11-generator-hardening.js','iteration12-generator-hardening.js','iteration13-generator-hardening.js','iteration14-generator-hardening.js','iteration15-generator-hardening.js','iteration16-generator-hardening.js','iteration17-generator-hardening.js','iteration18-generator-hardening.js','iteration19-generator-hardening.js'])vm.runInThisContext(fs.readFileSync(path.join(root,'games',f),'utf8'));
const difficulties=['gentle','focused','expert'];
function variant(){return SudokuBank.find(v=>v.id==='skyscraper-parks2');}
function line(v,cl){let a=cl.axis==='row'?v.solution[cl.index].slice():v.solution.map(r=>r[cl.index]);if(cl.side==='right'||cl.side==='bottom')a.reverse();return a;}
function visibleCount(a,park){let m=0,n=0;for(const x of a){if(x===park)continue;if(x>m){m=x;n++;}}return n;}
function givens(p){return p.flat().filter(Boolean).length;}

test('Iteration 19 static solution satisfies two-parks Latin and visibility rules',()=>{const v=variant(),park=v.data.parkValue;assert.equal(v.solution.length,8);for(let i=0;i<8;i++){for(const seq of [v.solution[i],v.solution.map(r=>r[i])]){assert.equal(seq.filter(x=>x===park).length,2);for(let d=1;d<=6;d++)assert.equal(seq.filter(x=>x===d).length,1);}}for(const cl of v.data.clues)assert.equal(visibleCount(line(v,cl),park),cl.count,JSON.stringify(cl));});

test('Iteration 19 generation is deterministic, seed-diverse, unique and variant-essential',()=>{const v=variant();for(const difficulty of difficulties){const a=SudokuGenerator.make(v,1919,difficulty),b=SudokuGenerator.make(v,1919,difficulty),c=SudokuGenerator.make(v,2026,difficulty);assert.deepEqual(a.puzzle,b.puzzle,'deterministic '+difficulty);assert.notDeepEqual(a.puzzle,c.puzzle,'seed-diverse '+difficulty);assert.equal(a.generation.unique,true,'unique '+difficulty);assert.equal(a.generation.variantEssential,true,'essential '+difficulty);assert.equal(SudokuGenerator.countParks2Solutions(a.puzzle,a,2,false),1,'solver unique '+difficulty);assert.ok(SudokuGenerator.countParks2Solutions(a.puzzle,a,2,true)>1,'outside clues essential '+difficulty);}});

test('Iteration 19 difficulty is clue-ordered and carries measured variant search evidence',()=>{const v=variant(),made=difficulties.map(d=>SudokuGenerator.make(v,1923,d));assert.ok(givens(made[0].puzzle)>=givens(made[1].puzzle),'gentle/focused clues');assert.ok(givens(made[1].puzzle)>=givens(made[2].puzzle),'focused/expert clues');for(const x of made){assert.ok(x.generation.searchStats,'search stats');for(const k of ['nodes','branches','deadEnds','solutions'])assert.equal(typeof x.generation.searchStats[k],'number',k);assert.equal(typeof x.generation.difficultyScore,'number','difficulty score');assert.ok(x.generation.difficultyScore>=0,'nonnegative score');}});

test('Iteration 19 runtime enforcement and special 8x8 park hooks are present',()=>{const gen=fs.readFileSync(path.join(root,'games/sudoku-generator.js'),'utf8'),lib=fs.readFileSync(path.join(root,'games/sudoku-library.js'),'utf8');for(const t of ['countParks2Solutions','makeParks2Puzzle',"variant.kind==='skyscraperparks2'"])assert.ok(gen.includes(t),t);for(const t of ["kindIs(vdef,'skyscraperparks2')",'parksPerLine','inputMax',"kindIs(v,'skyscraperparks2')&&v.data&&val===v.data.parkValue"])assert.ok(lib.includes(t),t);});
