'use strict';
const test=require('node:test'),fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const root=path.resolve(__dirname,'..'),ctx={console};ctx.globalThis=ctx;ctx.window=ctx;vm.createContext(ctx);
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
for(const f of [...html.matchAll(/<script src="([^"]+)"/g)].map(m=>m[1]).filter(x=>x.startsWith('games/sudoku-bank')))vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),ctx);
vm.runInContext(fs.readFileSync(path.join(root,'games/sudoku-generator.js'),'utf8'),ctx);
const variant=id=>{const v=ctx.SudokuBank.find(x=>x.id===id);assert.ok(v,id);return v;};
const seeds=[1,2,3,4,5,6,7,8,13,21],diffs=['gentle','focused','expert'];
function fullFillominoValid(grid){const n=grid.length,seen=new Set();for(let r=0;r<n;r++)for(let c=0;c<n;c++){const k=r+','+c;if(seen.has(k))continue;const value=grid[r][c],q=[[r,c]],cells=[];seen.add(k);while(q.length){const [rr,cc]=q.pop();cells.push([rr,cc]);for(const [dr,dc] of [[1,0],[-1,0],[0,1],[0,-1]]){const r2=rr+dr,c2=cc+dc,key=r2+','+c2;if(r2>=0&&c2>=0&&r2<n&&c2<n&&!seen.has(key)&&grid[r2][c2]===value){seen.add(key);q.push([r2,c2]);}}}if(cells.length!==value)return false;}return true;}

test('Iteration 42 Akari uses procedural wall layouts with strong seed diversity and uniqueness',()=>{const v=variant('akari');for(const d of diffs){const solutions=new Set(),puzzles=new Set();for(const seed of seeds){const g=ctx.SudokuGenerator.make(v,seed,d);assert.equal(g.generation.generatorFamily,'procedural-wall-layout');assert.equal(ctx.SudokuGenerator.countAkariSolutions(g.puzzle,2),1);solutions.add(JSON.stringify(g.solution));puzzles.add(JSON.stringify(g.puzzle));}assert.equal(solutions.size,10,d);assert.equal(puzzles.size,10,d);}});

test('Iteration 42 Fillomino procedurally partitions connected regions and remains unique',()=>{const v=variant('fillomino');for(const d of diffs){const solutions=new Set();for(const seed of seeds){const g=ctx.SudokuGenerator.make(v,seed,d);assert.equal(g.generation.generatorFamily,'procedural-region-partition');assert.ok(fullFillominoValid(g.solution));assert.equal(ctx.SudokuGenerator.countFillominoSolutions(g.puzzle,2),1);solutions.add(JSON.stringify(g.solution));}assert.ok(solutions.size>=9,d+' diversity '+solutions.size);}});

test('Iteration 42 large Sudoku removes substantially more clues while proving uniqueness',()=>{for(const id of ['sudoku-12x12','sudoku-16x16']){const v=variant(id),n=v.solution.length,counts={};for(const d of diffs){const sols=new Set();for(const seed of seeds.slice(0,4)){const g=ctx.SudokuGenerator.make(v,seed,d);assert.equal(g.generation.generatorFamily,'large-unique-removal');assert.equal(ctx.SudokuGenerator.countSolutions(g.puzzle,2),1);sols.add(JSON.stringify(g.solution));counts[d]=g.generation.clues;}assert.equal(sols.size,4);}assert.ok(counts.gentle>counts.focused&&counts.focused>counts.expert,id);assert.ok(n*n-counts.expert>=Math.round(n*4),id+' expert holes');}});

test('Akari UI communicates bulb conflicts and numbered-wall states without color alone',()=>{const lib=fs.readFileSync(path.join(root,'games/sudoku-library.js'),'utf8'),css=fs.readFileSync(path.join(root,'assets/styles.css'),'utf8');for(const token of ['bulbConflict','wallState','wall-satisfied','wall-conflict','aria-invalid','conflicting bulb','ütköző lámpa'])assert.ok(lib.includes(token),token);for(const token of ['.akari-cell.wall.wall-satisfied','.akari-cell.wall.wall-conflict','.akari-cell.bulb.conflict'])assert.ok(css.includes(token),token);});

test('all 16 Skyscraper systems remain catalogued while generator-depth limitation is explicitly documented',()=>{const ids=['classic-skyscrapers','skyscraper','skyscraper-sums','skyscraper-mixed','skyscraper-nontouching','skyscraper-parks','sum-skyscraper-parks','inside-skyscrapers','diagonal-skyscrapers','product-skyscrapers','killer-skyscrapers','domino-skyscrapers','skyscraper-parks2','evenodd-skyscrapers','toroidal-skyscrapers','double-skyscrapers'];assert.equal(ids.filter(id=>ctx.SudokuBank.some(v=>v.id===id)).length,16);const limits=fs.readFileSync(path.join(root,'docs/limitations.md'),'utf8');assert.match(limits,/Lakótelep.*solution.*seed/i);});
