'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');global.window=global;
for(const f of ['sudoku-bank.js','sudoku-bank-iteration2.js','sudoku-bank-iteration3.js','sudoku-bank-iteration4.js','sudoku-bank-iteration5.js','sudoku-bank-iteration6.js','sudoku-bank-iteration7.js','sudoku-bank-iteration8.js','sudoku-bank-iteration9.js','sudoku-bank-iteration10.js','sudoku-bank-iteration11.js','sudoku-bank-iteration12.js','sudoku-bank-iteration13.js','sudoku-bank-iteration14.js','sudoku-bank-iteration15.js','sudoku-bank-iteration16.js','sudoku-bank-iteration17.js','sudoku-generator.js','extra-house-generator-core.js','diagonal-generator-hardening.js','iteration4-generator-hardening.js','iteration5-generator-hardening.js','iteration6-generator-hardening.js','iteration7-generator-hardening.js','iteration8-generator-hardening.js','iteration9-generator-hardening.js','iteration10-generator-hardening.js','iteration11-generator-hardening.js','iteration12-generator-hardening.js','iteration13-generator-hardening.js','iteration14-generator-hardening.js','iteration15-generator-hardening.js','iteration16-generator-hardening.js','iteration17-generator-hardening.js'])vm.runInThisContext(fs.readFileSync(path.join(root,'games',f),'utf8'));
const ids=['product-skyscrapers','killer-skyscrapers'],difficulties=['gentle','focused','expert'];
function variant(id){return SudokuBank.find(v=>v.id===id);}
function line(v,cl){let a=cl.axis==='row'?v.solution[cl.index].slice():v.solution.map(r=>r[cl.index]);if(cl.side==='right'||cl.side==='bottom')a.reverse();return a;}
function visibleCount(a){let m=0,n=0;for(const x of a)if(x>m){m=x;n++;}return n;}
function visibleProduct(a){let m=0,p=1;for(const x of a)if(x>m){m=x;p*=x;}return p;}
function givens(p){return p.flat().filter(Boolean).length;}

test('Iteration 17 static solutions satisfy product and killer-skyscraper rules',()=>{const p=variant('product-skyscrapers');for(const cl of p.data.clues)assert.equal(cl.product,visibleProduct(line(p,cl)),JSON.stringify(cl));const k=variant('killer-skyscrapers');for(const cl of k.data.clues)assert.equal(cl.count,visibleCount(line(k,cl)),JSON.stringify(cl));for(const cage of k.data.cages){const vals=cage.cells.map(x=>k.solution[x[0]][x[1]]);assert.equal(new Set(vals).size,vals.length,JSON.stringify(cage));assert.equal(vals.reduce((a,b)=>a+b,0),cage.sum,JSON.stringify(cage));}});

test('Iteration 17 generation is deterministic, seed-diverse, unique and variant-essential',()=>{for(const id of ids){const v=variant(id);for(const difficulty of difficulties){const a=SudokuGenerator.make(v,1717,difficulty),b=SudokuGenerator.make(v,1717,difficulty),c=SudokuGenerator.make(v,2026,difficulty);assert.deepEqual(a.puzzle,b.puzzle,id+' deterministic '+difficulty);assert.notDeepEqual(a.puzzle,c.puzzle,id+' seed-diverse '+difficulty);assert.equal(a.generation.unique,true,id+' unique '+difficulty);assert.equal(a.generation.variantEssential,true,id+' essential '+difficulty);assert.equal(SudokuGenerator.countVariantSolutions(a.puzzle,a,2),1,id+' solver unique '+difficulty);assert.ok(SudokuGenerator.countSolutions(a.puzzle,2)>1,id+' classic ambiguous '+difficulty);}}});

test('Iteration 17 difficulty is clue-ordered and carries measured variant search evidence',()=>{for(const id of ids){const v=variant(id),made=difficulties.map(d=>SudokuGenerator.make(v,1721,d));assert.ok(givens(made[0].puzzle)>=givens(made[1].puzzle),id+' gentle/focused clues');assert.ok(givens(made[1].puzzle)>=givens(made[2].puzzle),id+' focused/expert clues');for(const x of made){assert.ok(x.generation.searchStats,id+' search stats');for(const k of ['nodes','branches','deadEnds','solutions'])assert.equal(typeof x.generation.searchStats[k],'number',id+' '+k);assert.equal(typeof x.generation.difficultyScore,'number',id+' difficulty score');assert.ok(x.generation.difficultyScore>=0,id+' nonnegative score');}}});

test('Iteration 17 runtime enforcement and visual hooks are present',()=>{const gen=fs.readFileSync(path.join(root,'games/sudoku-generator.js'),'utf8'),lib=fs.readFileSync(path.join(root,'games/sudoku-library.js'),'utf8');for(const t of ['skyscraperVisibleProduct','killerCagesValid','skyscraperproduct:true','killerskyscrapers:true'])assert.ok(gen.includes(t),t);for(const t of ["kindIs(v,'skyscraperproduct')","kindIs(v,'killerskyscrapers')",'skyscraperFamilyConflict','littleKillerConflict'])assert.ok(lib.includes(t),t);});
