'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
for(const f of ['sudoku-bank.js','sudoku-bank-iteration2.js','sudoku-bank-iteration3.js','sudoku-bank-iteration4.js','sudoku-bank-iteration5.js','sudoku-bank-iteration6.js','sudoku-bank-iteration7.js','sudoku-bank-iteration8.js','sudoku-bank-iteration9.js','sudoku-bank-iteration10.js','sudoku-bank-iteration11.js','sudoku-bank-iteration12.js','sudoku-generator.js','extra-house-generator-core.js','diagonal-generator-hardening.js','iteration4-generator-hardening.js','iteration5-generator-hardening.js','iteration6-generator-hardening.js','iteration7-generator-hardening.js','iteration8-generator-hardening.js','iteration9-generator-hardening.js','iteration10-generator-hardening.js','iteration11-generator-hardening.js','iteration12-generator-hardening.js'])require('../games/'+f);
const bank=global.SudokuBank,gen=global.SudokuGenerator,variant=id=>bank.find(v=>v.id===id);
function line(v,cl,g=v.solution){let a=cl.axis==='row'?g[cl.index].slice():g.map(r=>r[cl.index]);if(cl.side==='right'||cl.side==='bottom')a.reverse();return a;}

test('Numbered Rooms and Next to Nine static solutions satisfy every outside clue',()=>{const nr=variant('numbered-rooms');for(const cl of nr.data.clues){const a=line(nr,cl),n=a[0];assert.equal(a[n-1],cl.digit,JSON.stringify(cl));}const nn=variant('next-to-nine');for(const cl of nn.data.clues){const a=line(nn,cl),p=a.indexOf(9),want=[];if(p>0)want.push(a[p-1]);if(p<8)want.push(a[p+1]);want.sort((x,y)=>x-y);assert.deepEqual(cl.digits,want,JSON.stringify(cl));}});

test('Numbered Rooms and Next to Nine generation is deterministic, seed-diverse, unique and variant-essential',()=>{for(const id of ['numbered-rooms','next-to-nine']){const v=variant(id),seen=new Set();for(const seed of [1201,1202,1203,1204]){const a=gen.make(v,seed,'focused'),b=gen.make(v,seed,'focused');assert.deepEqual(a.puzzle,b.puzzle,id+' deterministic '+seed);assert.equal(a.generation.unique,true,id+' unique');assert.equal(a.generation.variantEssential,true,id+' essential');assert.equal(gen.countVariantSolutions(a.puzzle,a,2),1,id+' variant unique');assert.ok(gen.countSolutions(a.puzzle,2)>1,id+' classic ambiguous');seen.add(a.puzzle.flat().join(''));}assert.ok(seen.size>=3,id+' seed diversity');}});

test('Numbered Rooms and Next to Nine difficulty is clue-ordered and carries measured variant search evidence',()=>{for(const id of ['numbered-rooms','next-to-nine']){const v=variant(id),outs=['gentle','focused','expert'].map(d=>gen.make(v,1212,d));assert.ok(outs[0].generation.clues>=outs[1].generation.clues,id+' gentle/focused clues');assert.ok(outs[1].generation.clues>=outs[2].generation.clues,id+' focused/expert clues');for(const out of outs){assert.ok(Number.isFinite(out.generation.difficultyScore)&&out.generation.difficultyScore>0,id+' measured difficulty');assert.ok(out.generation.searchStats&&Number.isFinite(out.generation.searchStats.nodes),id+' search stats');}}});

test('Numbered Rooms and Next to Nine runtime enforcement and visual hooks are present',()=>{const genSource=fs.readFileSync(path.join(__dirname,'../games/sudoku-generator.js'),'utf8'),lib=fs.readFileSync(path.join(__dirname,'../games/sudoku-library.js'),'utf8');for(const token of ['outsideClueIndexCache','affectedOutsideClues','numberedRoomsValid','nextToNineValid'])assert.ok(genSource.includes(token),token);for(const token of ["kindIs(v,'numberedrooms')","kindIs(v,'nexttonine')",'cl.digit','cl.digits.join'])assert.ok(lib.includes(token),token);});