'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');global.window=global;
for(const f of ['sudoku-bank.js','sudoku-bank-iteration2.js','sudoku-bank-iteration3.js','sudoku-bank-iteration4.js','sudoku-bank-iteration5.js','sudoku-bank-iteration6.js','sudoku-bank-iteration7.js','sudoku-bank-iteration8.js','sudoku-bank-iteration9.js','sudoku-bank-iteration10.js','sudoku-bank-iteration11.js','sudoku-bank-iteration12.js','sudoku-bank-iteration13.js','sudoku-bank-iteration14.js','sudoku-bank-iteration15.js','sudoku-bank-iteration16.js','sudoku-generator.js','extra-house-generator-core.js','diagonal-generator-hardening.js','iteration4-generator-hardening.js','iteration5-generator-hardening.js','iteration6-generator-hardening.js','iteration7-generator-hardening.js','iteration8-generator-hardening.js','iteration9-generator-hardening.js','iteration10-generator-hardening.js','iteration11-generator-hardening.js','iteration12-generator-hardening.js','iteration13-generator-hardening.js','iteration14-generator-hardening.js','iteration15-generator-hardening.js','iteration16-generator-hardening.js'])vm.runInThisContext(fs.readFileSync(path.join(root,'games',f),'utf8'));
const ids=['inside-skyscrapers','diagonal-skyscrapers'],difficulties=['gentle','focused','expert'];
function variant(id){return SudokuBank.find(v=>v.id===id);}
function visible(a){let m=0,n=0;for(const x of a)if(x>m){m=x;n++;}return n;}
function givens(p){return p.flat().filter(Boolean).length;}

test('Iteration 16 static solutions satisfy every sightline clue',()=>{const inside=variant('inside-skyscrapers');for(const cl of inside.data.sightClues)assert.equal(inside.solution[cl.source[0]][cl.source[1]],visible(cl.cells.map(p=>inside.solution[p[0]][p[1]])),JSON.stringify(cl));const diagonal=variant('diagonal-skyscrapers');for(const cl of diagonal.data.sightClues)assert.equal(cl.count,visible(cl.cells.map(p=>diagonal.solution[p[0]][p[1]])),JSON.stringify(cl));});

test('Iteration 16 generation is deterministic, seed-diverse, unique and variant-essential',()=>{for(const id of ids){const v=variant(id);for(const difficulty of difficulties){const a=SudokuGenerator.make(v,1616,difficulty),b=SudokuGenerator.make(v,1616,difficulty),c=SudokuGenerator.make(v,2026,difficulty);assert.deepEqual(a.puzzle,b.puzzle,id+' deterministic '+difficulty);assert.notDeepEqual(a.puzzle,c.puzzle,id+' seed-diverse '+difficulty);assert.equal(a.generation.unique,true,id+' unique '+difficulty);assert.equal(a.generation.variantEssential,true,id+' essential '+difficulty);assert.equal(SudokuGenerator.countVariantSolutions(a.puzzle,a,2),1,id+' solver unique '+difficulty);assert.ok(SudokuGenerator.countSolutions(a.puzzle,2)>1,id+' classic ambiguous '+difficulty);}}});

test('Iteration 16 difficulty is clue-ordered and carries measured variant search evidence',()=>{for(const id of ids){const v=variant(id),made=difficulties.map(d=>SudokuGenerator.make(v,1620,d));assert.ok(givens(made[0].puzzle)>=givens(made[1].puzzle),id+' gentle/focused clues');assert.ok(givens(made[1].puzzle)>=givens(made[2].puzzle),id+' focused/expert clues');for(const x of made){assert.ok(x.generation.searchStats,id+' search stats');for(const k of ['nodes','branches','deadEnds','solutions'])assert.equal(typeof x.generation.searchStats[k],'number',id+' '+k);assert.equal(typeof x.generation.difficultyScore,'number',id+' difficulty score');assert.ok(x.generation.difficultyScore>=0,id+' nonnegative score');}}});

test('Iteration 16 runtime enforcement, rotation and visual hooks are present',()=>{const gen=fs.readFileSync(path.join(root,'games/sudoku-generator.js'),'utf8'),lib=fs.readFileSync(path.join(root,'games/sudoku-library.js'),'utf8');for(const t of ['sightClueIndexCache','sightlineValid','insideskyscrapers:true','diagonalskyscrapers:true'])assert.ok(gen.includes(t),t);for(const t of ['sightlineConflict','sudoku-inside-sky-marker','sudoku-diagonal-sky-marker','d.sightClues'])assert.ok(lib.includes(t),t);});
