'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.join(__dirname,'..'),gen=fs.readFileSync(path.join(root,'games/sudoku-generator.js'),'utf8'),bank=fs.readFileSync(path.join(root,'games/sudoku-bank.js'),'utf8'),core=fs.readFileSync(path.join(root,'games/extra-house-generator-core.js'),'utf8'),hardening=fs.readFileSync(path.join(root,'games/extra-house-generator-hardening.js'),'utf8'),lib=fs.readFileSync(path.join(root,'games/sudoku-library.js'),'utf8');
function context(){const c={console,globalThis:null,window:null,Map,Set,WeakMap};c.globalThis=c;c.window=c;vm.createContext(c);vm.runInContext(bank,c);vm.runInContext(gen,c);vm.runInContext(core,c);vm.runInContext(hardening,c);return c;}
function variant(c){const v=c.SudokuBank.find(x=>x.id==='kropki');assert.ok(v);return v;}
function median(xs){const a=xs.slice().sort((x,y)=>x-y),m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2;}
test('Kropki canonical solution satisfies every marked relation',()=>{const c=context(),v=variant(c);for(const e of v.data.edges){const a=v.solution[e.a[0]][e.a[1]],b=v.solution[e.b[0]][e.b[1]];if(e.type==='white')assert.equal(Math.abs(a-b),1);else assert.ok(a===2*b||b===2*a);}});
test('Kropki renderer recognizes Kropki edge relations',()=>{assert.match(lib,/v\.kind==='kropki'/);assert.match(lib,/d\.edges/);});
test('Kropki generation is deterministic, fresh, solver-certified and variant-essential',()=>{const c=context(),v=variant(c),solutions=new Set(),topologies=new Set();for(const d of ['gentle','focused','expert'])for(const seed of [1,17,101,2026]){const a=c.SudokuGenerator.make(v,seed,d),b=c.SudokuGenerator.make(v,seed,d);assert.deepEqual(a,b);assert.equal(a.generation.unique,true);assert.equal(a.generation.verification,'solver-verified');assert.equal(a.generation.mode,'seeded-variant-essential');assert.equal(a.generation.variantEssential,true);assert.equal(a.generation.generatorFamily,'adjacency-fresh-fill-mrv');assert.equal(c.SudokuGenerator.countVariantSolutions(a.puzzle,a,2),1);assert.ok(c.SudokuGenerator.countSolutions(a.puzzle,2)>1);for(const e of a.data.edges){const x=a.solution[e.a[0]][e.a[1]],y=a.solution[e.b[0]][e.b[1]];if(e.type==='white')assert.equal(Math.abs(x-y),1);else assert.ok(x===2*y||y===2*x);}solutions.add(JSON.stringify(a.solution));topologies.add(JSON.stringify(a.data.edges));}assert.ok(solutions.size>1);assert.ok(topologies.size>1);});
test('Kropki exposes measured Gentle < Focused < Expert difficulty',()=>{const c=context(),v=variant(c),scores={gentle:[],focused:[],expert:[]};for(const d of Object.keys(scores))for(const seed of [1,17,101,2026,20260828])scores[d].push(c.SudokuGenerator.make(v,seed,d).generation.difficultyScore);assert.ok(median(scores.gentle)<median(scores.focused));assert.ok(median(scores.focused)<median(scores.expert));});
test('Kropki retains shared notes, Check cleanup, completion and language refresh',()=>{assert.match(lib,/note-mode-button/);assert.match(lib,/classList\.remove\('checked-wrong'\)/);assert.match(lib,/api\.solved\(\)/);assert.match(lib,/refreshLanguage:function\(\)/);});
