'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.join(__dirname,'..');
function load(){const ctx={console,globalThis:null,window:null,Map,Set,WeakMap};ctx.globalThis=ctx;ctx.window=ctx;vm.createContext(ctx);for(const f of ['games/sudoku-bank.js','games/sudoku-generator.js','games/line-generator-core.js','games/line-generator-endpoint.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),ctx,{filename:f});return ctx;}
function variant(ctx){const v=ctx.SudokuBank.find(x=>x.id==='between');assert.ok(v);return v;}
function solutionKey(grid){return grid.map(row=>row.join('')).join('/');}
function assertBetween(ctx,g){for(const item of g.data.lines){const line=item.cells;assert.equal(ctx.LineGeneratorCore.validateSimplePath(line,{minLength:4,maxLength:7}),true);const a=g.solution[line[0][0]][line[0][1]],b=g.solution[line[line.length-1][0]][line[line.length-1][1]],lo=Math.min(a,b),hi=Math.max(a,b);assert.notEqual(a,b);for(let i=1;i<line.length-1;i++){const v=g.solution[line[i][0]][line[i][1]];assert.ok(v>lo&&v<hi,`interior ${v} not strictly between ${lo} and ${hi}`);}}}

test('Between endpoint builder returns deterministic valid path on a fresh solution',()=>{const ctx=load(),fresh=ctx.LineGeneratorCore.freshStandardSolution(17).grid,a=ctx.LineGeneratorEndpoint.buildBetweenPath(fresh,17),b=ctx.LineGeneratorEndpoint.buildBetweenPath(fresh,17);assert.deepEqual(a.path,b.path);const fake={solution:fresh,data:{lines:[{cells:a.path}]}};assertBetween(ctx,fake);});

test('Between four-seed pilot is fresh, deterministic, exact unique and variant-essential',()=>{const ctx=load(),v=variant(ctx),seeds=[1,17,101,2026],solutions=new Set(),topologies=new Set();for(const seed of seeds){const a=ctx.LineGeneratorEndpoint.makeBetweenPilot(ctx.SudokuGenerator,v,seed,'focused'),b=ctx.LineGeneratorEndpoint.makeBetweenPilot(ctx.SudokuGenerator,v,seed,'focused');assert.deepEqual(a.solution,b.solution);assert.deepEqual(a.puzzle,b.puzzle);assert.deepEqual(a.data.lines,b.data.lines);assert.equal(a.generation.generatorFamily,'line-between-fresh-fill-mrv');assert.equal(a.generation.variantEssential,true);assert.equal(a.generation.unique,true);assert.equal(a.generation.pilot,true);assert.equal(ctx.SudokuGenerator.countVariantSolutions(a.puzzle,a,2),1);assert.ok(ctx.SudokuGenerator.countSolutions(a.puzzle,2)>1);assertBetween(ctx,a);solutions.add(solutionKey(a.solution));topologies.add(a.generation.topologyFingerprint);}assert.ok(solutions.size>=3);assert.ok(topologies.size>=3);});

test('bounded impossible Between search fails explicitly with GENERATION_EXHAUSTED',()=>{const ctx=load(),solution=ctx.LineGeneratorCore.freshStandardSolution(7).grid;assert.throws(()=>ctx.LineGeneratorEndpoint.buildBetweenPath(solution,7,{minLength:8,maxLength:8,maxNodes:1,maxPairs:1}),/GENERATION_EXHAUSTED/);});
