'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.join(__dirname,'..');
function load(){const ctx={console,globalThis:null,window:null,Map,Set,WeakMap};ctx.globalThis=ctx;ctx.window=ctx;vm.createContext(ctx);for(const f of ['games/sudoku-bank.js','games/sudoku-bank-iteration2.js','games/sudoku-generator.js','games/line-generator-core.js','games/line-generator-symmetric.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),ctx,{filename:f});return ctx;}
function variant(ctx){const v=ctx.SudokuBank.find(x=>x.id==='zipper');assert.ok(v);return v;}
function solutionKey(grid){return grid.map(r=>r.join('')).join('/');}
function assertZipper(ctx,g){for(const wrapper of g.data.lines){const line=wrapper.cells;assert.ok(line.length>=3&&line.length<=7&&(line.length&1)===1);assert.equal(ctx.LineGeneratorCore.validateSimplePath(line,{minLength:3,maxLength:7}),true);const mid=(line.length-1)/2,target=g.solution[line[mid][0]][line[mid][1]];for(let d=1;d<=mid;d++){const a=line[mid-d],b=line[mid+d];assert.equal(g.solution[a[0]][a[1]]+g.solution[b[0]][b[1]],target);}}}

test('Zipper four-seed pilot is deterministic, exact unique and variant-essential',()=>{const ctx=load(),v=variant(ctx),solutions=new Set(),topologies=new Set();for(const seed of [1,17,101,2026]){const a=ctx.LineGeneratorSymmetric.makeZipperPilot(ctx.SudokuGenerator,v,seed,'focused'),b=ctx.LineGeneratorSymmetric.makeZipperPilot(ctx.SudokuGenerator,v,seed,'focused');assert.deepEqual(a.solution,b.solution);assert.deepEqual(a.puzzle,b.puzzle);assert.deepEqual(a.data.lines,b.data.lines);assert.equal(a.generation.generatorFamily,'line-zipper-fresh-fill-mrv');assert.equal(a.generation.variantEssential,true);assert.equal(ctx.SudokuGenerator.countVariantSolutions(a.puzzle,a,2),1);assert.ok(ctx.SudokuGenerator.countSolutions(a.puzzle,2)>1);assertZipper(ctx,a);solutions.add(solutionKey(a.solution));topologies.add(a.generation.topologyFingerprint);}assert.ok(solutions.size>=3);assert.ok(topologies.size>=3);});

test('Zipper pilot does not reuse static bank family for all seeds',()=>{const ctx=load(),v=variant(ctx),bankSolution=solutionKey(v.solution),bankTopology=ctx.LineGeneratorCore.topologyFingerprint(v.data.lines.map(x=>x.cells));const generated=[1,17,101,2026].map(seed=>ctx.LineGeneratorSymmetric.makeZipperPilot(ctx.SudokuGenerator,v,seed,'focused'));assert.ok(generated.some(g=>solutionKey(g.solution)!==bankSolution));assert.ok(generated.some(g=>g.generation.topologyFingerprint!==bankTopology));});

test('bounded impossible Zipper search fails explicitly with GENERATION_EXHAUSTED',()=>{const ctx=load(),solution=Array.from({length:9},()=>Array(9).fill(9));assert.throws(()=>ctx.LineGeneratorSymmetric.buildZipperPath(solution,7,{minLength:7,maxLength:7,maxNodes:1,maxCenters:1}),/GENERATION_EXHAUSTED/);});
