'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.join(__dirname,'..');
function load(){const ctx={console,globalThis:null,window:null,Map,Set,WeakMap};ctx.globalThis=ctx;ctx.window=ctx;vm.createContext(ctx);for(const f of ['games/sudoku-bank.js','games/sudoku-generator.js','games/line-generator-core.js','games/line-generator-whole-set.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),ctx,{filename:f});return ctx;}
function variant(ctx){const v=ctx.SudokuBank.find(x=>x.id==='renban');assert.ok(v);return v;}
function solutionKey(grid){return grid.map(row=>row.join('')).join('/');}
function assertRenbanLine(g,line){const vals=line.map(([r,c])=>g.solution[r][c]),uniq=new Set(vals);assert.equal(uniq.size,line.length);const min=Math.min(...vals),max=Math.max(...vals);assert.equal(max-min,line.length-1);}

test('Renban whole-set builder returns a simple path realizing one consecutive set',()=>{const ctx=load(),solution=ctx.LineGeneratorCore.freshStandardSolution(17).grid,b=ctx.LineGeneratorWholeSet.buildRenbanPath(solution,17,{minLength:4,maxLength:6});assert.equal(ctx.LineGeneratorCore.validateSimplePath(b.path,{minLength:4,maxLength:6}),true);const vals=b.path.map(([r,c])=>solution[r][c]);assert.equal(new Set(vals).size,b.path.length);assert.equal(Math.max(...vals)-Math.min(...vals),b.path.length-1);});

test('Renban four-seed pilot is deterministic, fresh, exact unique and variant-essential',()=>{const ctx=load(),v=variant(ctx),seeds=[1,17,101,2026],solutions=new Set(),topologies=new Set();for(const seed of seeds){const a=ctx.LineGeneratorWholeSet.makeRenbanPilot(ctx.SudokuGenerator,v,seed,'focused'),b=ctx.LineGeneratorWholeSet.makeRenbanPilot(ctx.SudokuGenerator,v,seed,'focused');assert.deepEqual(a.solution,b.solution);assert.deepEqual(a.puzzle,b.puzzle);assert.deepEqual(a.data.lines,b.data.lines);assert.equal(a.generation.generatorFamily,'line-renban-fresh-fill-mrv');assert.equal(a.generation.variantEssential,true);assert.equal(a.generation.unique,true);assert.equal(ctx.SudokuGenerator.countVariantSolutions(a.puzzle,a,2),1);assert.ok(ctx.SudokuGenerator.countSolutions(a.puzzle,2)>1);for(const line of a.data.lines){assert.equal(ctx.LineGeneratorCore.validateSimplePath(line,{minLength:4,maxLength:6}),true);assertRenbanLine(a,line);}solutions.add(solutionKey(a.solution));topologies.add(a.generation.topologyFingerprint);}assert.ok(solutions.size>=3);assert.ok(topologies.size>=3);});

test('Renban impossible bounded search reports GENERATION_EXHAUSTED',()=>{const ctx=load(),solution=ctx.LineGeneratorCore.freshStandardSolution(7).grid;assert.throws(()=>ctx.LineGeneratorWholeSet.buildRenbanPath(solution,7,{minLength:9,maxLength:9,maxNodes:1}),/GENERATION_EXHAUSTED/);});
