'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.join(__dirname,'..');
function load(){const ctx={console,globalThis:null,window:null,Map,Set,WeakMap};ctx.globalThis=ctx;ctx.window=ctx;vm.createContext(ctx);for(const f of ['games/sudoku-bank.js','games/sudoku-bank-iteration2.js','games/sudoku-bank-iteration3.js','games/sudoku-generator.js','games/line-generator-core.js','games/line-generator-transition.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),ctx,{filename:f});return ctx;}
function key(grid){return grid.map(r=>r.join('')).join('/');}
function assertSemantics(ctx,g,id){for(const line of g.data.lines){assert.equal(ctx.LineGeneratorCore.validateSimplePath(line,{minLength:4,maxLength:7}),true);for(let i=1;i<line.length;i++){const a=g.solution[line[i-1][0]][line[i-1][1]],b=g.solution[line[i][0]][line[i][1]];if(id==='dutch-whispers')assert.ok(Math.abs(a-b)>=4);else assert.notEqual(a&1,b&1);}}}

for(const id of ['dutch-whispers','parity-line'])test(`${id} four-seed transition pilot is fresh, deterministic, exact and essential`,()=>{const ctx=load(),v=ctx.SudokuBank.find(x=>x.id===id);assert.ok(v);const solutions=new Set(),topologies=new Set();for(const seed of [1,17,101,2026]){const a=ctx.LineGeneratorTransition.makeTransitionVariant(ctx.SudokuGenerator,v,seed,'focused'),b=ctx.LineGeneratorTransition.makeTransitionVariant(ctx.SudokuGenerator,v,seed,'focused');assert.deepEqual(a.solution,b.solution);assert.deepEqual(a.puzzle,b.puzzle);assert.deepEqual(a.data.lines,b.data.lines);assert.equal(a.generation.variantEssential,true);assert.equal(a.generation.unique,true);assert.equal(a.generation.pilot,true);assert.equal(ctx.SudokuGenerator.countVariantSolutions(a.puzzle,a,2),1);assert.ok(ctx.SudokuGenerator.countSolutions(a.puzzle,2)>1);assertSemantics(ctx,a,id);solutions.add(key(a.solution));topologies.add(a.generation.topologyFingerprint);}assert.ok(solutions.size>=3);assert.ok(topologies.size>=3);});

test('local-transition sibling adapter rejects unsupported variants explicitly',()=>{const ctx=load(),v=ctx.SudokuBank.find(x=>x.id==='classic');assert.throws(()=>ctx.LineGeneratorTransition.makeTransitionVariant(ctx.SudokuGenerator,v,1,'focused'),/Unsupported transition variant/);});
