'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm'),performance=require('node:perf_hooks').performance;
const root=path.join(__dirname,'..');
function load(){const ctx={console,globalThis:null,window:null,Map,Set,WeakMap};ctx.globalThis=ctx;ctx.window=ctx;vm.createContext(ctx);const files=['games/sudoku-bank.js'];for(let i=2;i<=23;i++)files.push(`games/sudoku-bank-iteration${i}.js`);for(let i=30;i<=38;i++)files.push(`games/sudoku-bank-iteration${i}.js`);for(let i=50;i<=52;i++)files.push(`games/sudoku-bank-iteration${i}.js`);files.push('games/sudoku-generator.js','games/line-generator-core.js','games/line-generator-proven-siblings.js','games/line-generator-proven-siblings-hardening.js');for(const f of files){const p=path.join(root,f);if(fs.existsSync(p))vm.runInContext(fs.readFileSync(p,'utf8'),ctx,{filename:f});}return ctx;}
function p95(xs){const a=xs.slice().sort((x,y)=>x-y);return a[Math.min(a.length-1,Math.ceil(a.length*0.95)-1)];}
function rawLine(entry){return Array.isArray(entry)?entry:entry.cells;}
const SEEDS=[3,11,23,37,53,71,97,127,173,223,313,421];

test('Lockout expert uses strengthened topology and stays below runtime contract on targeted pilot',()=>{const ctx=load(),v=ctx.SudokuBank.find(x=>x.id==='lockout');assert.ok(v);const times=[];for(const seed of SEEDS){const t0=performance.now(),a=ctx.SudokuGenerator.make(v,seed,'expert'),elapsed=performance.now()-t0,b=ctx.SudokuGenerator.make(v,seed,'expert');times.push(elapsed);assert.equal(a.generation.generatorFamily,'line-lockout-fresh-fill-mrv');assert.equal(a.generation.pilot,false);assert.ok(a.generation.lineCount>=3);assert.deepEqual(a.solution,b.solution);assert.deepEqual(a.puzzle,b.puzzle);assert.deepEqual(a.data.lines,b.data.lines);assert.equal(ctx.SudokuGenerator.countVariantSolutions(a.puzzle,a,2),1);assert.ok(ctx.SudokuGenerator.countSolutions(a.puzzle,2)>1);for(const entry of a.data.lines){const line=rawLine(entry),values=line.map(([r,c])=>a.solution[r][c]),lo=Math.min(values[0],values[values.length-1]),hi=Math.max(values[0],values[values.length-1]);for(let i=1;i<values.length-1;i++)assert.ok(values[i]<lo||values[i]>hi);}}const summary={seeds:SEEDS.length,p95Ms:p95(times),maxMs:Math.max(...times)};console.log('LOCKOUT_EXPERT_RUNTIME_PILOT '+JSON.stringify(summary));assert.ok(summary.p95Ms<1000);});
