'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.join(__dirname,'..');
function load(){const ctx={console,globalThis:null,window:null,Map,Set,WeakMap};ctx.globalThis=ctx;ctx.window=ctx;vm.createContext(ctx);for(const f of ['games/sudoku-bank.js','games/sudoku-generator.js','games/line-generator-core.js','games/line-generator-whole-set.js','games/line-generator-hardening.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),ctx,{filename:f});return ctx;}
function variant(ctx,id){const v=ctx.SudokuBank.find(x=>x.id===id);assert.ok(v);return v;}
function solutionKey(grid){return grid.map(r=>r.join('')).join('/');}
function assertBetween(ctx,g){for(const wrapped of g.data.lines){const line=wrapped.cells;assert.equal(ctx.LineGeneratorCore.validateSimplePath(line,{minLength:4,maxLength:7}),true);const a=g.solution[line[0][0]][line[0][1]],b=g.solution[line[line.length-1][0]][line[line.length-1][1]],lo=Math.min(a,b),hi=Math.max(a,b);assert.notEqual(a,b);for(let i=1;i<line.length-1;i++){const v=g.solution[line[i][0]][line[i][1]];assert.ok(v>lo&&v<hi);}}}

test('production make routes Between through fresh endpoint generator without separately loading endpoint primitive',()=>{const ctx=load(),v=variant(ctx,'between');for(const seed of [1,17,101,2026]){const g=ctx.SudokuGenerator.make(v,seed,'focused');assert.equal(g.generation.generatorFamily,'line-between-fresh-fill-mrv');assert.equal(g.generation.pilot,false);assert.equal(g.generation.variantEssential,true);assert.equal(ctx.SudokuGenerator.countVariantSolutions(g.puzzle,g,2),1);assert.ok(ctx.SudokuGenerator.countSolutions(g.puzzle,2)>1);assertBetween(ctx,g);}});

test('production Between replay is exact and pilot seeds vary solution/topology',()=>{const ctx=load(),v=variant(ctx,'between'),solutions=new Set(),topologies=new Set();for(const seed of [1,17,101,2026]){const a=ctx.SudokuGenerator.make(v,seed,'focused'),b=ctx.SudokuGenerator.make(v,seed,'focused');assert.deepEqual(a.solution,b.solution);assert.deepEqual(a.puzzle,b.puzzle);assert.deepEqual(a.data.lines,b.data.lines);solutions.add(solutionKey(a.solution));topologies.add(a.generation.topologyFingerprint);}assert.ok(solutions.size>=3);assert.ok(topologies.size>=3);});

test('Whispers and Renban production routes remain intact after Between wiring',()=>{const ctx=load();const w=ctx.SudokuGenerator.make(variant(ctx,'whispers'),17,'focused'),r=ctx.SudokuGenerator.make(variant(ctx,'renban'),17,'focused');assert.equal(w.generation.generatorFamily,'line-whispers-fresh-fill-mrv');assert.equal(r.generation.generatorFamily,'line-renban-fresh-fill-mrv');assert.equal(w.generation.pilot,false);assert.equal(r.generation.pilot,false);});
