'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.join(__dirname,'..');
function load(){const ctx={console,globalThis:null,window:null,Map,Set,WeakMap};ctx.globalThis=ctx;ctx.window=ctx;vm.createContext(ctx);for(const f of ['games/sudoku-bank.js','games/sudoku-bank-iteration2.js','games/sudoku-bank-iteration3.js','games/sudoku-generator.js','games/line-generator-core.js','games/line-generator-whole-set.js','games/line-generator-hardening.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),ctx,{filename:f});return ctx;}
function assertSemantics(id,g){for(const line of g.data.lines){assert.equal(g.LineGeneratorCore.validateSimplePath(line,{minLength:4,maxLength:7}),true);for(let i=1;i<line.length;i++){const a=g.solution[line[i-1][0]][line[i-1][1]],b=g.solution[line[i][0]][line[i][1]];if(id==='dutch-whispers')assert.ok(Math.abs(a-b)>=4);else assert.notEqual(a&1,b&1);}}}

test('production make routes Dutch Whispers and Parity Line through shared transition generator',()=>{const ctx=load();for(const id of ['dutch-whispers','parity-line']){const v=ctx.SudokuBank.find(x=>x.id===id);assert.ok(v);for(const seed of [1,17,101,2026]){const g=ctx.SudokuGenerator.make(v,seed,'focused');g.LineGeneratorCore=ctx.LineGeneratorCore;assert.equal(g.generation.pilot,false);assert.equal(g.generation.variantEssential,true);assert.equal(ctx.SudokuGenerator.countVariantSolutions(g.puzzle,g,2),1);assert.ok(ctx.SudokuGenerator.countSolutions(g.puzzle,2)>1);assertSemantics(id,g);}}});

test('production replay is exact for both transition siblings',()=>{const ctx=load();for(const id of ['dutch-whispers','parity-line']){const v=ctx.SudokuBank.find(x=>x.id===id);for(const seed of [1,17,101,2026]){const a=ctx.SudokuGenerator.make(v,seed,'focused'),b=ctx.SudokuGenerator.make(v,seed,'focused');assert.deepEqual(a.solution,b.solution);assert.deepEqual(a.puzzle,b.puzzle);assert.deepEqual(a.data.lines,b.data.lines);}}});

test('existing completed line routes remain intact',()=>{const ctx=load();for(const [id,family] of [['whispers','line-whispers-fresh-fill-mrv'],['renban','line-renban-fresh-fill-mrv'],['between','line-between-fresh-fill-mrv'],['zipper','line-zipper-fresh-fill-mrv']]){const v=ctx.SudokuBank.find(x=>x.id===id);assert.ok(v);const g=ctx.SudokuGenerator.make(v,17,'focused');assert.equal(g.generation.generatorFamily,family);assert.equal(g.generation.pilot,false);}});
