'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.join(__dirname,'..');
function load(){const ctx={console,globalThis:null,window:null,Map,Set,WeakMap};ctx.globalThis=ctx;ctx.window=ctx;vm.createContext(ctx);for(const f of ['games/sudoku-bank.js','games/sudoku-bank-iteration2.js','games/sudoku-bank-iteration3.js','games/sudoku-generator.js','games/line-generator-core.js','games/line-generator-whole-set.js','games/line-generator-proven-siblings.js','games/line-generator-hardening.js','games/line-generator-proven-siblings-hardening.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),ctx,{filename:f});return ctx;}
function lines(g){return g.data.lines.map(x=>Array.isArray(x)?x:x.cells);}
function assertSemantics(ctx,id,g){for(const line of lines(g)){assert.equal(ctx.LineGeneratorCore.validateSimplePath(line,{minLength:3,maxLength:7}),true);const values=line.map(([r,c])=>g.solution[r][c]);if(id==='nabner'){assert.equal(new Set(values).size,values.length);for(let i=0;i<values.length;i++)for(let j=i+1;j<values.length;j++)assert.notEqual(Math.abs(values[i]-values[j]),1);}else if(id==='palindrome'){for(let i=0;i<values.length;i++)assert.equal(values[i],values[values.length-1-i]);}else{const lo=Math.min(values[0],values[values.length-1]),hi=Math.max(values[0],values[values.length-1]);assert.ok(hi-lo>=3);for(let i=1;i<values.length-1;i++)assert.ok(values[i]<lo||values[i]>hi);}}}
const SPECS=[['nabner','line-nabner-fresh-fill-mrv'],['palindrome','line-palindrome-fresh-fill-mrv'],['lockout','line-lockout-fresh-fill-mrv']];
test('production make routes proven line siblings through fresh generators',()=>{const ctx=load();for(const [id,family] of SPECS){const v=ctx.SudokuBank.find(x=>x.id===id);assert.ok(v);for(const seed of [1,17,101,2026]){const g=ctx.SudokuGenerator.make(v,seed,'focused');assert.equal(g.generation.generatorFamily,family);assert.equal(g.generation.pilot,false);assert.equal(g.generation.variantEssential,true);assert.equal(ctx.SudokuGenerator.countVariantSolutions(g.puzzle,g,2),1);assert.ok(ctx.SudokuGenerator.countSolutions(g.puzzle,2)>1);assertSemantics(ctx,id,g);}}});
test('production Lockout expert uses four lines and 29-clue target',()=>{const ctx=load(),v=ctx.SudokuBank.find(x=>x.id==='lockout');assert.ok(v);for(const seed of [3,83,197,421]){const g=ctx.SudokuGenerator.make(v,seed,'expert');assert.equal(g.generation.generatorFamily,'line-lockout-fresh-fill-mrv');assert.equal(g.generation.pilot,false);assert.equal(g.generation.clues,29);assert.equal(g.generation.lineCount,4);assert.equal(ctx.SudokuGenerator.countVariantSolutions(g.puzzle,g,2),1);assert.ok(ctx.SudokuGenerator.countSolutions(g.puzzle,2)>1);assertSemantics(ctx,'lockout',g);}});
test('production replay is exact for all proven line siblings',()=>{const ctx=load();for(const [id] of SPECS){const v=ctx.SudokuBank.find(x=>x.id===id);for(const seed of [1,17,101,2026]){const a=ctx.SudokuGenerator.make(v,seed,'focused'),b=ctx.SudokuGenerator.make(v,seed,'focused');assert.deepEqual(a.solution,b.solution);assert.deepEqual(a.puzzle,b.puzzle);assert.deepEqual(a.data.lines,b.data.lines);}}});
test('previous Category A line routes remain intact',()=>{const ctx=load();for(const [id,family] of [['whispers','line-whispers-fresh-fill-mrv'],['renban','line-renban-fresh-fill-mrv'],['between','line-between-fresh-fill-mrv'],['zipper','line-zipper-fresh-fill-mrv'],['dutch-whispers','line-dutch-whispers-fresh-fill-mrv'],['parity-line','line-parity-fresh-fill-mrv']]){const v=ctx.SudokuBank.find(x=>x.id===id);assert.ok(v);const g=ctx.SudokuGenerator.make(v,17,'focused');assert.equal(g.generation.generatorFamily,family);assert.equal(g.generation.pilot,false);}});
