'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const css=fs.readFileSync(path.join(root,'assets/styles.css'),'utf8');
const lib=fs.readFileSync(path.join(root,'games/sudoku-library.js'),'utf8');
const app=fs.readFileSync(path.join(root,'assets/app.js'),'utf8');
const i18n=fs.readFileSync(path.join(root,'assets/i18n.js'),'utf8');
assert(html.includes('Ildi Sudoku Kertje'));
assert(i18n.includes("brand:'Ildi Sudoku Kertje'"));
assert(i18n.includes("Ildi's Sudoku Garden"));
assert(html.includes('category-select') && html.includes('variant-select'));
assert(html.includes('category-list') && html.includes('favorites-list') && html.includes('stats-list'));
assert(lib.includes("document.dispatchEvent(new CustomEvent('sudoku:variantchange'"));
assert(lib.includes("document.addEventListener('sudoku:select'"));
assert(app.includes('ildi-sudoku-favourites') && app.includes('ildi-sudoku-stats'));
assert(css.includes('Ildi Sudoku Kertje — Garden UI v2'));
assert(!html.includes('launcher'));
console.log('PASS personal design v2: floral Ildi branding, category sidebar, favourites, stats, bilingual garden UI');
