'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');global.window=global;
for(const f of ['sudoku-bank.js','sudoku-bank-iteration2.js','sudoku-bank-iteration3.js','sudoku-bank-iteration4.js','sudoku-bank-iteration5.js','sudoku-bank-iteration6.js','sudoku-bank-iteration7.js','sudoku-bank-iteration8.js','sudoku-bank-iteration9.js','sudoku-generator.js'])vm.runInThisContext(fs.readFileSync(path.join(root,'games',f),'utf8'));
function normal(g){for(const row of g)assert.deepEqual([...row].sort((a,b)=>a-b),[1,2,3,4,5,6,7,8,9]);for(let c=0;c<9;c++)assert.deepEqual(g.map(r=>r[c]).sort((a,b)=>a-b),[1,2,3,4,5,6,7,8,9]);}
test('iteration 9 expands catalogue from 63 to 65 systems',()=>{assert.equal(SudokuBank.length,65);assert.ok(SudokuBank.find(v=>v.id==='axia'));assert.ok(SudokuBank.find(v=>v.id==='couples'));});
test('Axia solution obeys every marked-cell diagonal exclusion',()=>{const v=SudokuBank.find(x=>x.id==='axia');normal(v.solution);assert.equal(v.data.axia.length,15);for(const [r,c] of v.data.axia){const d=v.solution[r][c];for(let dr of [-1,1])for(let dc of [-1,1])for(let k=1;;k++){const rr=r+dr*k,cc=c+dc*k;if(rr<0||rr>=9||cc<0||cc>=9)break;assert.notEqual(v.solution[rr][cc],d,`axia ${r},${c}`);}}});
test('Couples solution obeys same/different parity markers',()=>{const v=SudokuBank.find(x=>x.id==='couples');normal(v.solution);assert.equal(v.data.couples.length,36);for(const cp of v.data.couples){const a=v.solution[cp.a[0]][cp.a[1]],b=v.solution[cp.b[0]][cp.b[1]];assert.equal((a%2)===(b%2),cp.same,JSON.stringify(cp));}});
test('Axia and Couples generation is deterministic, unique, and variant-essential',()=>{for(const id of ['axia','couples']){const v=SudokuBank.find(x=>x.id===id);for(const difficulty of ['gentle','focused','expert'])for(const seed of [7,31,2026]){const a=SudokuGenerator.make(v,seed,difficulty),b=SudokuGenerator.make(v,seed,difficulty);assert.deepEqual(a.puzzle,b.puzzle,id);assert.equal(a.generation.unique,true,id);assert.equal(a.generation.variantEssential,true,id);assert.equal(SudokuGenerator.countVariantSolutions(a.puzzle,v,2),1,id);assert.ok(SudokuGenerator.countSolutions(a.puzzle,2)>1,id+' must require its special rule');}}});
test('iteration 13 rendering, bilingual copy, and constraint-aware note cleanup hooks exist',()=>{const lib=fs.readFileSync(path.join(root,'games/sudoku-library.js'),'utf8'),css=fs.readFileSync(path.join(root,'assets/styles.css'),'utf8'),i18n=fs.readFileSync(path.join(root,'assets/i18n.js'),'utf8');for(const token of ['d.axia','d.couples','sudoku-axia-marker','sudoku-couples-marker','kindIs(v,\'axia\')','kindIs(v,\'couples\')'])assert.ok(lib.includes(token),token);for(const token of ['.sudoku-axia-marker','.sudoku-couples-marker'])assert.ok(css.includes(token),token);for(const token of ["axia:['Axia Sudoku'","couples:['Párok / Couples Sudoku'",'85 Sudoku-változat','85 Sudoku variants'])assert.ok(i18n.includes(token),token);});
