'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');global.window=global;
for(const f of ['sudoku-bank.js','sudoku-bank-iteration2.js','sudoku-bank-iteration3.js','sudoku-bank-iteration4.js','sudoku-bank-iteration5.js','sudoku-bank-iteration6.js','sudoku-bank-iteration7.js','sudoku-bank-iteration8.js','sudoku-bank-iteration9.js','sudoku-bank-iteration10.js','sudoku-bank-iteration11.js','sudoku-generator.js'])vm.runInThisContext(fs.readFileSync(path.join(root,'games',f),'utf8'));
function classicOK(g){for(let r=0;r<9;r++){assert.equal(new Set(g[r]).size,9);assert.equal(new Set(g.map(x=>x[r])).size,9);}for(let br=0;br<9;br+=3)for(let bc=0;bc<9;bc+=3){const a=[];for(let r=br;r<br+3;r++)for(let c=bc;c<bc+3;c++)a.push(g[r][c]);assert.equal(new Set(a).size,9);}}
function bishopOK(v){const g=v.solution,p=v.data.parity;for(let r=0;r<9;r++)for(let c=0;c<9;c++)if(((r+c)&1)===p)for(const [dr,dc] of [[1,1],[1,-1]])for(let k=1;;k++){const rr=r+dr*k,cc=c+dc*k;if(rr<0||rr>=9||cc<0||cc>=9)break;assert.notEqual(g[r][c],g[rr][cc],`bishop repeat ${r},${c} to ${rr},${cc}`);}}
function minmaxOK(v){const g=v.solution;for(const ex of v.data.extrema){const [r,c]=ex.cell,n=[];for(const [dr,dc] of [[1,0],[-1,0],[0,1],[0,-1]]){const rr=r+dr,cc=c+dc;if(rr>=0&&rr<9&&cc>=0&&cc<9)n.push(g[rr][cc]);}assert.ok(n.every(x=>ex.type==='min'?g[r][c]<x:g[r][c]>x),JSON.stringify(ex));}}
test('iteration 15 expands catalogue from 67 to 69 systems',()=>{assert.equal(SudokuBank.length,69);assert.ok(SudokuBank.find(v=>v.id==='bishopsgate'));assert.ok(SudokuBank.find(v=>v.id==='minmax'));});
test('Bishopsgate solution obeys classic Sudoku and the selected checkerboard anti-bishop rule',()=>{const v=SudokuBank.find(x=>x.id==='bishopsgate');classicOK(v.solution);bishopOK(v);});
test('Min/Max markers exactly describe strict orthogonal extrema',()=>{const v=SudokuBank.find(x=>x.id==='minmax');classicOK(v.solution);assert.ok(v.data.extrema.length>=20);minmaxOK(v);});
test('new generators are deterministic, unique, and variant-essential at all difficulties',()=>{for(const id of ['bishopsgate','minmax']){const v=SudokuBank.find(x=>x.id===id);for(const difficulty of ['gentle','focused','expert'])for(const seed of [7,31,2026]){const a=SudokuGenerator.make(v,seed,difficulty),b=SudokuGenerator.make(v,seed,difficulty);assert.deepEqual(a.puzzle,b.puzzle,id);assert.equal(a.generation.unique,true,id);assert.equal(a.generation.variantEssential,true,id);assert.equal(SudokuGenerator.countVariantSolutions(a.puzzle,v,2),1,id);assert.ok(SudokuGenerator.countSolutions(a.puzzle,2)>1,id+' must require its extra rule');}}});
test('iteration 15 rendering, note cleanup, styling, scripts, and bilingual copy are wired',()=>{const lib=fs.readFileSync(path.join(root,'games/sudoku-library.js'),'utf8'),css=fs.readFileSync(path.join(root,'assets/styles.css'),'utf8'),i18n=fs.readFileSync(path.join(root,'assets/i18n.js'),'utf8'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');for(const token of ["kindIs(v,'bishopsgate')","kindIs(v,'minmax')",'bishopsgate-cell','sudoku-minmax-marker','d.extrema'])assert.ok(lib.includes(token),token);assert.ok(css.includes('Iteration 15 — Bishopsgate + Min/Max'));for(const token of ["bishopsgate:['Bishopsgate Sudoku'","minmax:['Minimum / maximum Sudoku'",'85 Sudoku-változat','85 Sudoku variants'])assert.ok(i18n.includes(token),token);assert.ok(html.includes('sudoku-bank-iteration11.js'));});
