'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');global.window=global;
for(const f of ['sudoku-bank.js','sudoku-bank-iteration2.js','sudoku-bank-iteration3.js','sudoku-bank-iteration4.js','sudoku-bank-iteration5.js','sudoku-bank-iteration6.js','sudoku-generator.js'])vm.runInThisContext(fs.readFileSync(path.join(root,'games',f),'utf8'));
function normal(g){assert.equal(g.length,9);for(const row of g)assert.deepEqual([...row].sort((a,b)=>a-b),[1,2,3,4,5,6,7,8,9]);for(let c=0;c<9;c++)assert.deepEqual(g.map(r=>r[c]).sort((a,b)=>a-b),[1,2,3,4,5,6,7,8,9]);for(let br=0;br<9;br+=3)for(let bc=0;bc<9;bc+=3){let z=[];for(let r=br;r<br+3;r++)for(let c=bc;c<bc+3;c++)z.push(g[r][c]);assert.deepEqual(z.sort((a,b)=>a-b),[1,2,3,4,5,6,7,8,9]);}}
function antiQueen9(g){let p=[];for(let r=0;r<9;r++)for(let c=0;c<9;c++)if(g[r][c]===9)p.push([r,c]);for(let i=0;i<p.length;i++)for(let j=i+1;j<p.length;j++)assert.notEqual(Math.abs(p[i][0]-p[j][0]),Math.abs(p[i][1]-p[j][1]));}
function quadSums(v){for(const q of v.data.quadSums){const vals=[[q[0]-1,q[1]-1],[q[0]-1,q[1]],[q[0],q[1]-1],[q[0],q[1]]].map(([r,c])=>v.solution[r][c]),sum=vals.reduce((a,b)=>a+b,0);assert.ok(vals.some(x=>2*x===sum),q.join(','));}}
test('iteration 6 expands catalogue from 58 to 60 systems',()=>{assert.equal(SudokuBank.length,60);assert.ok(SudokuBank.find(v=>v.id==='anti-queen-9'));assert.ok(SudokuBank.find(v=>v.id==='quad-sums'));});
test('Anti-Queen (9) solution obeys standard Sudoku and diagonal queen restriction',()=>{const v=SudokuBank.find(x=>x.id==='anti-queen-9');normal(v.solution);antiQueen9(v.solution);});
test('Quad Sums solution satisfies every black-dot relation',()=>{const v=SudokuBank.find(x=>x.id==='quad-sums');normal(v.solution);assert.ok(v.data.quadSums.length>=10);quadSums(v);});
test('new variant generators are seed-reproducible, unique under the variant, and variant-essential',()=>{for(const id of ['anti-queen-9','quad-sums']){const v=SudokuBank.find(x=>x.id===id);for(const difficulty of ['gentle','focused','expert'])for(const seed of [1,7,12345]){const a=SudokuGenerator.make(v,seed,difficulty),b=SudokuGenerator.make(v,seed,difficulty);assert.deepEqual(a.puzzle,b.puzzle,id);assert.equal(a.generation.unique,true,id);assert.equal(a.generation.variantEssential,true,id);assert.equal(SudokuGenerator.countVariantSolutions(a.puzzle,v,2),1,id);assert.ok(SudokuGenerator.countSolutions(a.puzzle,2)>1,id+' must need its variant rule');}}});
test('different seeds create diverse clue layouts for both new systems',()=>{for(const id of ['anti-queen-9','quad-sums']){const v=SudokuBank.find(x=>x.id===id),seen=new Set();for(let seed=1;seed<=20;seed++)seen.add(SudokuGenerator.make(v,seed,'focused').puzzle.flat().join(''));assert.ok(seen.size>=18,id+' diversity');}});
