'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');global.window=global;
for(const f of ['sudoku-bank.js','sudoku-bank-iteration2.js','sudoku-bank-iteration3.js','sudoku-bank-iteration4.js','sudoku-bank-iteration5.js','sudoku-bank-iteration6.js','sudoku-bank-iteration7.js','sudoku-bank-iteration8.js','sudoku-generator.js'])vm.runInThisContext(fs.readFileSync(path.join(root,'games',f),'utf8'));
function normal(g){for(const row of g)assert.deepEqual([...row].sort((a,b)=>a-b),[1,2,3,4,5,6,7,8,9]);for(let c=0;c<9;c++)assert.deepEqual(g.map(r=>r[c]).sort((a,b)=>a-b),[1,2,3,4,5,6,7,8,9]);for(let br=0;br<9;br+=3)for(let bc=0;bc<9;bc+=3){const z=[];for(let r=br;r<br+3;r++)for(let c=bc;c<bc+3;c++)z.push(g[r][c]);assert.deepEqual(z.sort((a,b)=>a-b),[1,2,3,4,5,6,7,8,9]);}}
test('iteration 8 expands catalogue from 61 to 63 systems',()=>{assert.equal(SudokuBank.length,63);assert.ok(SudokuBank.find(v=>v.id==='reflection'));assert.ok(SudokuBank.find(v=>v.id==='slingshot'));});
test('Reflection solution repeats each same-symbol line sequence exactly',()=>{const v=SudokuBank.find(x=>x.id==='reflection');normal(v.solution);for(const g of v.data.reflectionGroups){assert.ok(g.lines.length>=2);const base=g.lines[0].map(([r,c])=>v.solution[r][c]);for(const line of g.lines.slice(1))assert.deepEqual(line.map(([r,c])=>v.solution[r][c]),base.slice(0,line.length),g.symbol);}});
test('Slingshot solution satisfies every source-distance-direction relation',()=>{const v=SudokuBank.find(x=>x.id==='slingshot');normal(v.solution);assert.ok(v.data.slingshots.length>=8);for(const sh of v.data.slingshots){const n=v.solution[sh.cell[0]][sh.cell[1]],tr=sh.cell[0]+sh.dir[0]*n,tc=sh.cell[1]+sh.dir[1]*n;assert.ok(tr>=0&&tr<9&&tc>=0&&tc<9);assert.equal(v.solution[sh.source[0]][sh.source[1]],v.solution[tr][tc],JSON.stringify(sh));}});
test('Reflection and Slingshot generation is deterministic, variant-unique, and variant-essential',()=>{for(const id of ['reflection','slingshot']){const v=SudokuBank.find(x=>x.id===id);for(const difficulty of ['gentle','focused','expert'])for(const seed of [5,41,2026]){const a=SudokuGenerator.make(v,seed,difficulty),b=SudokuGenerator.make(v,seed,difficulty);assert.deepEqual(a.puzzle,b.puzzle,id);assert.equal(a.generation.unique,true,id);assert.equal(a.generation.variantEssential,true,id);assert.equal(SudokuGenerator.countVariantSolutions(a.puzzle,v,2),1,id);assert.ok(SudokuGenerator.countSolutions(a.puzzle,2)>1,id+' must require its special rule');}}});
test('iteration 12 rendering and pencil-note cleanup hooks are present',()=>{const lib=fs.readFileSync(path.join(root,'games/sudoku-library.js'),'utf8'),css=fs.readFileSync(path.join(root,'assets/styles.css'),'utf8'),i18n=fs.readFileSync(path.join(root,'assets/i18n.js'),'utf8');for(const token of ['reflectionGroups','slingshots','sudoku-reflection-symbol','sudoku-slingshot-arrow','prunePeerNotes'])assert.ok(lib.includes(token),token);for(const token of ['.reflection-line','.sudoku-reflection-symbol','.sudoku-slingshot-source','.sudoku-slingshot-arrow'])assert.ok(css.includes(token),token);for(const token of ["reflection:['Reflection Sudoku'","slingshot:['Slingshot Sudoku'",'85 Sudoku-változat','85 Sudoku variants'])assert.ok(i18n.includes(token),token);});
