'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');global.window=global;
for(const f of ['sudoku-bank.js','sudoku-bank-iteration2.js','sudoku-bank-iteration3.js','sudoku-bank-iteration4.js','sudoku-bank-iteration5.js','sudoku-bank-iteration6.js','sudoku-bank-iteration7.js','sudoku-bank-iteration8.js','sudoku-bank-iteration9.js','sudoku-bank-iteration10.js','sudoku-bank-iteration11.js','sudoku-bank-iteration12.js','sudoku-bank-iteration13.js','sudoku-bank-iteration14.js','sudoku-bank-iteration15.js','sudoku-generator.js'])vm.runInThisContext(fs.readFileSync(path.join(root,'games',f),'utf8'));
function line(v,cl){let a=cl.axis==='row'?v.solution[cl.index].slice():v.solution.map(r=>r[cl.index]);if(cl.side==='right'||cl.side==='bottom')a.reverse();return a;}
function buildings(a){return a.filter(x=>x!==9);}
function visibleCount(a){let m=0,n=0;for(const x of buildings(a))if(x>m){m=x;n++;}return n;}
function visibleSum(a){let m=0,n=0;for(const x of buildings(a))if(x>m){m=x;n+=x;}return n;}
test('iteration 19 expands catalogue from 76 to 78 systems',()=>{assert.equal(SudokuBank.length,78);for(const id of ['skyscraper-parks','sum-skyscraper-parks'])assert.ok(SudokuBank.find(v=>v.id===id),id);});
test('Parks solutions contain 1-8 plus exactly one park in every row and column',()=>{for(const id of ['skyscraper-parks','sum-skyscraper-parks']){const v=SudokuBank.find(x=>x.id===id);for(let i=0;i<9;i++){assert.deepEqual([...v.solution[i]].sort((a,b)=>a-b),[1,2,3,4,5,6,7,8,9]);assert.deepEqual(v.solution.map(r=>r[i]).sort((a,b)=>a-b),[1,2,3,4,5,6,7,8,9]);}}});
test('Parks clues ignore parks and match counts or visible-height sums',()=>{for(const id of ['skyscraper-parks','sum-skyscraper-parks']){const v=SudokuBank.find(x=>x.id===id);assert.equal(v.data.clues.length,36);for(const cl of v.data.clues){if(id==='skyscraper-parks')assert.equal(cl.count,visibleCount(line(v,cl)),JSON.stringify(cl));else assert.equal(cl.sum,visibleSum(line(v,cl)),JSON.stringify(cl));}}});
test('park generators are deterministic, unique, and clue-essential',()=>{for(const id of ['skyscraper-parks','sum-skyscraper-parks']){const v=SudokuBank.find(x=>x.id===id);for(const difficulty of ['gentle','focused','expert'])for(const seed of [19,78,2026]){const a=SudokuGenerator.make(v,seed,difficulty),b=SudokuGenerator.make(v,seed,difficulty);assert.deepEqual(a.puzzle,b.puzzle,id);assert.equal(a.generation.unique,true,id);assert.equal(a.generation.variantEssential,true,id);assert.equal(SudokuGenerator.countParkSolutions(a.puzzle,a,2,false),1,id);assert.ok(SudokuGenerator.countParkSolutions(a.puzzle,a,2,true)>1,id+' must require its outside clues');}}});
test('park UI uses real park symbol, P keyboard input, no Sudoku boxes, and bilingual copy',()=>{const lib=fs.readFileSync(path.join(root,'games/sudoku-library.js'),'utf8'),i18n=fs.readFileSync(path.join(root,'assets/i18n.js'),'utf8'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');for(const token of ["return '🌿'","e.key==='p'||e.key==='P'","!kindIs(v,'skyscraperparks')","kindIs(v,'sumskyscraperparks')"])assert.ok(lib.includes(token),token);for(const token of ["'skyscraper-parks':['Lakótelep – grundokkal / Skyscrapers Parks'","'sum-skyscraper-parks':['Összeges Lakótelep – grundokkal / Sum Skyscrapers Parks'",'85 Sudoku-változat','85 Sudoku variants'])assert.ok(i18n.includes(token),token);assert.ok(html.includes('sudoku-bank-iteration15.js'));});
