'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');global.window=global;
for(const f of ['sudoku-bank.js','sudoku-bank-iteration2.js','sudoku-bank-iteration3.js','sudoku-bank-iteration4.js','sudoku-bank-iteration5.js','sudoku-bank-iteration6.js','sudoku-bank-iteration7.js','sudoku-bank-iteration8.js','sudoku-bank-iteration9.js','sudoku-bank-iteration10.js','sudoku-bank-iteration11.js','sudoku-bank-iteration12.js','sudoku-bank-iteration13.js','sudoku-bank-iteration14.js','sudoku-generator.js'])vm.runInThisContext(fs.readFileSync(path.join(root,'games',f),'utf8'));
function line(v,cl){let a=cl.axis==='row'?v.solution[cl.index].slice():v.solution.map(r=>r[cl.index]);if(cl.side==='right'||cl.side==='bottom')a.reverse();return a;}
function visibleCount(a){let m=0,n=0;for(const x of a)if(x>m){m=x;n++;}return n;}
function visibleSum(a){let m=0,n=0;for(const x of a)if(x>m){m=x;n+=x;}return n;}
test('iteration 18 expands catalogue from 73 to 76 systems',()=>{assert.equal(SudokuBank.length,76);for(const id of ['skyscraper-sums','skyscraper-mixed','skyscraper-nontouching'])assert.ok(SudokuBank.find(v=>v.id===id),id);});
test('Skyscraper Sums clues equal the sum of all visible building heights',()=>{const v=SudokuBank.find(x=>x.id==='skyscraper-sums');assert.equal(v.data.clues.length,18);for(const cl of v.data.clues)assert.equal(cl.sum,visibleSum(line(v,cl)),JSON.stringify(cl));});
test('Mixed Information clues are valid as either visibility count or nearest building height',()=>{const v=SudokuBank.find(x=>x.id==='skyscraper-mixed');assert.equal(v.data.clues.length,18);for(const cl of v.data.clues){const a=line(v,cl);assert.ok(cl.value===visibleCount(a)||cl.value===a[0],JSON.stringify(cl));}});
test('Non-touching Skyscraper solution obeys visibility clues and diagonal non-touching rule',()=>{const v=SudokuBank.find(x=>x.id==='skyscraper-nontouching');for(const cl of v.data.clues)assert.equal(cl.count,visibleCount(line(v,cl)),JSON.stringify(cl));for(let r=0;r<8;r++)for(let c=0;c<8;c++){assert.notEqual(v.solution[r][c],v.solution[r+1][c+1]);assert.notEqual(v.solution[r+1][c],v.solution[r][c+1]);}});
test('new Lakotelep generators are deterministic, unique, and variant-essential at all difficulties',()=>{for(const id of ['skyscraper-sums','skyscraper-mixed','skyscraper-nontouching']){const v=SudokuBank.find(x=>x.id===id);for(const difficulty of ['gentle','focused','expert'])for(const seed of [18,76,2026]){const a=SudokuGenerator.make(v,seed,difficulty),b=SudokuGenerator.make(v,seed,difficulty);assert.deepEqual(a.puzzle,b.puzzle,id);assert.equal(a.generation.unique,true,id);assert.equal(a.generation.variantEssential,true,id);assert.equal(SudokuGenerator.countVariantSolutions(a.puzzle,a,2),1,id);assert.ok(SudokuGenerator.countSolutions(a.puzzle,2)>1,id+' must require its Lakotelep rule');}}});
test('iteration 18 solver, rendering, note cleanup, scripts, and bilingual copy are wired',()=>{const gen=fs.readFileSync(path.join(root,'games/sudoku-generator.js'),'utf8'),lib=fs.readFileSync(path.join(root,'games/sudoku-library.js'),'utf8'),i18n=fs.readFileSync(path.join(root,'assets/i18n.js'),'utf8'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');for(const token of ['skyscraperVisibleSum','skyscraperFamilyValid','skyscrapersums:true','skyscrapermixed:true','skyscrapernontouching:true'])assert.ok(gen.includes(token),token);for(const token of ["kindIs(v,'skyscrapersums')","kindIs(v,'skyscrapermixed')","kindIs(v,'skyscrapernontouching')",'notes[nr][nc].delete'])assert.ok(lib.includes(token),token);for(const token of ["'skyscraper-sums':['Lakótelep összegekkel / Skyscraper Sums'","'skyscraper-mixed':['Vegyes információs Lakótelep / Mixed Information'","'skyscraper-nontouching':['Nem érintkező Lakótelep / Non-touching Skyscraper'",'85 Sudoku-változat','85 Sudoku variants'])assert.ok(i18n.includes(token),token);assert.ok(html.includes('sudoku-bank-iteration14.js'));});
