'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');global.window=global;
for(const f of ['sudoku-bank.js','sudoku-bank-iteration2.js','sudoku-bank-iteration3.js','sudoku-bank-iteration4.js','sudoku-bank-iteration5.js','sudoku-bank-iteration6.js','sudoku-bank-iteration7.js','sudoku-bank-iteration8.js','sudoku-bank-iteration9.js','sudoku-bank-iteration10.js','sudoku-generator.js'])vm.runInThisContext(fs.readFileSync(path.join(root,'games',f),'utf8'));
function lineAt(g,axis,index){return axis==='row'?g[index]:g.map(row=>row[index]);}
function runningCount(line){const used=Array(line.length).fill(false);for(let i=0;i<line.length-1;i++)if(Math.abs(line[i]-line[i+1])===1)used[i]=used[i+1]=true;return used.filter(Boolean).length;}
function ascendingCount(line){let count=0,inRun=false;for(let i=0;i<line.length-1;i++){if(line[i]<line[i+1]){if(!inRun)count++;inRun=true;}else inRun=false;}return count;}
test('iteration 14 expands catalogue from 65 to 67 systems',()=>{assert.equal(SudokuBank.length,67);assert.ok(SudokuBank.find(v=>v.id==='running-cells'));assert.ok(SudokuBank.find(v=>v.id==='ascending-sequences'));});
test('Running Cells exposes exact row and column running-cell counts',()=>{const v=SudokuBank.find(x=>x.id==='running-cells');assert.equal(v.data.clues.length,18);for(const cl of v.data.clues)assert.equal(runningCount(lineAt(v.solution,cl.axis,cl.index)),cl.count,JSON.stringify(cl));});
test('Ascending Sequences exposes exact maximal increasing-run counts',()=>{const v=SudokuBank.find(x=>x.id==='ascending-sequences');assert.equal(v.data.clues.length,18);for(const cl of v.data.clues)assert.equal(ascendingCount(lineAt(v.solution,cl.axis,cl.index)),cl.count,JSON.stringify(cl));});
test('new outside-clue generators are deterministic, unique, and variant-essential',()=>{for(const id of ['running-cells','ascending-sequences']){const v=SudokuBank.find(x=>x.id===id);for(const difficulty of ['gentle','focused','expert'])for(const seed of [5,23,2026]){const a=SudokuGenerator.make(v,seed,difficulty),b=SudokuGenerator.make(v,seed,difficulty);assert.deepEqual(a.puzzle,b.puzzle,id);assert.equal(a.generation.unique,true,id);assert.equal(a.generation.variantEssential,true,id);assert.equal(SudokuGenerator.countVariantSolutions(a.puzzle,v,2),1,id);assert.ok(SudokuGenerator.countSolutions(a.puzzle,2)>1,id+' must require its outside clues');}}});
test('iteration 14 rendering, rotation support, styling, and bilingual copy are wired',()=>{const lib=fs.readFileSync(path.join(root,'games/sudoku-library.js'),'utf8'),css=fs.readFileSync(path.join(root,'assets/styles.css'),'utf8'),i18n=fs.readFileSync(path.join(root,'assets/i18n.js'),'utf8'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');for(const token of ["kindIs(v,'runningcells')","kindIs(v,'ascendingsequences')",'outsideCountConflict','count-clues','rotateAxisIndex'])assert.ok(lib.includes(token),token);assert.ok(css.includes('Iteration 14 — Running Cells + Ascending Sequences'));for(const token of ["'running-cells':['Futó cellák / Running Cells'","'ascending-sequences':['Növekvő sorozatok'",'85 Sudoku-változat','85 Sudoku variants'])assert.ok(i18n.includes(token),token);assert.ok(html.includes('sudoku-bank-iteration10.js'));});
