'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');global.window=global;
for(const f of ['sudoku-bank.js','sudoku-bank-iteration2.js','sudoku-bank-iteration3.js','sudoku-bank-iteration4.js','sudoku-bank-iteration5.js','sudoku-bank-iteration6.js','sudoku-bank-iteration7.js','sudoku-bank-iteration8.js','sudoku-bank-iteration9.js','sudoku-bank-iteration10.js','sudoku-bank-iteration11.js','sudoku-bank-iteration12.js','sudoku-bank-iteration13.js','sudoku-bank-iteration14.js','sudoku-bank-iteration15.js','sudoku-bank-iteration16.js','sudoku-bank-iteration17.js','sudoku-generator.js'])vm.runInThisContext(fs.readFileSync(path.join(root,'games',f),'utf8'));
function line(v,cl){let a=cl.axis==='row'?v.solution[cl.index].slice():v.solution.map(r=>r[cl.index]);if(cl.side==='right'||cl.side==='bottom')a.reverse();return a;}
function visibleCount(a){let m=0,n=0;for(const x of a)if(x>m){m=x;n++;}return n;}
function visibleProduct(a){let m=0,p=1;for(const x of a)if(x>m){m=x;p*=x;}return p;}
test('iteration 21 expands catalogue from 80 to 82 systems',()=>{assert.equal(SudokuBank.length,82);for(const id of ['product-skyscrapers','killer-skyscrapers'])assert.ok(SudokuBank.find(v=>v.id===id),id);});
test('Product Skyscrapers clues equal the product of visible building heights',()=>{const v=SudokuBank.find(x=>x.id==='product-skyscrapers');assert.equal(v.data.clues.length,18);for(const cl of v.data.clues)assert.equal(cl.product,visibleProduct(line(v,cl)),JSON.stringify(cl));});
test('Killer Skyscrapers solution satisfies visibility and every cage',()=>{const v=SudokuBank.find(x=>x.id==='killer-skyscrapers');assert.equal(v.data.clues.length,18);assert.ok(v.data.cages.length>=30);for(const cl of v.data.clues)assert.equal(cl.count,visibleCount(line(v,cl)),JSON.stringify(cl));for(const cage of v.data.cages){const vals=cage.cells.map(p=>v.solution[p[0]][p[1]]);assert.equal(new Set(vals).size,vals.length);assert.equal(vals.reduce((a,b)=>a+b,0),cage.sum);}});
test('new Lakotelep generators are deterministic, unique, and variant-essential',()=>{for(const id of ['product-skyscrapers','killer-skyscrapers']){const v=SudokuBank.find(x=>x.id===id);for(const difficulty of ['gentle','focused','expert'])for(const seed of [21,82,2026]){const a=SudokuGenerator.make(v,seed,difficulty),b=SudokuGenerator.make(v,seed,difficulty);assert.deepEqual(a.puzzle,b.puzzle,id);assert.equal(a.generation.unique,true,id);assert.equal(a.generation.variantEssential,true,id);assert.equal(SudokuGenerator.countVariantSolutions(a.puzzle,a,2),1,id);assert.ok(SudokuGenerator.countSolutions(a.puzzle,2)>1,id+' must require its Lakotelep constraints');}}});
test('iteration 21 solver, cage rendering, clue labels, scripts, and bilingual copy are wired',()=>{const gen=fs.readFileSync(path.join(root,'games/sudoku-generator.js'),'utf8'),lib=fs.readFileSync(path.join(root,'games/sudoku-library.js'),'utf8'),i18n=fs.readFileSync(path.join(root,'assets/i18n.js'),'utf8'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');for(const t of ['skyscraperVisibleProduct','killerCagesValid','skyscraperproduct:true','killerskyscrapers:true'])assert.ok(gen.includes(t),t);for(const t of ["kindIs(v,'skyscraperproduct')","kindIs(v,'killerskyscrapers')",'Π'+"'+cl.product"] )assert.ok(lib.includes(t),t);for(const t of ["'product-skyscrapers':['Szorzatos Lakótelep / Product Skyscrapers'","'killer-skyscrapers':['Killer Lakótelep / Killer Skyscrapers'",'85 Sudoku-változat','85 Sudoku variants'])assert.ok(i18n.includes(t),t);assert.ok(html.includes('sudoku-bank-iteration17.js'));});
