'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
require('../games/sudoku-bank.js');require('../games/sudoku-bank-iteration2.js');require('../games/sudoku-bank-iteration3.js');require('../games/sudoku-bank-iteration4.js');require('../games/sudoku-generator.js');
const bank=global.SudokuBank,gen=global.SudokuGenerator,added=bank.slice(49);const at=(g,p)=>g[p[0]][p[1]];
function normal(g){for(let r=0;r<9;r++){assert.equal(new Set(g[r]).size,9);assert.equal(new Set(g.map(x=>x[r])).size,9);}for(let br=0;br<9;br+=3)for(let bc=0;bc<9;bc+=3){let z=[];for(let r=br;r<br+3;r++)for(let c=bc;c<bc+3;c++)z.push(g[r][c]);assert.equal(new Set(z).size,9);}}
test('iteration 4 expands catalogue from 49 to 54 systems',()=>{assert.equal(bank.length,54);assert.equal(added.length,5);assert.equal(new Set(bank.map(v=>v.id)).size,54);});
test('Miracle solution satisfies anti-knight, anti-king and nonconsecutive rules',()=>{let g=bank.find(v=>v.id==='miracle').solution;normal(g);let K=[[-2,-1],[-2,1],[-1,-2],[-1,2],[1,-2],[1,2],[2,-1],[2,1],[-1,-1],[-1,1],[1,-1],[1,1]];for(let r=0;r<9;r++)for(let c=0;c<9;c++){for(let [dr,dc] of K){let rr=r+dr,cc=c+dc;if(rr>=0&&rr<9&&cc>=0&&cc<9)assert.notEqual(g[r][c],g[rr][cc]);}for(let [dr,dc] of [[1,0],[0,1]]){let rr=r+dr,cc=c+dc;if(rr<9&&cc<9)assert.notEqual(Math.abs(g[r][c]-g[rr][cc]),1);}}});
test('Magic Square centre is a Lo Shu square',()=>{let g=bank.find(v=>v.id==='magic-square').solution,z=g.slice(3,6).map(r=>r.slice(3,6));normal(g);for(let i=0;i<3;i++){assert.equal(z[i].reduce((a,b)=>a+b,0),15);assert.equal(z.map(r=>r[i]).reduce((a,b)=>a+b,0),15);}assert.equal(z[0][0]+z[1][1]+z[2][2],15);assert.equal(z[0][2]+z[1][1]+z[2][0],15);});
test('Asterisk and Argyle extra groups contain no repeats',()=>{for(let id of ['asterisk','argyle']){let v=bank.find(x=>x.id===id),lines=id==='asterisk'?[v.data.cells]:v.data.lines;for(let line of lines){let z=line.map(p=>at(v.solution,p));assert.equal(new Set(z).size,z.length,id);}}});
test('Jigsaw regions are connected nine-cell regions containing 1-9',()=>{let v=bank.find(x=>x.id==='jigsaw'),R=v.data.regions,g=v.solution;for(let k=0;k<9;k++){let cells=[];for(let r=0;r<9;r++)for(let c=0;c<9;c++)if(R[r][c]===k)cells.push([r,c]);assert.equal(cells.length,9);assert.equal(new Set(cells.map(p=>at(g,p))).size,9);let seen=new Set([cells[0].join(',')]),q=[cells[0]];while(q.length){let [r,c]=q.shift();for(let [dr,dc] of [[1,0],[-1,0],[0,1],[0,-1]]){let key=(r+dr)+','+(c+dc);if(R[r+dr]?.[c+dc]===k&&!seen.has(key)){seen.add(key);q.push([r+dr,c+dc]);}}}assert.equal(seen.size,9);}});
test('Jigsaw generator proves uniqueness under irregular regions, not classic boxes',()=>{let v=bank.find(x=>x.id==='jigsaw');for(let seed=1;seed<=12;seed++){let out=gen.make(v,seed,'focused');assert.equal(gen.countJigsawSolutions(out.puzzle,v.data.regions,2),1);}});
