'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');global.window=global;
for(const f of ['sudoku-bank.js','sudoku-bank-iteration2.js','sudoku-bank-iteration3.js','sudoku-bank-iteration4.js','sudoku-bank-iteration5.js','sudoku-bank-iteration6.js','sudoku-bank-iteration7.js','sudoku-bank-iteration8.js','sudoku-bank-iteration9.js','sudoku-bank-iteration10.js','sudoku-bank-iteration11.js','sudoku-bank-iteration12.js','sudoku-bank-iteration13.js','sudoku-bank-iteration14.js','sudoku-bank-iteration15.js','sudoku-bank-iteration16.js','sudoku-bank-iteration17.js','sudoku-bank-iteration18.js','sudoku-generator.js'])vm.runInThisContext(fs.readFileSync(path.join(root,'games',f),'utf8'));
function line(v,cl){let a=cl.axis==='row'?v.solution[cl.index].slice():v.solution.map(r=>r[cl.index]);if(cl.side==='right'||cl.side==='bottom')a.reverse();return a;}
function visibleCount(a){let m=0,n=0;for(const x of a)if(x>m){m=x;n++;}return n;}
test('iteration 22 expands catalogue from 82 to 83 systems',()=>{assert.equal(SudokuBank.length,83);const v=SudokuBank.find(x=>x.id==='domino-skyscrapers');assert.ok(v);assert.equal(v.solution.length,7);});
test('Domino Skyscrapers uses a true 7x7 Latin solution with exact LMI visibility clues',()=>{const v=SudokuBank.find(x=>x.id==='domino-skyscrapers');for(const row of v.solution)assert.deepEqual([...row].sort((a,b)=>a-b),[1,2,3,4,5,6,7]);for(let c=0;c<7;c++)assert.deepEqual(v.solution.map(r=>r[c]).sort((a,b)=>a-b),[1,2,3,4,5,6,7]);for(const cl of v.data.clues)assert.equal(visibleCount(line(v,cl)),cl.count,JSON.stringify(cl));});
test('every marked Domino Skyscrapers domino has the same sum',()=>{const v=SudokuBank.find(x=>x.id==='domino-skyscrapers');const sums=v.data.dominoes.map(dm=>dm.reduce((sum,p)=>sum+v.solution[p[0]][p[1]],0));assert.equal(v.data.dominoes.length,5);assert.equal(new Set(sums).size,1);assert.equal(sums[0],9);});
test('Domino Skyscrapers generator is deterministic, unique, and Latin-variant-essential',()=>{const v=SudokuBank.find(x=>x.id==='domino-skyscrapers');for(const difficulty of ['gentle','focused','expert'])for(const seed of [22,83,2026]){const a=SudokuGenerator.make(v,seed,difficulty),b=SudokuGenerator.make(v,seed,difficulty);assert.deepEqual(a.puzzle,b.puzzle);assert.equal(a.generation.unique,true);assert.equal(a.generation.variantEssential,true);assert.equal(SudokuGenerator.countDominoSkyscraperSolutions(a.puzzle,a,2,false),1);assert.ok(SudokuGenerator.countDominoSkyscraperSolutions(a.puzzle,a,2,true)>1,'Latin rules alone must not be enough');}});
test('iteration 22 Latin UI, domino rendering, scripts, and bilingual copy are wired',()=>{const gen=fs.readFileSync(path.join(root,'games/sudoku-generator.js'),'utf8'),lib=fs.readFileSync(path.join(root,'games/sudoku-library.js'),'utf8'),css=fs.readFileSync(path.join(root,'assets/styles.css'),'utf8'),i18n=fs.readFileSync(path.join(root,'assets/i18n.js'),'utf8'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');for(const t of ['countDominoSkyscraperSolutions','makeDominoSkyscraperPuzzle',"variant.kind==='dominoskyscrapers'"])assert.ok(gen.includes(t),t);for(const t of ["kindIs(vdef,'dominoskyscrapers')","b.classList.add('domino-cell')","kindIs(v,'dominoskyscrapers')"])assert.ok(lib.includes(t),t);assert.ok(css.includes('Iteration 22 — Domino Skyscrapers'));assert.ok(i18n.includes("'domino-skyscrapers':['Dominó Lakótelep / Domino Skyscrapers'"));assert.ok(i18n.includes('85 Sudoku variants'));assert.ok(html.includes('sudoku-bank-iteration18.js'));});
