'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');global.window=global;
for(const f of ['sudoku-bank.js','sudoku-bank-iteration2.js','sudoku-bank-iteration3.js','sudoku-bank-iteration4.js','sudoku-bank-iteration5.js','sudoku-bank-iteration6.js','sudoku-bank-iteration7.js','sudoku-bank-iteration8.js','sudoku-bank-iteration9.js','sudoku-bank-iteration10.js','sudoku-bank-iteration11.js','sudoku-bank-iteration12.js','sudoku-bank-iteration13.js','sudoku-bank-iteration14.js','sudoku-bank-iteration15.js','sudoku-bank-iteration16.js','sudoku-generator.js'])vm.runInThisContext(fs.readFileSync(path.join(root,'games',f),'utf8'));
function visible(a){let m=0,n=0;for(const x of a)if(x>m){m=x;n++;}return n;}
test('iteration 20 expands catalogue from 78 to 80 systems',()=>{assert.equal(SudokuBank.length,80);for(const id of ['inside-skyscrapers','diagonal-skyscrapers'])assert.ok(SudokuBank.find(v=>v.id===id),id);});
test('Inside Skyscrapers arrow cells equal visibility from the next cell to the edge',()=>{const v=SudokuBank.find(x=>x.id==='inside-skyscrapers');assert.ok(v.data.sightClues.length>=10);for(const cl of v.data.sightClues)assert.equal(v.solution[cl.source[0]][cl.source[1]],visible(cl.cells.map(p=>v.solution[p[0]][p[1]])),JSON.stringify(cl));});
test('Diagonal Skyscraper outside clues match their diagonal sightlines',()=>{const v=SudokuBank.find(x=>x.id==='diagonal-skyscrapers');assert.ok(v.data.sightClues.length>=20);for(const cl of v.data.sightClues)assert.equal(cl.count,visible(cl.cells.map(p=>v.solution[p[0]][p[1]])),JSON.stringify(cl));});
test('new Lakotelep generators are deterministic, unique, and variant-essential',()=>{for(const id of ['inside-skyscrapers','diagonal-skyscrapers']){const v=SudokuBank.find(x=>x.id===id);for(const difficulty of ['gentle','focused','expert'])for(const seed of [20,80,2026]){const a=SudokuGenerator.make(v,seed,difficulty),b=SudokuGenerator.make(v,seed,difficulty);assert.deepEqual(a.puzzle,b.puzzle,id);assert.equal(a.generation.unique,true,id);assert.equal(a.generation.variantEssential,true,id);assert.equal(SudokuGenerator.countVariantSolutions(a.puzzle,a,2),1,id);assert.ok(SudokuGenerator.countSolutions(a.puzzle,2)>1,id+' must require its sightline rules');}}});
test('iteration 20 solver, rotation, markers, scripts, and bilingual copy are wired',()=>{const gen=fs.readFileSync(path.join(root,'games/sudoku-generator.js'),'utf8'),lib=fs.readFileSync(path.join(root,'games/sudoku-library.js'),'utf8'),css=fs.readFileSync(path.join(root,'assets/styles.css'),'utf8'),i18n=fs.readFileSync(path.join(root,'assets/i18n.js'),'utf8'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');for(const t of ['sightClueIndexCache','sightlineValid','insideskyscrapers:true','diagonalskyscrapers:true'])assert.ok(gen.includes(t),t);for(const t of ['sightlineConflict','sudoku-inside-sky-marker','sudoku-diagonal-sky-marker','d.sightClues'])assert.ok(lib.includes(t),t);assert.ok(css.includes('Iteration 20 — Inside + Diagonal Skyscrapers'));for(const t of ["'inside-skyscrapers':['Belső Lakótelep / Inside Skyscrapers'","'diagonal-skyscrapers':['Átlós Lakótelep / Diagonal Skyscraper'",'85 Sudoku-változat','85 Sudoku variants'])assert.ok(i18n.includes(t),t);assert.ok(html.includes('sudoku-bank-iteration16.js'));});
