'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');global.window=global;
for(const f of ['sudoku-bank.js','sudoku-bank-iteration2.js','sudoku-bank-iteration3.js','sudoku-bank-iteration4.js','sudoku-bank-iteration5.js','sudoku-bank-iteration6.js','sudoku-bank-iteration7.js','sudoku-generator.js'])vm.runInThisContext(fs.readFileSync(path.join(root,'games',f),'utf8'));
function checker(g,r,c){const v=[g[r-1][c-1],g[r-1][c],g[r][c-1],g[r][c]];return v[0]%2===v[3]%2&&v[1]%2===v[2]%2&&v[0]%2!==v[1]%2;}
test('iteration 7 expands catalogue from 60 to 61 systems',()=>{assert.equal(SudokuBank.length,61);assert.ok(SudokuBank.find(v=>v.id==='battenburg'));});
test('Battenburg solution exposes every and only odd/even checkerboard intersection',()=>{const v=SudokuBank.find(x=>x.id==='battenburg'),marked=new Set(v.data.battenburg.map(p=>p.join(',')));let total=0;for(let r=1;r<9;r++)for(let c=1;c<9;c++){const is=checker(v.solution,r,c);if(is)total++;assert.equal(marked.has(r+','+c),is,'intersection '+r+','+c);}assert.equal(marked.size,total);assert.ok(total>0);});
test('Battenburg generator is reproducible, variant-unique, and variant-essential',()=>{const v=SudokuBank.find(x=>x.id==='battenburg');for(const difficulty of ['gentle','focused','expert'])for(const seed of [3,29]){const a=SudokuGenerator.make(v,seed,difficulty),b=SudokuGenerator.make(v,seed,difficulty);assert.deepEqual(a.puzzle,b.puzzle);assert.equal(a.generation.unique,true);assert.equal(a.generation.variantEssential,true);assert.equal(SudokuGenerator.countVariantSolutions(a.puzzle,v,2),1);assert.ok(SudokuGenerator.countSolutions(a.puzzle,2)>1);}});
test('pencil-note interaction is wired for buttons, keyboard, ARIA, and visual small-number grid',()=>{const lib=fs.readFileSync(path.join(root,'games/sudoku-library.js'),'utf8'),css=fs.readFileSync(path.join(root,'assets/styles.css'),'utf8'),i18n=fs.readFileSync(path.join(root,'assets/i18n.js'),'utf8');for(const token of ['noteMode','toggleNote','clearCell','aria-pressed','sudoku-notes','e.key===\'n\''])assert.ok(lib.includes(token),token);for(const token of ['.sudoku-notes','.sudoku-note.on','.note-mode-button.active'])assert.ok(css.includes(token),token);for(const token of ["notes:'Jegyzet'","notes:'Notes'","noteMark:'jegyzet'","noteMark:'note'"])assert.ok(i18n.includes(token),token);});
