'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');global.window=global;
for(const f of ['sudoku-bank.js','sudoku-bank-iteration2.js','sudoku-bank-iteration3.js','sudoku-bank-iteration4.js','sudoku-bank-iteration5.js','sudoku-bank-iteration6.js','sudoku-bank-iteration7.js','sudoku-bank-iteration8.js','sudoku-bank-iteration9.js','sudoku-bank-iteration10.js','sudoku-bank-iteration11.js','sudoku-bank-iteration12.js','sudoku-bank-iteration13.js','sudoku-bank-iteration14.js','sudoku-bank-iteration15.js','sudoku-bank-iteration16.js','sudoku-bank-iteration17.js','sudoku-bank-iteration18.js','sudoku-bank-iteration19.js','sudoku-bank-iteration20.js','sudoku-generator.js'])vm.runInThisContext(fs.readFileSync(path.join(root,'games',f),'utf8'));
function line(v,cl){let a=cl.axis==='row'?v.solution[cl.index].slice():v.solution.map(r=>r[cl.index]);if(cl.side==='right'||cl.side==='bottom')a.reverse();return a;}
function visible(a){let m=0,n=0;for(const x of a)if(x>m){m=x;n++;}return n;}
test('iteration 24 expands catalogue from 84 to 85 systems',()=>{assert.equal(SudokuBank.length,85);const v=SudokuBank.find(x=>x.id==='evenodd-skyscrapers');assert.ok(v);assert.equal(v.solution.length,6);assert.equal(v.data.clues.length,24);assert.equal(v.data.parityCells.length,36);});
test('Even/Odd Skyscrapers solution is a 1-6 Latin square and every cell parity marker is correct',()=>{const v=SudokuBank.find(x=>x.id==='evenodd-skyscrapers');for(let i=0;i<6;i++){assert.deepEqual([...v.solution[i]].sort(),[1,2,3,4,5,6]);assert.deepEqual(v.solution.map(r=>r[i]).sort(),[1,2,3,4,5,6]);}for(const p of v.data.parityCells){const x=v.solution[p.cell[0]][p.cell[1]];assert.equal(x%2?'odd':'even',p.parity);}});
test('outside Even/Odd markers match visibility-count parity',()=>{const v=SudokuBank.find(x=>x.id==='evenodd-skyscrapers');for(const cl of v.data.clues)assert.equal(visible(line(v,cl))%2?'odd':'even',cl.parity,JSON.stringify(cl));});
test('Even/Odd generator is deterministic, unique, and special-clue-essential',()=>{const v=SudokuBank.find(x=>x.id==='evenodd-skyscrapers');for(const difficulty of ['gentle','focused','expert'])for(const seed of [24,85,2026]){const a=SudokuGenerator.make(v,seed,difficulty),b=SudokuGenerator.make(v,seed,difficulty);assert.deepEqual(a.puzzle,b.puzzle);assert.equal(a.generation.unique,true);assert.equal(a.generation.variantEssential,true);assert.equal(SudokuGenerator.countEvenOddSkyscraperSolutions(a.puzzle,a,2,false),1);assert.ok(SudokuGenerator.countEvenOddSkyscraperSolutions(a.puzzle,a,2,true)>1);}});
test('Lakótelepek category and Even/Odd UI are bilingual and wired',()=>{const lib=fs.readFileSync(path.join(root,'games/sudoku-library.js'),'utf8'),i18n=fs.readFileSync(path.join(root,'assets/i18n.js'),'utf8'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');for(const t of ["id:'skyscrapers'","hu:'Lakótelepek'","en:'Skyscrapers'","'evenodd-skyscrapers'","kindIs(v,'evenoddskyscrapers')","parityCells"])assert.ok(lib.includes(t),t);assert.ok(i18n.includes("'evenodd-skyscrapers':['Páros–páratlan Lakótelep / Skyscrapers (Even/Odd)'"));assert.ok(i18n.includes('85 Sudoku variants'));assert.ok(html.includes('sudoku-bank-iteration20.js'));});
