'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');global.window=global;
for(const f of ['sudoku-bank.js','sudoku-bank-iteration2.js','sudoku-bank-iteration3.js','sudoku-bank-iteration4.js','sudoku-bank-iteration5.js','sudoku-bank-iteration6.js','sudoku-bank-iteration7.js','sudoku-bank-iteration8.js','sudoku-bank-iteration9.js','sudoku-bank-iteration10.js','sudoku-bank-iteration11.js','sudoku-bank-iteration12.js','sudoku-generator.js'])vm.runInThisContext(fs.readFileSync(path.join(root,'games',f),'utf8'));
function line(v,cl){let a=cl.axis==='row'?v.solution[cl.index].slice():v.solution.map(r=>r[cl.index]);if(cl.side==='right'||cl.side==='bottom')a.reverse();return a;}
test('iteration 16 expands catalogue from 69 to 71 systems',()=>{assert.equal(SudokuBank.length,71);assert.ok(SudokuBank.find(v=>v.id==='numbered-rooms'));assert.ok(SudokuBank.find(v=>v.id==='next-to-nine'));});
test('Numbered Rooms clues exactly match first-cell indexed positions',()=>{const v=SudokuBank.find(x=>x.id==='numbered-rooms');assert.equal(v.data.clues.length,36);for(const cl of v.data.clues){const a=line(v,cl),n=a[0];assert.equal(a[n-1],cl.digit,JSON.stringify(cl));}});
test('Next to Nine clues list all and only direct neighbours of 9',()=>{const v=SudokuBank.find(x=>x.id==='next-to-nine');assert.equal(v.data.clues.length,18);for(const cl of v.data.clues){const a=line(v,cl),p=a.indexOf(9),want=[];if(p>0)want.push(a[p-1]);if(p<8)want.push(a[p+1]);want.sort((x,y)=>x-y);assert.deepEqual(cl.digits,want,JSON.stringify(cl));}});
test('new outside-clue generators are deterministic, unique, and variant-essential',()=>{for(const id of ['numbered-rooms','next-to-nine']){const v=SudokuBank.find(x=>x.id===id);for(const difficulty of ['gentle','focused','expert'])for(const seed of [11,71,2026]){const a=SudokuGenerator.make(v,seed,difficulty),b=SudokuGenerator.make(v,seed,difficulty);assert.deepEqual(a.puzzle,b.puzzle,id);assert.equal(a.generation.unique,true,id);assert.equal(a.generation.variantEssential,true,id);assert.equal(SudokuGenerator.countVariantSolutions(a.puzzle,v,2),1,id);assert.ok(SudokuGenerator.countSolutions(a.puzzle,2)>1,id+' must require its outside clue rule');}}});
test('iteration 16 shared outside-clue index, rendering, scripts, and bilingual copy are wired',()=>{const gen=fs.readFileSync(path.join(root,'games/sudoku-generator.js'),'utf8'),lib=fs.readFileSync(path.join(root,'games/sudoku-library.js'),'utf8'),i18n=fs.readFileSync(path.join(root,'assets/i18n.js'),'utf8'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');for(const token of ['outsideClueIndexCache','affectedOutsideClues','numberedRoomsValid','nextToNineValid'])assert.ok(gen.includes(token),token);for(const token of ["kindIs(v,'numberedrooms')","kindIs(v,'nexttonine')",'cl.digit','cl.digits.join'])assert.ok(lib.includes(token),token);for(const token of ["'numbered-rooms':['Számozott szobák / Numbered Rooms'","'next-to-nine':['A kilences mellett / Next to Nine'",'85 Sudoku-változat','85 Sudoku variants'])assert.ok(i18n.includes(token),token);assert.ok(html.includes('sudoku-bank-iteration12.js'));});
