'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');global.window=global;
for(const f of ['sudoku-bank.js','sudoku-bank-iteration2.js','sudoku-bank-iteration3.js','sudoku-bank-iteration4.js','sudoku-bank-iteration5.js','sudoku-bank-iteration6.js','sudoku-bank-iteration7.js','sudoku-bank-iteration8.js','sudoku-bank-iteration9.js','sudoku-bank-iteration10.js','sudoku-bank-iteration11.js','sudoku-bank-iteration12.js','sudoku-bank-iteration13.js','sudoku-generator.js','iteration13-generator-hardening.js'])vm.runInThisContext(fs.readFileSync(path.join(root,'games',f),'utf8'));
function line(v,cl){return cl.axis==='row'?v.solution[cl.index].slice():v.solution.map(r=>r[cl.index]);}
function evenSandwichDigits(a){const out=[];for(let i=1;i<a.length-1;i++)if(a[i-1]%2===0&&a[i+1]%2===0)out.push(a[i]);return out.sort((x,y)=>x-y);}
function assertTopHeavyGrid(grid,label){for(let r=0;r<8;r++)for(let c=0;c<9;c++){const a=grid[r][c],b=grid[r+1][c];if(a&&b&&a%2===b%2)assert.ok(a>b,`${label}: R${r+1}C${c+1}=${a} must be > R${r+2}C${c+1}=${b}`);}}
function assertPuzzleMatchesSolution(puzzle,solution,label){for(let r=0;r<9;r++)for(let c=0;c<9;c++)if(puzzle[r][c])assert.equal(puzzle[r][c],solution[r][c],`${label}: R${r+1}C${c+1}`);}
test('iteration 17 expands catalogue from 71 to 73 systems',()=>{assert.equal(SudokuBank.length,73);assert.ok(SudokuBank.find(v=>v.id==='even-sandwich'));assert.ok(SudokuBank.find(v=>v.id==='top-heavy-parity'));});
test('Even Sandwich clues expose every and only digit enclosed by even neighbours',()=>{const v=SudokuBank.find(x=>x.id==='even-sandwich');assert.equal(v.data.clues.length,18);for(const cl of v.data.clues)assert.deepEqual(cl.digits,evenSandwichDigits(line(v,cl)),JSON.stringify(cl));});
test('Top-Heavy Parity solution obeys every vertical same-parity ordering',()=>{const v=SudokuBank.find(x=>x.id==='top-heavy-parity');assertTopHeavyGrid(v.solution,'catalogue solution');});
test('new production generators are deterministic, unique, and variant-essential at all difficulties',()=>{for(const id of ['even-sandwich','top-heavy-parity']){const v=SudokuBank.find(x=>x.id===id);for(const difficulty of ['gentle','focused','expert'])for(const seed of [17,73,2026]){const a=SudokuGenerator.make(v,seed,difficulty),b=SudokuGenerator.make(v,seed,difficulty);assert.deepEqual(a.puzzle,b.puzzle,id);assert.equal(a.generation.unique,true,id);assert.equal(a.generation.variantEssential,true,id);assert.equal(SudokuGenerator.countVariantSolutions(a.puzzle,a,2),1,id);assert.ok(SudokuGenerator.countSolutions(a.puzzle,2)>1,id+' must require its variant rule');if(id==='top-heavy-parity'){assertTopHeavyGrid(a.solution,`${id} solution seed ${seed}`);assertTopHeavyGrid(a.puzzle,`${id} givens seed ${seed}`);assertPuzzleMatchesSolution(a.puzzle,a.solution,`${id} seed ${seed}`);assert.equal(a.generation.generatorFamily,'top-heavy-parity-fresh-constrained-solution');}}}});
test('Top-Heavy screenshot regression seed 1859712027 stays valid on the production hardening path',()=>{const v=SudokuBank.find(x=>x.id==='top-heavy-parity'),out=SudokuGenerator.make(v,1859712027,'focused');assert.equal(out.generation.seed,1859712027);assert.equal(out.generation.generatorFamily,'top-heavy-parity-fresh-constrained-solution');assert.equal(out.generation.unique,true);assert.equal(out.generation.variantEssential,true);assertTopHeavyGrid(out.solution,'screenshot-seed solution');assertTopHeavyGrid(out.puzzle,'screenshot-seed givens');assertPuzzleMatchesSolution(out.puzzle,out.solution,'screenshot-seed givens');assert.equal(SudokuGenerator.countVariantSolutions(out.puzzle,out,2),1);assert.ok(SudokuGenerator.countSolutions(out.puzzle,2)>1);});
test('Sudoku UI uses generated boards directly with no legacy rotation layer',()=>{const lib=fs.readFileSync(path.join(root,'games/sudoku-library.js'),'utf8');assert.ok(lib.includes('var v=generated,vt=I?I.variant(v):v;'),'renderVariant must pass the generated board through unchanged');assert.ok(!lib.includes('transformedVariant('),'legacy transformedVariant helper must be removed');assert.ok(!lib.includes('turns=api.seed%4'),'legacy seed-based UI turns must be removed');});
test('iteration 17 solver, note cleanup, rendering, scripts, and bilingual copy are wired',()=>{const gen=fs.readFileSync(path.join(root,'games/sudoku-generator.js'),'utf8'),hard=fs.readFileSync(path.join(root,'games/iteration13-generator-hardening.js'),'utf8'),lib=fs.readFileSync(path.join(root,'games/sudoku-library.js'),'utf8'),i18n=fs.readFileSync(path.join(root,'assets/i18n.js'),'utf8'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');for(const token of ['evenSandwichValid',"variant.kind==='topheavyparity'",'evensandwich:true','topheavyparity:true'])assert.ok(gen.includes(token),token);for(const token of ['topHeavySolution','makeTopHeavy','top-heavy-parity-fresh-constrained-solution'])assert.ok(hard.includes(token),token);for(const token of ["kindIs(v,'evensandwich')","kindIs(v,'topheavyparity')",'notes[r-1][c].delete','cl.digits.length'])assert.ok(lib.includes(token),token);for(const token of ["'even-sandwich':['Páros szendvics / Even Sandwich'","'top-heavy-parity':['Felül nehéz paritás / Top-Heavy Parity'",'85 Sudoku-változat','85 Sudoku variants'])assert.ok(i18n.includes(token),token);assert.ok(html.includes('sudoku-bank-iteration13.js'));assert.ok(html.includes('iteration13-generator-hardening.js'));});
