'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');global.window=global;
for(const f of ['sudoku-bank.js','sudoku-bank-iteration2.js','sudoku-bank-iteration3.js','sudoku-bank-iteration4.js','sudoku-bank-iteration5.js','sudoku-bank-iteration6.js','sudoku-bank-iteration7.js','sudoku-bank-iteration8.js','sudoku-bank-iteration9.js','sudoku-bank-iteration10.js','sudoku-bank-iteration11.js','sudoku-bank-iteration12.js','sudoku-bank-iteration13.js','sudoku-bank-iteration14.js','sudoku-bank-iteration15.js','sudoku-bank-iteration16.js','sudoku-bank-iteration17.js','sudoku-bank-iteration18.js','sudoku-bank-iteration19.js','sudoku-generator.js'])vm.runInThisContext(fs.readFileSync(path.join(root,'games',f),'utf8'));
function line(v,cl){let a=cl.axis==='row'?v.solution[cl.index].slice():v.solution.map(r=>r[cl.index]);if(cl.side==='right'||cl.side==='bottom')a.reverse();return a;}
function visibleCount(a,park){let m=0,n=0;for(const x of a){if(x===park)continue;if(x>m){m=x;n++;}}return n;}
test('iteration 23 expands catalogue from 83 to 84 systems',()=>{assert.equal(SudokuBank.length,84);const v=SudokuBank.find(x=>x.id==='skyscraper-parks2');assert.ok(v);assert.equal(v.solution.length,8);assert.equal(v.data.maxDigit,6);assert.equal(v.data.parksPerLine,2);});
test('Skyscrapers Parks 2 has 1-6 once plus exactly two parks in every row and column',()=>{const v=SudokuBank.find(x=>x.id==='skyscraper-parks2'),park=v.data.parkValue;for(let i=0;i<8;i++){const row=v.solution[i],col=v.solution.map(r=>r[i]);for(const seq of [row,col]){assert.equal(seq.filter(x=>x===park).length,2);for(let d=1;d<=6;d++)assert.equal(seq.filter(x=>x===d).length,1);}}});
test('Parks 2 visibility clues ignore both parks and match the completed solution',()=>{const v=SudokuBank.find(x=>x.id==='skyscraper-parks2');assert.equal(v.data.clues.length,32);for(const cl of v.data.clues)assert.equal(visibleCount(line(v,cl),v.data.parkValue),cl.count,JSON.stringify(cl));});
test('Parks 2 generator is deterministic, unique, and outside-clue-essential',()=>{const v=SudokuBank.find(x=>x.id==='skyscraper-parks2');for(const difficulty of ['gentle','focused','expert'])for(const seed of [23,84,2026]){const a=SudokuGenerator.make(v,seed,difficulty),b=SudokuGenerator.make(v,seed,difficulty);assert.deepEqual(a.puzzle,b.puzzle);assert.equal(a.generation.unique,true);assert.equal(a.generation.variantEssential,true);assert.equal(SudokuGenerator.countParks2Solutions(a.puzzle,a,2,false),1);assert.ok(SudokuGenerator.countParks2Solutions(a.puzzle,a,2,true)>1);}});
test('Parks 2 UI supports one park symbol twice, 8x8 Latin layout, notes, scripts, and bilingual copy',()=>{const gen=fs.readFileSync(path.join(root,'games/sudoku-generator.js'),'utf8'),lib=fs.readFileSync(path.join(root,'games/sudoku-library.js'),'utf8'),i18n=fs.readFileSync(path.join(root,'assets/i18n.js'),'utf8'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');for(const t of ['countParks2Solutions','makeParks2Puzzle',"variant.kind==='skyscraperparks2'"])assert.ok(gen.includes(t),t);for(const t of ["kindIs(vdef,'skyscraperparks2')",'parksPerLine','inputMax',"kindIs(v,'skyscraperparks2')&&v.data&&val===v.data.parkValue"])assert.ok(lib.includes(t),t);assert.ok(i18n.includes("'skyscraper-parks2':['Lakótelep – két grunddal / Skyscrapers Parks 2'"));assert.ok(i18n.includes('85 Sudoku variants'));assert.ok(html.includes('sudoku-bank-iteration19.js'));});
