'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
require('../games/sudoku-bank.js');require('../games/sudoku-bank-iteration2.js');require('../games/sudoku-bank-iteration3.js');require('../games/sudoku-bank-iteration4.js');require('../games/sudoku-bank-iteration5.js');require('../games/sudoku-generator.js');
const bank=global.SudokuBank,gen=global.SudokuGenerator;
function validGrid(g,bh,bw){const n=g.length,want=new Set(Array.from({length:n},(_,i)=>i+1));for(let r=0;r<n;r++)assert.deepEqual(new Set(g[r]),want);for(let c=0;c<n;c++)assert.deepEqual(new Set(g.map(row=>row[c])),want);for(let br=0;br<n;br+=bh)for(let bc=0;bc<n;bc+=bw){let z=[];for(let r=br;r<br+bh;r++)for(let c=bc;c<bc+bw;c++)z.push(g[r][c]);assert.deepEqual(new Set(z),want);}}
test('iteration 5 expands catalogue from 54 to 58 systems',()=>{assert.equal(bank.length,58);for(const id of ['sudoku-12x12','sudoku-16x16','sukaku','samurai'])assert.ok(bank.find(v=>v.id===id));});
test('12x12 and 16x16 solutions obey rectangular-box Sudoku rules',()=>{validGrid(bank.find(v=>v.id==='sudoku-12x12').solution,3,4);validGrid(bank.find(v=>v.id==='sudoku-16x16').solution,4,4);});
test('large-grid generator creates seeded uniqueness-proven boards with separated difficulty',()=>{for(const id of ['sudoku-12x12','sudoku-16x16']){const v=bank.find(x=>x.id===id),clues=[];for(const d of ['gentle','focused','expert']){const out=gen.make(v,12345,d);assert.equal(out.generation.unique,true,id+' '+d);assert.equal(gen.countSolutions(out.puzzle,2),1,id+' '+d);validGrid(out.solution,id==='sudoku-12x12'?3:4,id==='sudoku-12x12'?4:4);clues.push(out.generation.clues);}assert.ok(clues[0]>clues[1]&&clues[1]>clues[2],id+' difficulty clue separation');}});
test('Sukaku generation exposes candidate sets compatible with the unique solution',()=>{const v=bank.find(x=>x.id==='sukaku'),out=gen.make(v,98765,'focused');assert.equal(out.data.candidates.length,9);assert.equal(out.puzzle.flat().filter(Boolean).length,0);assert.equal(gen.countSolutions(out.data.sourcePuzzle,2),1);for(let r=0;r<9;r++)for(let c=0;c<9;c++)assert.ok(out.data.candidates[r][c].includes(out.solution[r][c]),`candidate ${r},${c}`);});
test('Samurai generator creates five valid overlapping grids with one coherent solution',()=>{const v=bank.find(x=>x.id==='samurai'),out=gen.make(v,424242,'focused');assert.equal(out.solution.length,21);assert.equal(out.data.grids.length,5);let active=0;for(let r=0;r<21;r++)for(let c=0;c<21;c++)if(out.data.active[r][c])active++;assert.equal(active,369);for(const gd of out.data.grids){let sub=[];for(let r=0;r<9;r++)sub.push(out.solution[gd.off[0]+r].slice(gd.off[1],gd.off[1]+9));validGrid(sub,3,3);}assert.equal(out.generation.unique,true);});
