(function(root){'use strict';
  var FULL_MASK=0x1ff;

  var FAMILY_IDS=Object.freeze({completion:'completion',intersection:'intersection',subset:'subset',fish:'fish',singleDigitPattern:'single-digit-pattern',wing:'wing',coloring:'coloring',uniqueness:'uniqueness',chain:'chain',als:'als',exocet:'exocet',rank:'rank',forcing:'forcing',dynamicForcing:'dynamic-forcing'});

  var TECHNIQUES=Object.freeze({
    'full-house':{familyId:FAMILY_IDS.completion,baseRating:1.0,priority:10},'naked-single':{familyId:FAMILY_IDS.completion,baseRating:1.2,priority:20},'hidden-single':{familyId:FAMILY_IDS.completion,baseRating:1.5,priority:30},
    'locked-candidate-pointing':{familyId:FAMILY_IDS.intersection,baseRating:2.6,priority:40},'locked-candidate-claiming':{familyId:FAMILY_IDS.intersection,baseRating:2.8,priority:50},
    'naked-pair':{familyId:FAMILY_IDS.subset,baseRating:3.0,priority:60},'hidden-pair':{familyId:FAMILY_IDS.subset,baseRating:3.4,priority:70},'naked-triple':{familyId:FAMILY_IDS.subset,baseRating:3.6,priority:80},'hidden-triple':{familyId:FAMILY_IDS.subset,baseRating:4.0,priority:90},
    'x-wing':{familyId:FAMILY_IDS.fish,baseRating:3.2,priority:100},'skyscraper':{familyId:FAMILY_IDS.singleDigitPattern,baseRating:4.0,priority:110},'two-string-kite':{familyId:FAMILY_IDS.singleDigitPattern,baseRating:4.1,priority:120},'turbot-fish':{familyId:FAMILY_IDS.singleDigitPattern,baseRating:4.1,priority:130},'empty-rectangle':{familyId:FAMILY_IDS.singleDigitPattern,baseRating:4.2,priority:140},
    'xy-wing':{familyId:FAMILY_IDS.wing,baseRating:4.2,priority:150},'xyz-wing':{familyId:FAMILY_IDS.wing,baseRating:4.4,priority:160},'w-wing':{familyId:FAMILY_IDS.wing,baseRating:4.5,priority:170},'swordfish':{familyId:FAMILY_IDS.fish,baseRating:4.5,priority:180},
    'naked-quad':{familyId:FAMILY_IDS.subset,baseRating:5.0,priority:190},'hidden-quad':{familyId:FAMILY_IDS.subset,baseRating:5.4,priority:200},'simple-coloring':{familyId:FAMILY_IDS.coloring,baseRating:5.0,priority:210},'multi-coloring':{familyId:FAMILY_IDS.coloring,baseRating:5.5,priority:220},
    'unique-rectangle':{familyId:FAMILY_IDS.uniqueness,baseRating:4.5,priority:230,requiresUniqueness:true},'unique-loop':{familyId:FAMILY_IDS.uniqueness,baseRating:5.0,priority:240,requiresUniqueness:true},'bug-plus-one':{familyId:FAMILY_IDS.uniqueness,baseRating:5.6,priority:250,requiresUniqueness:true},'jellyfish':{familyId:FAMILY_IDS.fish,baseRating:5.2,priority:260},
    'finned-x-wing':{familyId:FAMILY_IDS.fish,baseRating:4.6,priority:270},'sashimi-x-wing':{familyId:FAMILY_IDS.fish,baseRating:4.8,priority:271},'finned-swordfish':{familyId:FAMILY_IDS.fish,baseRating:5.2,priority:272},'sashimi-swordfish':{familyId:FAMILY_IDS.fish,baseRating:5.4,priority:273},'finned-jellyfish':{familyId:FAMILY_IDS.fish,baseRating:5.8,priority:274},'sashimi-jellyfish':{familyId:FAMILY_IDS.fish,baseRating:6.0,priority:275},
    'x-chain':{familyId:FAMILY_IDS.chain,baseRating:6.5,priority:300},'xy-chain':{familyId:FAMILY_IDS.chain,baseRating:6.6,priority:310},'aic':{familyId:FAMILY_IDS.chain,baseRating:7.0,priority:320},'grouped-aic':{familyId:FAMILY_IDS.chain,baseRating:7.5,priority:330},
    'sue-de-coq':{familyId:FAMILY_IDS.als,baseRating:7.3,priority:340},'als-xz':{familyId:FAMILY_IDS.als,baseRating:7.4,priority:350},'als-xy-wing':{familyId:FAMILY_IDS.als,baseRating:7.6,priority:360},'als-chain':{familyId:FAMILY_IDS.als,baseRating:8.0,priority:370},'aligned-pair-exclusion':{familyId:FAMILY_IDS.als,baseRating:8.2,priority:375,serverPreferred:true,implementationStatus:'IMPLEMENTED_UNWIRED',auditStatus:'NEEDS_FIX',productionTrusted:false},'death-blossom':{familyId:FAMILY_IDS.als,baseRating:8.8,priority:380,serverPreferred:true},
    'forcing-chain':{familyId:FAMILY_IDS.forcing,baseRating:8.0,priority:400,serverPreferred:true},'forcing-net':{familyId:FAMILY_IDS.forcing,baseRating:8.5,priority:410,serverPreferred:true},'digit-forcing-chain':{familyId:FAMILY_IDS.forcing,baseRating:8.6,priority:420,serverPreferred:true},'digit-forcing-net':{familyId:FAMILY_IDS.forcing,baseRating:8.9,priority:430,serverPreferred:true},'junior-exocet':{familyId:FAMILY_IDS.exocet,baseRating:9.2,priority:440,serverPreferred:true},'multi-sector-locked-set':{familyId:FAMILY_IDS.rank,baseRating:9.3,priority:450,serverPreferred:true,implementationStatus:'WIRED',auditStatus:'VERIFIED',productionTrusted:true},'dynamic-forcing-chain':{familyId:FAMILY_IDS.dynamicForcing,baseRating:9.0,priority:500,serverOnly:true},'nested-forcing-chain':{familyId:FAMILY_IDS.dynamicForcing,baseRating:9.8,priority:510,serverOnly:true}
  });

  function bitForDigit(digit){if(!Number.isInteger(digit)||digit<1||digit>9)throw new RangeError('digit must be 1..9');return 1<<(digit-1);}
  function bitCount(mask){var n=0;for(mask&=FULL_MASK;mask;mask&=mask-1)n++;return n;}
  function digitsFromMask(mask){var out=[];for(var d=1;d<=9;d++)if(mask&bitForDigit(d))out.push(d);return out;}
  function boxIndex(row,col){return Math.floor(row/3)*3+Math.floor(col/3);}
  function cellIndex(row,col){return row*9+col;}
  function rowCol(index){return [Math.floor(index/9),index%9];}
  function parseGrid(source){if(typeof source==='string'){if(source.length!==81||!/^[0-9.]+$/.test(source))throw new TypeError('classic grid string must contain 81 digits/dots');return Array.from({length:9},function(_,r){return Array.from({length:9},function(__,c){var ch=source[r*9+c];return ch==='.'?0:Number(ch);});});}if(!Array.isArray(source)||source.length!==9||source.some(function(row){return !Array.isArray(row)||row.length!==9;}))throw new TypeError('classic grid must be 9x9');return source.map(function(row){return row.map(function(v){if(!Number.isInteger(v)||v<0||v>9)throw new TypeError('classic grid values must be 0..9');return v;});});}
  function ClassicCandidateState(source){this.grid=parseGrid(source);this.rowUsed=new Uint16Array(9);this.colUsed=new Uint16Array(9);this.boxUsed=new Uint16Array(9);this.masks=new Uint16Array(81);this.valid=true;for(var r=0;r<9;r++)for(var c=0;c<9;c++){var v=this.grid[r][c];if(!v)continue;var bit=bitForDigit(v),b=boxIndex(r,c);if((this.rowUsed[r]&bit)||(this.colUsed[c]&bit)||(this.boxUsed[b]&bit)){this.valid=false;return;}this.rowUsed[r]|=bit;this.colUsed[c]|=bit;this.boxUsed[b]|=bit;}this.rebuildCandidates();}
  ClassicCandidateState.prototype.rebuildCandidates=function(){if(!this.valid)return false;for(var r=0;r<9;r++)for(var c=0;c<9;c++){var idx=cellIndex(r,c),v=this.grid[r][c];if(v){this.masks[idx]=bitForDigit(v);continue;}var mask=FULL_MASK&~(this.rowUsed[r]|this.colUsed[c]|this.boxUsed[boxIndex(r,c)]);this.masks[idx]=mask;if(!mask)this.valid=false;}return this.valid;};
  ClassicCandidateState.prototype.candidateMask=function(row,col){return this.masks[cellIndex(row,col)];};ClassicCandidateState.prototype.candidates=function(row,col){return digitsFromMask(this.candidateMask(row,col));};ClassicCandidateState.prototype.cloneGrid=function(){return this.grid.map(function(row){return row.slice();});};
  function normalizeCellAction(action,name){if(!action||!Number.isInteger(action.cell)||action.cell<0||action.cell>=81||!Number.isInteger(action.digit)||action.digit<1||action.digit>9)throw new TypeError(name+' requires {cell:0..80,digit:1..9}');return {cell:action.cell,digit:action.digit};}
  function sortActions(list){return list.slice().sort(function(a,b){return a.cell-b.cell||a.digit-b.digit;});}function uniqueActions(list){var out=[],last='';for(var i=0;i<list.length;i++){var key=list[i].cell+':'+list[i].digit;if(key!==last)out.push(list[i]);last=key;}return out;}
  function normalizeDeduction(raw){if(!raw||!TECHNIQUES[raw.techniqueId])throw new TypeError('unknown techniqueId');var meta=TECHNIQUES[raw.techniqueId],placements=uniqueActions(sortActions((raw.placements||[]).map(function(x){return normalizeCellAction(x,'placement');}))),eliminations=uniqueActions(sortActions((raw.eliminations||[]).map(function(x){return normalizeCellAction(x,'elimination');})));if(!placements.length&&!eliminations.length)throw new TypeError('deduction must change state');var overlap={};placements.forEach(function(x){overlap[x.cell+':'+x.digit]=1;});eliminations.forEach(function(x){if(overlap[x.cell+':'+x.digit])throw new TypeError('same candidate cannot be placed and eliminated');});return Object.freeze({techniqueId:raw.techniqueId,familyId:meta.familyId,baseRating:meta.baseRating,priority:meta.priority,placements:Object.freeze(placements),eliminations:Object.freeze(eliminations),anchors:Object.freeze((raw.anchors||[]).slice().sort(function(a,b){return a-b;})),houses:Object.freeze((raw.houses||[]).slice().sort()),candidateNodes:Object.freeze((raw.candidateNodes||[]).slice()),proofEdges:Object.freeze((raw.proofEdges||[]).slice()),complexity:Object.freeze(Object.assign({},raw.complexity||{})),explanationData:Object.freeze(Object.assign({},raw.explanationData||{}))});}
  function deductionStateKey(d){var n=normalizeDeduction(d);return n.placements.map(function(x){return 'P'+x.cell+'='+x.digit;}).concat(n.eliminations.map(function(x){return 'E'+x.cell+'!='+x.digit;})).join('|');}function compareDeductions(a,b){var na=normalizeDeduction(a),nb=normalizeDeduction(b);return na.priority-nb.priority||deductionStateKey(na).localeCompare(deductionStateKey(nb))||na.techniqueId.localeCompare(nb.techniqueId);}
  function countSolutions(source,limit){limit=limit==null?2:limit;if(!Number.isInteger(limit)||limit<1)throw new RangeError('limit must be >=1');var initial=new ClassicCandidateState(source);if(!initial.valid)return 0;var grid=initial.cloneGrid(),rowUsed=new Uint16Array(initial.rowUsed),colUsed=new Uint16Array(initial.colUsed),boxUsed=new Uint16Array(initial.boxUsed),found=0;function search(){if(found>=limit)return;var best=-1,bestMask=0,bestCount=10;for(var idx=0;idx<81;idx++){var rc=rowCol(idx),r=rc[0],c=rc[1];if(grid[r][c])continue;var mask=FULL_MASK&~(rowUsed[r]|colUsed[c]|boxUsed[boxIndex(r,c)]),cnt=bitCount(mask);if(!cnt)return;if(cnt<bestCount){best=idx;bestMask=mask;bestCount=cnt;if(cnt===1)break;}}if(best<0){found++;return;}var rc=rowCol(best),r=rc[0],c=rc[1],b=boxIndex(r,c);for(var bits=bestMask;bits&&found<limit;bits&=bits-1){var bit=bits&-bits,digit=digitsFromMask(bit)[0];grid[r][c]=digit;rowUsed[r]|=bit;colUsed[c]|=bit;boxUsed[b]|=bit;search();grid[r][c]=0;rowUsed[r]&=~bit;colUsed[c]&=~bit;boxUsed[b]&=~bit;}}search();return found;}function isSolvedGrid(source){var state=new ClassicCandidateState(source);if(!state.valid)return false;for(var r=0;r<9;r++)for(var c=0;c<9;c++)if(!state.grid[r][c])return false;return true;}
  var api={FULL_MASK:FULL_MASK,FAMILY_IDS:FAMILY_IDS,TECHNIQUES:TECHNIQUES,bitForDigit:bitForDigit,bitCount:bitCount,digitsFromMask:digitsFromMask,boxIndex:boxIndex,cellIndex:cellIndex,rowCol:rowCol,parseGrid:parseGrid,ClassicCandidateState:ClassicCandidateState,normalizeDeduction:normalizeDeduction,deductionStateKey:deductionStateKey,compareDeductions:compareDeductions,countSolutions:countSolutions,isSolvedGrid:isSolvedGrid};if(typeof module!=='undefined'&&module.exports)module.exports=api;root.ClassicHumanContracts=api;
})(typeof globalThis!=='undefined'?globalThis:this);
