(function(root){'use strict';
  var C=root.ClassicHumanContracts;if(!C&&typeof require==='function')C=require('./contracts.js');
  var FULL=C.FULL_MASK,bitForDigit=C.bitForDigit,bitCount=C.bitCount,digitsFromMask=C.digitsFromMask,cellIndex=C.cellIndex,rowCol=C.rowCol,normalizeDeduction=C.normalizeDeduction,compareDeductions=C.compareDeductions;

  var DEFAULT_MAX_PRIMARY_SECTORS=4,DEFAULT_MAX_DIGITS=6,DEFAULT_MAX_PATTERNS=64,DEFAULT_MAX_COMBINATIONS=20000;
  function optionInt(options,key,def,min,max){var v=options&&options[key]!=null?options[key]:def;if(!Number.isInteger(v)||v<min||v>max)throw new RangeError(key+' must be '+min+'..'+max);return v;}
  function unsolved(state,cell){var rc=rowCol(cell);return !state.grid[rc[0]][rc[1]];}
  function combinations(items,size,visit,ctx){var chosen=[];function rec(start){if(ctx.stopped)return;if(chosen.length===size){ctx.tick();if(!ctx.stopped)visit(chosen.slice());return;}for(var i=start;i<=items.length-(size-chosen.length)&&!ctx.stopped;i++){chosen.push(items[i]);rec(i+1);chosen.pop();}}rec(0);}
  function commonMissingDigits(state,orientation,sectors){var mask=FULL;for(var i=0;i<sectors.length;i++){var used=0,s=sectors[i];for(var p=0;p<9;p++){var r=orientation==='rows'?s:p,c=orientation==='rows'?p:s,v=state.grid[r][c];if(v)used|=bitForDigit(v);}mask&=FULL&~used;}return digitsFromMask(mask);}
  function baseNodes(state,orientation,sectors,digits){var nodes=[];for(var si=0;si<sectors.length;si++){var s=sectors[si];for(var di=0;di<digits.length;di++){var d=digits[di],bit=bitForDigit(d),truth=[];for(var p=0;p<9;p++){var r=orientation==='rows'?s:p,c=orientation==='rows'?p:s,cell=cellIndex(r,c);if(unsolved(state,cell)&&(state.masks[cell]&bit))truth.push(cell);}if(!truth.length)return null;for(var ti=0;ti<truth.length;ti++)nodes.push({cell:truth[ti],digit:d,truth:si*digits.length+di});}}return nodes;}
  function buildCoverLinks(nodes,orientation){var byCell={},byCross={};for(var i=0;i<nodes.length;i++){var n=nodes[i],rc=rowCol(n.cell),cross=orientation==='rows'?rc[1]:rc[0],ck=n.cell,xk=cross+':'+n.digit;(byCell[ck]||(byCell[ck]=[])).push(i);(byCross[xk]||(byCross[xk]=[])).push(i);}var links=[];Object.keys(byCell).map(Number).sort(function(a,b){return a-b;}).forEach(function(cell){var ns=byCell[cell];if(ns.length>=2)links.push({type:'cell',index:cell,digit:0,nodes:ns.slice()});});Object.keys(byCross).sort(function(a,b){var aa=a.split(':').map(Number),bb=b.split(':').map(Number);return aa[0]-bb[0]||aa[1]-bb[1];}).forEach(function(key){var parts=key.split(':').map(Number),ns=byCross[key];if(ns.length>=2)links.push({type:orientation==='rows'?'column-digit':'row-digit',index:parts[0],digit:parts[1],nodes:ns.slice()});});return links;}
  function exactCover(nodes,links,truthCount,ctx,visit){var byNode=Array.from({length:nodes.length},function(){return [];});for(var li=0;li<links.length;li++)for(var ni=0;ni<links[li].nodes.length;ni++)byNode[links[li].nodes[ni]].push(li);var covered=new Uint8Array(nodes.length),coveredCount=0,chosen=[];
    function compatible(li){var ns=links[li].nodes;for(var i=0;i<ns.length;i++)if(covered[ns[i]])return false;return true;}
    function rec(){if(ctx.stopped)return;if(coveredCount===nodes.length){if(chosen.length===truthCount)visit(chosen.map(function(x){return links[x];}));return;}if(chosen.length>=truthCount)return;var remainingLinks=truthCount-chosen.length,remainingNodes=nodes.length-coveredCount;if(remainingNodes<remainingLinks*2)return;var opts=null;for(var n=0;n<nodes.length;n++){if(covered[n])continue;var local=[];for(var j=0;j<byNode[n].length;j++){var li=byNode[n][j];if(compatible(li))local.push(li);}if(!local.length)return;if(opts===null||local.length<opts.length){opts=local;if(opts.length===1)break;}}opts.sort(function(a,b){return links[b].nodes.length-links[a].nodes.length||links[a].type.localeCompare(links[b].type)||links[a].index-links[b].index||links[a].digit-links[b].digit;});for(var oi=0;oi<opts.length&&!ctx.stopped;oi++){ctx.tick();if(ctx.stopped)return;var pick=opts[oi],ns=links[pick].nodes;chosen.push(pick);for(var k=0;k<ns.length;k++){covered[ns[k]]=1;coveredCount++;}rec();for(k=0;k<ns.length;k++){covered[ns[k]]=0;coveredCount--;}chosen.pop();}}
    rec();
  }
  function coverEliminations(state,orientation,sectors,digits,links,nodes){var base={},out=[],seen={};for(var i=0;i<nodes.length;i++)base[nodes[i].cell+':'+nodes[i].digit]=1;function add(cell,digit){var k=cell+':'+digit;if(base[k]||seen[k]||!unsolved(state,cell)||(state.masks[cell]&bitForDigit(digit))===0)return;seen[k]=1;out.push({cell:cell,digit:digit});}
    for(i=0;i<links.length;i++){var l=links[i];if(l.type==='cell'){for(var d=1;d<=9;d++)add(l.index,d);}else{for(var p=0;p<9;p++){var r=orientation==='rows'?p:l.index,c=orientation==='rows'?l.index:p;add(cellIndex(r,c),l.digit);}}}out.sort(function(a,b){return a.cell-b.cell||a.digit-b.digit;});return out;}
  function coverDescriptor(orientation,l){if(l.type==='cell')return {type:'cell',cell:l.index};return {type:l.type,house:(orientation==='rows'?'c':'r')+(l.index+1),digit:l.digit};}
  function findingKey(d){return C.deductionStateKey(d)+'|'+d.explanationData.orientation+'|'+d.explanationData.primarySectors.join(',')+'|'+d.explanationData.digits.join(',')+'|'+JSON.stringify(d.explanationData.covers);}
  function findMultiSectorLockedSet(state,options){options=options||{};var maxPrimary=optionInt(options,'maxPrimarySectors',DEFAULT_MAX_PRIMARY_SECTORS,2,DEFAULT_MAX_PRIMARY_SECTORS),maxDigits=optionInt(options,'maxDigits',DEFAULT_MAX_DIGITS,2,DEFAULT_MAX_DIGITS),maxPatterns=optionInt(options,'maxPatterns',DEFAULT_MAX_PATTERNS,1,DEFAULT_MAX_PATTERNS),maxCombinations=optionInt(options,'maxCombinations',DEFAULT_MAX_COMBINATIONS,1,DEFAULT_MAX_COMBINATIONS),out=[],seen={};
    function orientationPass(orientation){var ctx={count:0,stopped:false,tick:function(){this.count++;if(this.count>maxCombinations)this.stopped=true;}},sectors=[0,1,2,3,4,5,6,7,8];for(var sc=Math.min(maxPrimary,4);sc>=2&&!ctx.stopped&&out.length<maxPatterns;sc--)combinations(sectors,sc,function(primary){var common=commonMissingDigits(state,orientation,primary);for(var dc=Math.min(maxDigits,common.length);dc>=2&&!ctx.stopped&&out.length<maxPatterns;dc--)combinations(common,dc,function(digits){var truthCount=primary.length*digits.length,nodes=baseNodes(state,orientation,primary,digits);if(!nodes||nodes.length<truthCount*2)return;var links=buildCoverLinks(nodes,orientation);if(links.length<truthCount)return;exactCover(nodes,links,truthCount,ctx,function(covers){if(out.length>=maxPatterns)return;var elims=coverEliminations(state,orientation,primary,digits,covers,nodes);if(!elims.length)return;var houses=primary.map(function(s){return (orientation==='rows'?'r':'c')+(s+1);});for(var ci=0;ci<covers.length;ci++)if(covers[ci].type!=='cell')houses.push((orientation==='rows'?'c':'r')+(covers[ci].index+1));var d=normalizeDeduction({techniqueId:'multi-sector-locked-set',eliminations:elims,anchors:Array.from(new Set(nodes.map(function(n){return n.cell;}))),houses:houses,complexity:{primarySectors:primary.length,digits:digits.length,truths:truthCount,baseCandidates:nodes.length,covers:covers.length},explanationData:{scope:'classical-rank-zero',orientation:orientation,primarySectors:primary.slice(),digits:digits.slice(),truthCount:truthCount,baseCandidates:nodes.map(function(n){return {cell:n.cell,digit:n.digit,truth:n.truth};}),covers:covers.map(function(l){return coverDescriptor(orientation,l);}),rank:0}});var key=findingKey(d);if(!seen[key]){seen[key]=1;out.push(d);}});},ctx);},ctx);return ctx.count;}
    orientationPass('rows');if(out.length<maxPatterns)orientationPass('columns');out.sort(compareDeductions);return out.slice(0,maxPatterns);
  }
  var api={findMultiSectorLockedSet:findMultiSectorLockedSet,DEFAULT_MAX_PRIMARY_SECTORS:DEFAULT_MAX_PRIMARY_SECTORS,DEFAULT_MAX_DIGITS:DEFAULT_MAX_DIGITS,DEFAULT_MAX_PATTERNS:DEFAULT_MAX_PATTERNS,DEFAULT_MAX_COMBINATIONS:DEFAULT_MAX_COMBINATIONS};if(typeof module!=='undefined'&&module.exports)module.exports=api;root.ClassicHumanMSLS=api;
})(typeof globalThis!=='undefined'?globalThis:this);
