(function(root){'use strict';
  var E=root.ClassicHumanPoolEvaluator,C=root.ClassicHumanPoolCheckpoint;
  if(!E&&typeof require==='function')E=require('./pool-evaluator.js');if(!C&&typeof require==='function')C=require('./pool-checkpoint.js');
  function percentile(sorted,p){if(!sorted.length)return null;return sorted[Math.ceil(p*sorted.length)-1];}
  function auditPoolResults(results){if(!Array.isArray(results))throw new TypeError('results must be an array');var reasons={},bands={},hashes=new Set(),duplicates=0,times=[];results.forEach(function(item){if(!item||typeof item!=='object'||!item.result)throw new TypeError('audit item invalid');var reason=item.result.reason;reasons[reason]=(reasons[reason]||0)+1;if(item.elapsedMs!=null){if(typeof item.elapsedMs!=='number'||!Number.isFinite(item.elapsedMs)||item.elapsedMs<0)throw new TypeError('elapsedMs invalid');times.push(item.elapsedMs);}if(reason===E.REASONS.ACCEPTED){var r=item.result.record,key=r.puzzleHash||r.puzzle;if(hashes.has(key))duplicates++;else hashes.add(key);bands[r.band]=(bands[r.band]||0)+1;}});times.sort(function(a,b){return a-b;});var accepted=reasons[E.REASONS.ACCEPTED]||0,total=results.length;return Object.freeze({total:total,accepted:accepted,acceptanceRate:total?accepted/total:0,reasons:Object.freeze(reasons),bands:Object.freeze(bands),duplicates:duplicates,runtime:Object.freeze({count:times.length,p50:percentile(times,.50),p95:percentile(times,.95),max:times.length?times[times.length-1]:null})});}
  function counts(values,keyFn){var m={};values.forEach(function(v){var k=keyFn(v);m[k]=(m[k]||0)+1;});var out={};Object.keys(m).sort().forEach(function(k){out[k]=m[k];});return Object.freeze(out);}
  function stats(values){if(!values.length)return Object.freeze({min:null,p50:null,p95:null,max:null});var a=values.slice().sort(function(x,y){return x-y;});return Object.freeze({min:a[0],p50:percentile(a,.5),p95:percentile(a,.95),max:a[a.length-1]});}
  function clueCount(p){var n=0;for(var i=0;i<p.length;i++)if(p[i]!=='0'&&p[i]!=='.')n++;return n;}function clueMask(p){var s='';for(var i=0;i<p.length;i++)s+=(p[i]==='0'||p[i]==='.')?'0':'1';return s;}
  function occupancySignature(p){var rows=[],cols=[],r,c,n;for(r=0;r<9;r++){n=0;for(c=0;c<9;c++)if(p[r*9+c]!=='0')n++;rows.push(n);}for(c=0;c<9;c++){n=0;for(r=0;r<9;r++)if(p[r*9+c]!=='0')n++;cols.push(n);}return rows.join('')+'/'+cols.join('');}
  function techniqueSignature(r){var used=Object.keys(r.techniqueCounts||{}).filter(function(k){return r.techniqueCounts[k]>0;}).sort();return used.join('+')||'none';}
  function maxMaskSimilarity(records){if(records.length<2)return null;var masks=records.map(function(r){return clueMask(r.puzzle);}),max=0;for(var i=0;i<masks.length;i++)for(var j=i+1;j<masks.length;j++){var same=0;for(var k=0;k<81;k++)if(masks[i][k]===masks[j][k])same++;max=Math.max(max,same/81);}return Number(max.toFixed(4));}
  function auditCheckpoint(raw){if(!C)throw new Error('ClassicHumanPoolCheckpoint unavailable');var cp=C.normalizeCheckpoint(raw),records=cp.records,attempted=cp.attempted,accepted=records.length,puzzleHashes=records.map(function(r){return r.puzzleHash;}),recordHashes=records.map(function(r){return r.recordHash;}),maskCounts=counts(records,function(r){return clueMask(r.puzzle);});var exactMaskDuplicates=Object.keys(maskCounts).reduce(function(n,k){return n+Math.max(0,maskCounts[k]-1);},0);var s={schemaVersion:1,targetBand:cp.targetBand,generatorProfile:cp.generatorProfile,solverVersion:cp.solverVersion,raterVersion:cp.raterVersion,startSeed:cp.startSeed,nextSeed:cp.nextSeed,attempted:attempted,accepted:accepted,acceptanceRate:attempted?Number((accepted/attempted).toFixed(4)):0,rejections:cp.rejections,duplicates:cp.duplicates,duplicateRate:attempted?Number((cp.duplicates/attempted).toFixed(4)):0,score:stats(records.map(function(r){return r.score;})),clueCount:stats(records.map(function(r){return clueCount(r.puzzle);})),hardestTechniques:counts(records,function(r){return r.hardestTechnique||'none';}),techniqueSignatures:counts(records,techniqueSignature),occupancySignatures:counts(records,function(r){return occupancySignature(r.puzzle);}),puzzleHashesUnique:new Set(puzzleHashes).size===puzzleHashes.length,recordHashesUnique:new Set(recordHashes).size===recordHashes.length,exactMaskDuplicates:exactMaskDuplicates,maxMaskSimilarity:maxMaskSimilarity(records)};var minAcceptance=cp.targetBand==='expert'?.20:.80,maxSignature=Object.keys(s.techniqueSignatures).reduce(function(m,k){return Math.max(m,s.techniqueSignatures[k]);},0),failures=[];if(s.acceptanceRate<minAcceptance)failures.push('ACCEPTANCE_RATE');if(s.duplicateRate>.02)failures.push('DUPLICATE_RATE');if(!s.puzzleHashesUnique)failures.push('PUZZLE_HASH_DUPLICATE');if(!s.recordHashesUnique)failures.push('RECORD_HASH_DUPLICATE');if(s.exactMaskDuplicates>0)failures.push('CLUE_MASK_DUPLICATE');if(cp.targetBand==='expert'&&accepted>=12&&maxSignature/accepted>.60)failures.push('TECHNIQUE_SIGNATURE_CONCENTRATION');s.gate=Object.freeze({pass:failures.length===0,failures:Object.freeze(failures)});return Object.freeze(s);}
  var api={auditPoolResults:auditPoolResults,auditCheckpoint:auditCheckpoint,stats:stats,clueCount:clueCount,clueMask:clueMask,occupancySignature:occupancySignature,techniqueSignature:techniqueSignature};if(typeof module!=='undefined'&&module.exports)module.exports=api;root.ClassicHumanPoolAudit=api;
})(typeof globalThis!=='undefined'?globalThis:this);
